/**
 * Map registry. Two sources of truth:
 *
 *   1. KANTO_OVERWORLD: stitched from FireRed outdoor zones at offsets
 *      auto-derived from pokefirered's connection graph
 *      (scripts/stitch-firered-overworld.mjs).
 *
 *   2. Indoor maps: every Pallet Town interior, gym, mart, pokémon center,
 *      cave, tower, mansion, hideout, S.S. Anne floor, Silph Co floor, and
 *      League room is loaded from its canonical pokefirered layout via
 *      `src/data/firered/indoorMaps.generated.ts` (autogenerated by
 *      scripts/generate-indoor-maps.mjs).
 *
 * Round-trip warp pins are auto-derived: for every indoor map M, every exit
 * warp going back to KANTO_OVERWORLD is rewritten to land at the world coord
 * of the corresponding outdoor entry (one tile south of the door, so the
 * player isn't standing on the warp tile after exiting).
 */

import { bridgeStitchedKanto, type StitchedDescriptor } from '../../lib/firered/multiZoneBridge';
import { FIRERED_INDOOR_MAPS } from '../firered/indoorMaps.generated';
import type { MapData } from '../../types';

import stitched_kanto from '../../artifacts/firered/maps/STITCHED_KANTO_OVERWORLD.json';

const _stitched = bridgeStitchedKanto(stitched_kanto as StitchedDescriptor);

// Index outdoor warps by their indoor target so we can auto-pin exit warps
// on each indoor map. Each entry: indoor MapID → list of (worldX, worldY)
// outdoor entry coords. Multiple entries when an indoor map has multiple
// doors leading to it (e.g., the gym + mart entrances on the same city map).
const outdoorEntryByTarget = new Map<string, Array<{ x: number; y: number }>>();
for (const w of _stitched.warps) {
  const list = outdoorEntryByTarget.get(w.targetMap) ?? [];
  list.push({ x: w.x, y: w.y });
  outdoorEntryByTarget.set(w.targetMap, list);
}

// Pin every indoor map's exit warp to a world coord south of the matching
// outdoor door. The +1 in y lands the player just past the door so they
// don't stand on the warp tile and immediately re-warp.
for (const [mapId, indoor] of Object.entries(FIRERED_INDOOR_MAPS)) {
  const outdoorEntries = outdoorEntryByTarget.get(mapId);
  if (!outdoorEntries?.length) continue;
  const exitTarget = { x: outdoorEntries[0].x, y: outdoorEntries[0].y + 1 };
  for (const w of indoor.warps) {
    if (w.targetMap === 'KANTO_OVERWORLD') {
      w.targetPos = exitTarget;
    }
  }
}

// Also pin the stitched outdoor warps (overworld → indoor) to land at the
// indoor map's first warp tile, which is the canonical FireRed front door.
for (const w of _stitched.warps) {
  const indoor = FIRERED_INDOOR_MAPS[w.targetMap as keyof typeof FIRERED_INDOOR_MAPS];
  if (!indoor) continue;
  // Find the indoor warp that targets KANTO_OVERWORLD — that's the front
  // door tile from inside, which is the same tile the player should land
  // on when entering.
  const entry = indoor.warps.find(iw => iw.targetMap === 'KANTO_OVERWORLD');
  if (entry) w.targetPos = { x: entry.x, y: entry.y };
}

export const MAP_KANTO_OVERWORLD: MapData = {
  tiles: _stitched.tiles,
  warps: _stitched.warps as MapData['warps'],
  firered: true,
  fireredLayout: _stitched,
};

export const worldMaps = {
  KANTO_OVERWORLD: MAP_KANTO_OVERWORLD,
  ...FIRERED_INDOOR_MAPS,
} as const;
