/**
 * Map registry. Two sources of truth:
 *
 *   1. KANTO_OVERWORLD: stitched from FireRed outdoor zones at offsets
 *      auto-derived from pokefirered's connection graph
 *      (scripts/stitch-firered-overworld.mjs).
 *
 *   2. Indoor maps: every Pallet Town interior, gym, mart, pokémon center,
 *      cave, tower, mansion, hideout, S.S. Anne floor, Silph Co floor, and
 *      League room is loaded from its canonical pokefirered layout via
 *      `src/data/firered/indoorMaps.generated.ts` (autogenerated by
 *      scripts/generate-indoor-maps.mjs).
 *
 * Round-trip warp pins are auto-derived: for every indoor map M, every exit
 * warp going back to KANTO_OVERWORLD is rewritten to land at the world coord
 * of the corresponding outdoor entry (one tile south of the door, so the
 * player isn't standing on the warp tile after exiting).
 */

import { bridgeStitchedKanto, type StitchedDescriptor } from '../../lib/firered/multiZoneBridge';
import { FIRERED_INDOOR_MAPS } from '../firered/indoorMaps.generated';
import type { MapData } from '../../types';

import stitched_kanto from '../../artifacts/firered/maps/STITCHED_KANTO_OVERWORLD.json';

const _stitched = bridgeStitchedKanto(stitched_kanto as StitchedDescriptor);

// Index outdoor warps by their indoor target so we can auto-pin exit warps
// on each indoor map. Each entry: indoor MapID → list of (worldX, worldY)
// outdoor entry coords. Multiple entries when an indoor map has multiple
// doors leading to it (e.g., the gym + mart entrances on the same city map).
const outdoorEntryByTarget = new Map<string, Array<{ x: number; y: number }>>();
for (const w of _stitched.warps) {
  const list = outdoorEntryByTarget.get(w.targetMap) ?? [];
  list.push({ x: w.x, y: w.y });
  outdoorEntryByTarget.set(w.targetMap, list);
}

// Pin every indoor map's exit warp to a world coord south of the matching
// outdoor door. The +1 in y lands the player just past the door so they
// don't stand on the warp tile and immediately re-warp.
for (const [mapId, indoor] of Object.entries(FIRERED_INDOOR_MAPS)) {
  const outdoorEntries = outdoorEntryByTarget.get(mapId);
  if (!outdoorEntries?.length) continue;
  const exitTarget = { x: outdoorEntries[0].x, y: outdoorEntries[0].y + 1 };
  for (const w of indoor.warps) {
    if (w.targetMap === 'KANTO_OVERWORLD') {
      w.targetPos = exitTarget;
    }
  }
}

// Also pin the stitched outdoor warps (overworld → indoor) to land at the
// indoor map's first warp tile, which is the canonical FireRed front door.
for (const w of _stitched.warps) {
  const indoor = FIRERED_INDOOR_MAPS[w.targetMap as keyof typeof FIRERED_INDOOR_MAPS];
  if (!indoor) continue;
  // Find the indoor warp that targets KANTO_OVERWORLD — that's the front
  // door tile from inside, which is the same tile the player should land
  // on when entering.
  const entry = indoor.warps.find(iw => iw.targetMap === 'KANTO_OVERWORLD');
  if (entry) w.targetPos = { x: entry.x, y: entry.y };
}

// Special-case: VIRIDIAN_FOREST is an indoor map but its outdoor entrances
// in Route 2 are tiny gate buildings (MAP_ROUTE2_VIRIDIAN_FOREST_*_ENTRANCE)
// that collapse to KANTO_OVERWORLD. The auto-pin loop above can't see those,
// so the forest's exit warps are left at raw forest-local coords (which land
// on KANTO_OVERWORLD wall tiles). Hand-pin them to the Route 2 entrance
// tiles, then add the matching outdoor → forest warps so the round-trip
// works (Route 2 north & south entrances). Numbers come from FireRed.
const FOREST_NORTH_ENTRY = { x: 65, y: 114 };
const FOREST_SOUTH_ENTRY = { x: 65, y: 152 };
const forest = FIRERED_INDOOR_MAPS.VIRIDIAN_FOREST;
if (forest) {
  for (const w of forest.warps) {
    if (w.targetMap !== 'KANTO_OVERWORLD') continue;
    // Forest top (y < 30) → Route 2 north entrance; forest bottom → south.
    w.targetPos = w.y < 30 ? FOREST_NORTH_ENTRY : FOREST_SOUTH_ENTRY;
  }
}
// Outdoor → forest warps. Route 2 north gate at world (65–66, 113); south
// gate at (65–66, 151). Player walks onto the gate tile and lands inside
// the forest at the matching exit position (top of forest for north entry,
// bottom for south entry).
_stitched.warps.push(
  { x: 65, y: 113, targetMap: 'VIRIDIAN_FOREST', targetPos: { x: 5, y: 10 } },
  { x: 66, y: 113, targetMap: 'VIRIDIAN_FOREST', targetPos: { x: 5, y: 10 } },
  { x: 65, y: 151, targetMap: 'VIRIDIAN_FOREST', targetPos: { x: 29, y: 61 } },
  { x: 66, y: 151, targetMap: 'VIRIDIAN_FOREST', targetPos: { x: 29, y: 61 } },
);

// Snap any warp whose target landed on a non-walkable tile to the nearest
// walkable tile (BFS, max radius 6). The runtime's getValidTeleportLocation
// otherwise crashes the player back to PLAYERS_HOUSE_2F with a SYSTEM ERROR
// overlay — which is much worse than landing one tile next to the door.
function snapToNearestWalkable(tiles: MapData['tiles'], pos: { x: number; y: number }): { x: number; y: number } {
  const inB = (x: number, y: number) => y >= 0 && y < tiles.length && x >= 0 && x < tiles[0].length;
  if (inB(pos.x, pos.y) && tiles[pos.y][pos.x].walkable) return pos;
  const seen = new Set<string>();
  const queue: Array<{ x: number; y: number; d: number }> = [{ ...pos, d: 0 }];
  while (queue.length) {
    const c = queue.shift()!;
    const k = `${c.x},${c.y}`;
    if (seen.has(k)) continue;
    seen.add(k);
    if (c.d > 15) continue;
    if (inB(c.x, c.y) && tiles[c.y][c.x].walkable) return { x: c.x, y: c.y };
    for (const [dx, dy] of [[1,0],[-1,0],[0,1],[0,-1]]) {
      queue.push({ x: c.x + dx, y: c.y + dy, d: c.d + 1 });
    }
  }
  return pos; // give up — caller's getValidTeleportLocation will fall back
}

const indoorMapsArr = Object.entries(FIRERED_INDOOR_MAPS) as Array<[string, MapData]>;
for (const w of _stitched.warps) {
  const target = FIRERED_INDOOR_MAPS[w.targetMap as keyof typeof FIRERED_INDOOR_MAPS];
  if (!target || !w.targetPos) continue;
  w.targetPos = snapToNearestWalkable(target.tiles, w.targetPos);
}
for (const [, indoor] of indoorMapsArr) {
  for (const w of indoor.warps) {
    if (!w.targetPos) continue;
    const target = w.targetMap === 'KANTO_OVERWORLD' ? _stitched : FIRERED_INDOOR_MAPS[w.targetMap as keyof typeof FIRERED_INDOOR_MAPS];
    if (!target) continue;
    w.targetPos = snapToNearestWalkable(target.tiles, w.targetPos);
  }
}

// Resolve indoor→indoor warp targetPos from the canonical FireRed
// dest_warp_id. In the GBA game, dest_warp_id is an index into the
// destination map's warp_events array. Without this, cave ladder pairs
// (MT_MOON ↔ MT_MOON_B1F, etc.) land on the wrong tile and the
// reciprocal-warp check fails.
for (const [, indoor] of indoorMapsArr) {
  for (const w of indoor.warps) {
    if (!w.destWarpId || w.targetMap === 'KANTO_OVERWORLD') continue;
    const destIndoor = FIRERED_INDOOR_MAPS[w.targetMap as keyof typeof FIRERED_INDOOR_MAPS];
    const destEvents = (destIndoor as any)?.fireredLayout?.meta?.warp_events;
    if (!destEvents) continue;
    const idx = parseInt(w.destWarpId);
    if (isNaN(idx) || !destEvents[idx]) continue;
    w.targetPos = { x: destEvents[idx].x, y: destEvents[idx].y };
    w.targetPos = snapToNearestWalkable(destIndoor.tiles, w.targetPos);
  }
}

export const MAP_KANTO_OVERWORLD: MapData = {
  tiles: _stitched.tiles,
  warps: _stitched.warps as MapData['warps'],
  firered: true,
  fireredLayout: _stitched,
};

export const worldMaps = {
  KANTO_OVERWORLD: MAP_KANTO_OVERWORLD,
  ...FIRERED_INDOOR_MAPS,
} as const;
