import { type Move } from '../types';

/** Helper to create a Move with pp === maxPp */
function move(name: string, type: string, power: number, accuracy: number, maxPp: number, extra?: Partial<Move>): Move {
  const defaultSfxType: Move['sfxType'] =
    power === 0 ? 'glissando' : (type === 'normal' || type === 'rock' || type === 'fighting' ? 'noise' : 'pulse');
  return { name, type, power, accuracy, pp: maxPp, maxPp, sfxType: defaultSfxType, ...extra };
}

export const MOVES: Record<string, Move> = {
  TACKLE:        move('PLACAJE',       'normal',   40, 100, 35),
  THUNDERSHOCK:  move('IMPACTRUENO',   'electric', 40, 100, 30, { statusEffect: 'paralyzed', statusChance: 10 }),
  SCRATCH:       move('ARAÑAZO',       'normal',   40, 100, 35),
  GROWL:         move('GRUÑIDO',       'normal',    0, 100, 40, { statChange: { target: 'enemy', stat: 'attack',  stages: -1 } }),
  GUST:          move('TORNADO',       'flying',   40, 100, 35),
  STRING_SHOT:   move('DISP. SEDA',    'bug',       0,  95, 40, { statChange: { target: 'enemy', stat: 'speed',   stages: -1 } }),
  PECK:          move('PICOTAZO',      'flying',   35, 100, 35),
  EMBER:         move('ASCUAS',        'fire',     40, 100, 25, { statusEffect: 'burn',      statusChance: 10 }),
  WATER_GUN:     move('PISTOLA AGUA',  'water',    40, 100, 25),
  VINE_WHIP:     move('LATIGO CEPA',   'grass',    45, 100, 25),
  POISON_POWDER: move('POLVO VENENO',  'poison',    0,  75, 35, { statusEffect: 'poison',    statusChance: 100 }),
  SLEEP_POWDER:  move('SOMNÍFERO',     'grass',     0,  75, 15, { statusEffect: 'sleep',     statusChance: 100 }),
  ROCK_THROW:    move('LANZARROCAS',   'rock',     50,  90, 15),
  CUT:           move('CORTAR',        'normal',   50,  95, 30),
  STRENGTH:      move('FUERZA',        'normal',   80, 100, 15),
  HARDEN:        move('FORTALEZA',     'normal',    0, 100, 30, { statChange: { target: 'self',  stat: 'defense', stages: +1 } }),
  POUND:         move('GOLPE NORMAL',  'normal',   40, 100, 35),
  // High-crit moves (baseSpeed × 8 / 512 crit chance)
  SLASH:         move('CUCHILLADA',    'normal',   70, 100, 20, { highCrit: true }),
  RAZOR_LEAF:    move('HOJA AFILADA',  'grass',    55,  95, 25, { highCrit: true }),
  // Damage + status / utility
  BUBBLEBEAM:    move('RAYO BURBUJA',  'water',    65, 100, 20),
  THUNDERBOLT:   move('RAYO',          'electric', 90, 100, 15, { statusEffect: 'paralyzed', statusChance: 10 }),
  ICE_BEAM:      move('RAYO HIELO',    'ice',      90, 100, 10, { statusEffect: 'frozen',    statusChance: 10 }),
  FLAMETHROWER:  move('LANZALLAMAS',   'fire',     90, 100, 15, { statusEffect: 'burn',      statusChance: 10 }),
  BODY_SLAM:     move('GOLPE CUERPO',  'normal',   85, 100, 15, { statusEffect: 'paralyzed', statusChance: 30 }),
  CONFUSION:     move('CONFUSIÓN',     'psychic',  50, 100, 25),
  PSYCHIC:       move('PSÍQUICO',      'psychic',  90, 100, 10),
  SURF:          move('SURF',          'water',    90, 100, 15),
  EARTHQUAKE:    move('TERREMOTO',     'ground',  100, 100, 10),
  BLIZZARD:      move('VENTISCA',      'ice',     110,  90,  5, { statusEffect: 'frozen', statusChance: 10 }),
  FIRE_BLAST:    move('LLAMARADA',     'fire',    110,  85,  5, { statusEffect: 'burn',   statusChance: 30 }),
  THUNDER:       move('TRUENO',        'electric',110,  70, 10, { statusEffect: 'paralyzed', statusChance: 30 }),
  HYDRO_PUMP:    move('HIDROBOMBA',    'water',   110,  80,  5),
  // Recoil moves
  DOUBLE_EDGE:   move('DOBLE FILO',    'normal',  120, 100, 15, { recoil: 0.25 }),
  TAKE_DOWN:     move('DERRIBO',       'normal',   90,  85, 20, { recoil: 0.25 }),
  THRASH:        move('GOLPE',         'normal',   90, 100, 20, { rampage: { turns: 2 } }),
  PETAL_DANCE:   move('DANZA PÉTALO',  'grass',    70, 100, 20, { rampage: { turns: 2 } }),
  // Drain moves
  MEGA_DRAIN:    move('MEGA DRENADO',  'grass',    40, 100, 15, { drain: 0.5 }),
  DREAM_EATER:   move('COMESUEÑOS',    'psychic',  65, 100, 15, { drain: 0.5 }),
  // Never-miss
  SWIFT:         move('RAPIDEZ',       'normal',   60, 100, 20, { alwaysHit: true }),
  // Multi-hit
  DOUBLE_KICK:   move('DOBLE PATADA',  'fighting', 30, 100, 30, { multiHit: { minHits: 2, maxHits: 2 } }),
  // Confuse
  SUPERSONIC:    move('SUPERSÓNICO',   'normal',    0,  55, 20, { confuseChance: 100 }),
  // Priority
  QUICK_ATTACK:  move('ATAQUE RÁPIDO', 'normal',   40, 100, 30, { priority: 1 }),
  // Fixed damage
  DRAGON_RAGE:   move('FURIA DRAGÓN',  'dragon',   40, 100, 10, { fixedDmg: 40 }),
  SEISMIC_TOSS:  move('MOV. SÍSM.',    'fighting',  1, 100, 20, { dmgEqualsLevel: true }),
  // Charge / two-turn
  DIG:           move('EXCAVAR',       'ground',   80, 100, 10, { twoTurn: { chargeMessage: '¡cavó un hoyo!', invulnerable: true } }),
  SOLAR_BEAM:    move('RAYO SOLAR',    'grass',   120, 100, 10, { twoTurn: { chargeMessage: '¡tomó luz solar!', invulnerable: false } }),
  // Recharge
  HYPER_BEAM:    move('HIPER RAYO',    'normal',  150,  90,  5, { recharge: true }),
  // Self-sacrifice
  SELFDESTRUCT:  move('AUTODESTR.',    'normal',  200, 100,  5, { faintsUser: true }),
  ROCK_SLIDE:    move('AVALANCHA',     'rock',     75,  90, 10),
  WING_ATTACK:   move('ATAQUE ALA',    'flying',   60, 100, 35),
  PSYBEAM:       move('PSICO RAYO',    'psychic',  65, 100, 20, { confuseChance: 10 }),
  LICK:          move('LENGÜETAZO',    'ghost',    20, 100, 30, { statusEffect: 'paralyzed', statusChance: 30 }),
  MEGA_PUNCH:    move('MEGA PUÑO',     'normal',   80,  85, 20),
  MEGA_KICK:     move('MEGA PATADA',   'normal',   80,  75, 20),
  COUNTER:       move('CONTRAATAQUE',  'fighting',  1, 100, 20),
  SCREECH:       move('CHIRRIDO',      'normal',    0,  85, 40, { statChange: { target: 'enemy', stat: 'defense', stages: -2 } }),
  SMOKESCREEN:   move('PANTALLAHUMO',  'normal',    0, 100, 20, { statChange: { target: 'enemy', stat: 'speed',   stages: -1 } }),
  WITHDRAW:      move('RETIRADA',      'water',     0, 100, 40, { statChange: { target: 'self',  stat: 'defense',  stages: +1 } }),
  HEADBUTT:      move('GOLPE CABEZA',  'normal',   70, 100, 15),
  ROLLING_KICK:  move('PATADA GIRO',   'fighting', 60,  85, 15),
  DRILL_PECK:    move('PICO TALADRO',  'flying',   80, 100, 20),
  THUNDER_WAVE:  move('ONDA TRUENO',   'electric',  0, 100, 20, { statusEffect: 'paralyzed', statusChance: 100 }),
  TOXIC:         move('TÓXICO',        'poison',    0,  85, 10, { statusEffect: 'poison',    statusChance: 100 }),
  HYPNOSIS:      move('HIPNOSIS',      'psychic',   0,  60, 20, { statusEffect: 'sleep',     statusChance: 100 }),
  SPORE:         move('ESPORA',        'grass',     0,  75, 15, { statusEffect: 'sleep',     statusChance: 100 }),
  STUN_SPORE:    move('PARALIZADOR',   'grass',     0,  75, 30, { statusEffect: 'paralyzed', statusChance: 100 }),
  TAIL_WHIP:     move('LÁTIGO',        'normal',    0, 100, 30, { statChange: { target: 'enemy', stat: 'defense', stages: -1 } }),
  LEER:          move('MALICIA',       'normal',    0, 100, 30, { statChange: { target: 'enemy', stat: 'defense', stages: -1 } }),
  GROWTH:        move('CRECIMIENTO',   'normal',    0, 100, 20, { statChange: { target: 'self',  stat: 'special',  stages: +1 } }),
  SWORDS_DANCE:  move('DANZA ESPADA',  'normal',    0, 100, 20, { statChange: { target: 'self',  stat: 'attack',   stages: +2 } }),
  AGILITY:       move('AGILIDAD',      'psychic',   0, 100, 30, { statChange: { target: 'self',  stat: 'speed',    stages: +2 } }),
  AMNESIA:       move('AMNESIA',       'psychic',   0, 100, 20, { statChange: { target: 'self',  stat: 'special',  stages: +2 } }),
  BARRIER:       move('BARRERA',       'psychic',   0, 100, 20, { statChange: { target: 'self',  stat: 'defense',  stages: +2 } }),
  BITE:          move('MORDISCO',      'normal',   60, 100, 25),
  LEECH_SEED:    move('DRENADORAS',    'grass',     0,  90, 10),
  SLUDGE:        move('RESIDUOS',      'poison',   65, 100, 20, { statusEffect: 'poison', statusChance: 30 }),
  // ── 79 new moves from pokered ──
  ABSORB:          move('ABSORBER', 'grass'   ,  20, 100,  20, { drain: 0.5 }),
  ACID:            move('ÁCIDO', 'poison'  ,  40, 100,  30, { statChange: { target: 'enemy', stat: 'defense', stages: -1 } }),
  ACID_ARMOR:      move('ARMADURA ÁCI.', 'poison'  ,   0, 100,  20, { statChange: { target: 'self', stat: 'defense', stages: 2 } }),
  AURORA_BEAM:     move('RAYO AURORA', 'ice'     ,  65, 100,  20, { statChange: { target: 'enemy', stat: 'attack', stages: -1 } }),
  BARRAGE:         move('LLUVIA', 'normal'  ,  15,  85,  20, { multiHit: { minHits: 2, maxHits: 5 } }),
  BIDE:            move('ESPERA', 'normal'  ,   0, 100,  10),
  BIND:            move('ATADURA', 'normal'  ,  15,  85,  20, { trap: { turns: 2 } }),
  BONE_CLUB:       move('HUESO PALO', 'ground'  ,  65,  85,  20),
  BONEMERANG:      move('BUMERANG', 'ground'  ,  50,  90,  10, { multiHit: { minHits: 2, maxHits: 2 } }),
  BUBBLE:          move('BURBUJA', 'water'   ,  20, 100,  30, { statChange: { target: 'enemy', stat: 'speed', stages: -1 } }),
  CHEERLEADER:     move('ANIMADORA', 'normal'  ,   0, 100,  30), // placeholder
  CLAMP:           move('TENAZA', 'water'   ,  35,  85,  10, { trap: { turns: 2 } }),
  COMET_PUNCH:     move('PUÑO COMETA', 'normal'  ,  18,  85,  15, { multiHit: { minHits: 2, maxHits: 5 } }),
  CONFUSE_RAY:     move('RAYO CONFUSO', 'ghost'   ,   0, 100,  10, { confuseChance: 100 }),
  CONSTRICT:       move('RESTRICCIÓN', 'normal'  ,  10, 100,  35),
  CONVERSION:      move('CONVERSIÓN', 'normal'  ,   0, 100,  30),
  CRABHAMMER:      move('MARTILLO', 'water'   ,  90,  85,  10, { highCrit: true }),
  DEFENSE_CURL:    move('RIZO DEFENSA', 'normal'  ,   0, 100,  40, { statChange: { target: 'self', stat: 'defense', stages: 1 } }),
  DIZZY_PUNCH:     move('PUÑO MAREANTE', 'normal'  ,  70, 100,  10),
  DOUBLE_TEAM:     move('DOBLE EQUIPO', 'normal'  ,   0, 100,  15, { statChange: { target: 'self', stat: 'evasion', stages: 1 } }),
  DOUBLESLAP:      move('DOBLE BOFETÓN', 'normal'  ,  15,  85,  10, { multiHit: { minHits: 2, maxHits: 5 } }),
  EGG_BOMB:        move('BOMBA HUEVO', 'normal'  , 100,  75,  10),
  EXPLOSION:       move('EXPLOSIÓN', 'normal'  , 250, 100,   5, { faintsUser: true }),
  FIRE_PUNCH:      move('PUÑO FUEGO', 'fire'    ,  75, 100,  15, { statusEffect: 'burn', statusChance: 10 }),
  FIRE_SPIN:       move('GIRO FUEGO', 'fire'    ,  15,  70,  15, { trap: { turns: 2 } }),
  FLASH:           move('DESTELLO', 'normal'  ,   0, 100,  20, { statChange: { target: 'enemy', stat: 'accuracy', stages: -2 } }),
  FLY:             move('VUELO', 'flying'  ,  70,  95,  15, { twoTurn: { chargeMessage: '¡voló muy alto!', invulnerable: true } }),
  FOCUS_ENERGY:    move('ENERG. FOCAL', 'normal'  ,   0, 100,  30),
  FURY_ATTACK:     move('ATAQUE FURIA', 'normal'  ,  15,  85,  20, { multiHit: { minHits: 2, maxHits: 5 } }),
  FURY_SWIPES:     move('GOLPES FURIA', 'normal'  ,  18,  80,  15, { multiHit: { minHits: 2, maxHits: 5 } }),
  GLARE:           move('MIRADA ESTEL.', 'normal'  ,   0, 100,  30, { statusEffect: 'paralyzed', statusChance: 100 }),
  HAZE:            move('NEBLINA OSC.', 'ice'     ,   0, 100,  30),
  HI_JUMP_KICK:    move('PAT. SALTO A.', 'fighting',  85,  90,  20),
  HORN_ATTACK:     move('CORNEAZO', 'normal'  ,  65, 100,  25),
  HYPER_FANG:      move('SUPER DIENTE', 'normal'  ,  80,  90,  15),
  ICE_PUNCH:       move('PUÑO HIELO', 'ice'     ,  75, 100,  15, { statusEffect: 'frozen', statusChance: 10 }),
  JUMP_KICK:       move('PAT. SALTO', 'fighting',  70,  95,  25),
  KARATE_CHOP:     move('GOLPE KÁRATE', 'fighting',  50, 100,  25, { highCrit: true }),
  KINESIS:         move('KINESIS', 'psychic' ,   0,  80,  15, { statChange: { target: 'enemy', stat: 'accuracy', stages: -2 } }),
  LEECH_LIFE:      move('DRENAJE', 'bug'     ,  20, 100,  15, { drain: 0.5 }),
  LIGHT_SCREEN:    move('PANTALLA LUZ', 'psychic' ,   0, 100,  30),
  LOVELY_KISS:     move('BESO AMOROSO', 'normal'  ,   0,  75,  10, { statusEffect: 'sleep', statusChance: 100 }),
  LOW_KICK:        move('PATADA BAJA', 'fighting',  50, 100,  20),
  MEDITATE:        move('MEDITACIÓN', 'psychic' ,   0, 100,  40, { statChange: { target: 'self', stat: 'attack', stages: 1 } }),
  METRONOME:       move('METRÓNOMO', 'normal'  ,   0, 100,  10),
  MINIMIZE:        move('REDUCCIÓN', 'normal'  ,   0, 100,  20, { statChange: { target: 'self', stat: 'evasion', stages: 1 } }),
  MIRROR_MOVE:     move('MOV. ESPEJO', 'flying'  ,   0, 100,  20),
  NIGHT_SHADE:     move('TINIEBLAS', 'ghost'   ,   1, 100,  15, { dmgEqualsLevel: true }),
  PAY_DAY:         move('DÍA DE PAGO', 'normal'  ,  40, 100,  20),
  PIN_MISSILE:     move('PIN MISIL', 'bug'     ,  14,  85,  20, { multiHit: { minHits: 2, maxHits: 5 } }),
  POISON_GAS:      move('GAS VENENOSO', 'poison'  ,   0,  80,  40, { statusEffect: 'poison', statusChance: 100 }),
  POISON_STING:    move('PICOT. VENENO', 'poison'  ,  15, 100,  35, { statusEffect: 'poison', statusChance: 30 }),
  PSYWAVE:         move('PSIQUI ONDA', 'psychic' ,   1, 100,  15),
  RAGE:            move('FURIA', 'normal'  ,  20, 100,  20),
  RAZOR_WIND:      move('VIENTO CORT.', 'normal'  ,  80, 100,  10),
  RECOVER:         move('RECUPERACIÓN', 'normal'  ,   0, 100,  20, { healSelf: 50 }),
  REFLECT:         move('REFLEJO', 'psychic' ,   0, 100,  20),
  REST:            move('DESCANSO', 'psychic' ,   0, 100,  10, { healSelf: 100, healStatus: true }),
  SHARPEN:         move('AFILAR', 'normal'  ,   0, 100,  30, { statChange: { target: 'self', stat: 'attack', stages: 1 } }),
  SING:            move('CANTO', 'normal'  ,   0,  55,  15, { statusEffect: 'sleep', statusChance: 100 }),
  SKY_ATTACK:      move('ATAQ. CIELO', 'flying'  , 140,  90,   5),
  SLAM:            move('PORTAZO', 'normal'  ,  80,  75,  20),
  SMOG:            move('MOHO', 'poison'  ,  20,  70,  20, { statusEffect: 'poison', statusChance: 40 }),
  SOFTBOILED:      move('AMORTIGUADOR', 'normal'  ,   0, 100,  10, { healSelf: 50 }),
  SONICBOOM:       move('BOMBA SÓNICA', 'normal'  ,   1,  90,  20, { fixedDmg: 20 }),
  SPIKE_CANNON:    move('CLAVO CAÑÓN', 'normal'  ,  20, 100,  15, { multiHit: { minHits: 2, maxHits: 5 } }),
  SPLASH:          move('SALPICADURA', 'normal'  ,   0, 100,  40),
  STOMP:           move('PISOTÓN', 'normal'  ,  65, 100,  20, { statusEffect: 'paralyzed', statusChance: 30 }),
  SUBMISSION:      move('SUBMISIÓN', 'fighting',  80,  80,  25, { recoil: 0.25 }),
  SUBSTITUTE:      move('SUSTITUTO', 'normal'  ,   0, 100,  10),
  SUPER_FANG:      move('SUPER COLMIL.', 'normal'  ,   1,  90,  10, { halfHp: true }),
  THUNDERPUNCH:    move('PUÑO TRUENO', 'electric',  75, 100,  15, { statusEffect: 'paralyzed', statusChance: 10 }),
  TRANSFORM:       move('TRANSFORMAC.', 'normal'  ,   0, 100,  10),
  TRI_ATTACK:      move('TRIPLE ATAQUE', 'normal'  ,  80, 100,  10, { statusEffect: 'paralyzed', statusChance: 20 }),
  TWINEEDLE:       move('DOBLE ATAQUE', 'bug'     ,  25, 100,  20, { statusEffect: 'poison', statusChance: 20, multiHit: { minHits: 2, maxHits: 2 } }),
  VICEGRIP:        move('AGARRÓN', 'normal'  ,  55, 100,  30),
  WATERFALL:       move('CASCADA', 'water'   ,  80, 100,  15),
  DISABLE:      move('ANULACIÓN',    'normal',  0,  100,  20),
  FISSURE:      move('FISURA',       'ground',  0,   25,   5, { ohko: true }),
  GUILLOTINE:   move('GUILLOTINA',   'normal',  0,   30,   5, { ohko: true }),
  HORN_DRILL:   move('PERFORADOR',   'normal',  0,   25,   5, { ohko: true }),
  MIMIC:        move('IMITACIÓN',    'normal',  0,  100,  10),
  MIST:         move('NEBLINA',      'ice',     0,  100,  30),
  SKULL_BASH:   move('CAB. ROCA',    'normal', 100, 100,  15),
  TELEPORT:     move('TELETRANSP.',  'psychic', 0,  100,  20),
  WHIRLWIND:    move('REMOLINO',     'normal',  0,  100,  20),
};
export const LEARNSET_DATABASE: Record<string, { level: number; move: Move }[]> = {
  1: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.GROWL }, { level: 7, move: MOVES.LEECH_SEED }, { level: 10, move: MOVES.VINE_WHIP }, { level: 15, move: MOVES.POISON_POWDER }, { level: 20, move: MOVES.RAZOR_LEAF }, { level: 32, move: MOVES.GROWTH }, { level: 46, move: MOVES.SOLAR_BEAM }],
  2: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.GROWL }, { level: 7, move: MOVES.LEECH_SEED }, { level: 10, move: MOVES.VINE_WHIP }, { level: 15, move: MOVES.POISON_POWDER }, { level: 22, move: MOVES.RAZOR_LEAF }, { level: 38, move: MOVES.GROWTH }, { level: 56, move: MOVES.SOLAR_BEAM }],
  3: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.GROWL }, { level: 7, move: MOVES.LEECH_SEED }, { level: 10, move: MOVES.VINE_WHIP }, { level: 15, move: MOVES.POISON_POWDER }, { level: 22, move: MOVES.RAZOR_LEAF }, { level: 41, move: MOVES.GROWTH }, { level: 65, move: MOVES.SOLAR_BEAM }],
  4: [{ level: 1, move: MOVES.SCRATCH }, { level: 7, move: MOVES.EMBER }, { level: 19, move: MOVES.SMOKESCREEN }, { level: 31, move: MOVES.FLAMETHROWER }, { level: 37, move: MOVES.SLASH }, { level: 43, move: MOVES.DRAGON_RAGE }, { level: 49, move: MOVES.FIRE_SPIN }],
  5: [{ level: 1, move: MOVES.SCRATCH }, { level: 7, move: MOVES.EMBER }, { level: 20, move: MOVES.SMOKESCREEN }, { level: 34, move: MOVES.FLAMETHROWER }, { level: 41, move: MOVES.SLASH }, { level: 48, move: MOVES.DRAGON_RAGE }, { level: 55, move: MOVES.FIRE_SPIN }],
  6: [{ level: 1, move: MOVES.SCRATCH }, { level: 7, move: MOVES.EMBER }, { level: 20, move: MOVES.SMOKESCREEN }, { level: 34, move: MOVES.FLAMETHROWER }, { level: 36, move: MOVES.WING_ATTACK }, { level: 44, move: MOVES.SLASH }, { level: 54, move: MOVES.DRAGON_RAGE }, { level: 64, move: MOVES.FIRE_SPIN }],
  7: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.TAIL_WHIP }, { level: 7, move: MOVES.BUBBLE }, { level: 10, move: MOVES.WITHDRAW }, { level: 13, move: MOVES.WATER_GUN }, { level: 18, move: MOVES.BITE }, { level: 40, move: MOVES.SKULL_BASH }, { level: 47, move: MOVES.HYDRO_PUMP }],
  8: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.TAIL_WHIP }, { level: 7, move: MOVES.BUBBLE }, { level: 10, move: MOVES.WITHDRAW }, { level: 13, move: MOVES.WATER_GUN }, { level: 19, move: MOVES.BITE }, { level: 45, move: MOVES.SKULL_BASH }, { level: 53, move: MOVES.HYDRO_PUMP }],
  9: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.TAIL_WHIP }, { level: 7, move: MOVES.BUBBLE }, { level: 10, move: MOVES.WITHDRAW }, { level: 13, move: MOVES.WATER_GUN }, { level: 19, move: MOVES.BITE }, { level: 55, move: MOVES.SKULL_BASH }, { level: 68, move: MOVES.HYDRO_PUMP }],
  10: [{ level: 1, move: MOVES.TACKLE }],
  11: [{ level: 1, move: MOVES.HARDEN }, { level: 7, move: MOVES.HARDEN }],
  12: [{ level: 1, move: MOVES.CONFUSION }, { level: 10, move: MOVES.CONFUSION }, { level: 13, move: MOVES.POISON_POWDER }, { level: 14, move: MOVES.STUN_SPORE }, { level: 15, move: MOVES.SLEEP_POWDER }, { level: 18, move: MOVES.SUPERSONIC }, { level: 23, move: MOVES.WHIRLWIND }, { level: 34, move: MOVES.PSYBEAM }],
  13: [{ level: 1, move: MOVES.POISON_STING }],
  14: [{ level: 1, move: MOVES.HARDEN }, { level: 7, move: MOVES.HARDEN }],
  15: [{ level: 1, move: MOVES.FURY_ATTACK }, { level: 10, move: MOVES.FURY_ATTACK }, { level: 15, move: MOVES.FOCUS_ENERGY }, { level: 20, move: MOVES.TWINEEDLE }, { level: 25, move: MOVES.RAGE }, { level: 35, move: MOVES.PIN_MISSILE }, { level: 40, move: MOVES.AGILITY }],
  16: [{ level: 1, move: MOVES.TACKLE }, { level: 5, move: MOVES.SAND_ATTACK }, { level: 13, move: MOVES.QUICK_ATTACK }, { level: 19, move: MOVES.WHIRLWIND }, { level: 25, move: MOVES.WING_ATTACK }, { level: 39, move: MOVES.AGILITY }, { level: 47, move: MOVES.MIRROR_MOVE }],
  17: [{ level: 1, move: MOVES.TACKLE }, { level: 5, move: MOVES.SAND_ATTACK }, { level: 13, move: MOVES.QUICK_ATTACK }, { level: 20, move: MOVES.WHIRLWIND }, { level: 27, move: MOVES.WING_ATTACK }, { level: 43, move: MOVES.AGILITY }, { level: 52, move: MOVES.MIRROR_MOVE }],
  18: [{ level: 1, move: MOVES.TACKLE }, { level: 5, move: MOVES.SAND_ATTACK }, { level: 13, move: MOVES.QUICK_ATTACK }, { level: 20, move: MOVES.WHIRLWIND }, { level: 27, move: MOVES.WING_ATTACK }, { level: 48, move: MOVES.AGILITY }, { level: 62, move: MOVES.MIRROR_MOVE }],
  19: [{ level: 1, move: MOVES.TACKLE }, { level: 7, move: MOVES.QUICK_ATTACK }, { level: 20, move: MOVES.FOCUS_ENERGY }],
  20: [{ level: 1, move: MOVES.TACKLE }, { level: 7, move: MOVES.QUICK_ATTACK }],
  21: [{ level: 1, move: MOVES.GROWL }, { level: 7, move: MOVES.LEER }, { level: 13, move: MOVES.FURY_ATTACK }, { level: 31, move: MOVES.MIRROR_MOVE }, { level: 37, move: MOVES.DRILL_PECK }, { level: 43, move: MOVES.AGILITY }],
  22: [{ level: 1, move: MOVES.GROWL }, { level: 7, move: MOVES.LEER }, { level: 13, move: MOVES.FURY_ATTACK }, { level: 32, move: MOVES.MIRROR_MOVE }, { level: 40, move: MOVES.DRILL_PECK }, { level: 47, move: MOVES.AGILITY }],
  23: [{ level: 1, move: MOVES.WRAP }, { level: 8, move: MOVES.POISON_STING }, { level: 13, move: MOVES.BITE }, { level: 20, move: MOVES.GLARE }, { level: 25, move: MOVES.SCREECH }, { level: 32, move: MOVES.ACID }, { level: 44, move: MOVES.HAZE }],
  24: [{ level: 1, move: MOVES.WRAP }, { level: 8, move: MOVES.POISON_STING }, { level: 13, move: MOVES.BITE }, { level: 20, move: MOVES.GLARE }, { level: 28, move: MOVES.SCREECH }, { level: 38, move: MOVES.ACID }, { level: 56, move: MOVES.HAZE }],
  25: [{ level: 1, move: MOVES.GROWL }, { level: 6, move: MOVES.TAIL_WHIP }, { level: 8, move: MOVES.THUNDER_WAVE }, { level: 11, move: MOVES.QUICK_ATTACK }, { level: 15, move: MOVES.DOUBLE_TEAM }, { level: 20, move: MOVES.SLAM }, { level: 33, move: MOVES.AGILITY }, { level: 41, move: MOVES.THUNDER }, { level: 50, move: MOVES.LIGHT_SCREEN }],
  26: [{ level: 1, move: MOVES.TAIL_WHIP }],
  27: [{ level: 1, move: MOVES.SCRATCH }, { level: 6, move: MOVES.DEFENSE_CURL }, { level: 11, move: MOVES.SAND_ATTACK }, { level: 17, move: MOVES.POISON_STING }, { level: 23, move: MOVES.SLASH }, { level: 30, move: MOVES.SWIFT }, { level: 37, move: MOVES.FURY_SWIPES }],
  28: [{ level: 1, move: MOVES.SCRATCH }, { level: 6, move: MOVES.DEFENSE_CURL }, { level: 11, move: MOVES.SAND_ATTACK }, { level: 17, move: MOVES.POISON_STING }, { level: 24, move: MOVES.SLASH }, { level: 33, move: MOVES.SWIFT }, { level: 42, move: MOVES.FURY_SWIPES }],
  29: [{ level: 1, move: MOVES.GROWL }, { level: 8, move: MOVES.TAIL_WHIP }, { level: 12, move: MOVES.DOUBLE_KICK }, { level: 17, move: MOVES.POISON_STING }, { level: 20, move: MOVES.BITE }, { level: 30, move: MOVES.FURY_SWIPES }],
  30: [{ level: 1, move: MOVES.GROWL }, { level: 8, move: MOVES.TAIL_WHIP }, { level: 12, move: MOVES.DOUBLE_KICK }, { level: 18, move: MOVES.POISON_STING }, { level: 22, move: MOVES.BITE }, { level: 34, move: MOVES.FURY_SWIPES }],
  31: [{ level: 1, move: MOVES.SCRATCH }, { level: 22, move: MOVES.BODY_SLAM }],
  32: [{ level: 1, move: MOVES.LEER }, { level: 8, move: MOVES.FOCUS_ENERGY }, { level: 12, move: MOVES.DOUBLE_KICK }, { level: 17, move: MOVES.POISON_STING }, { level: 20, move: MOVES.HORN_ATTACK }, { level: 30, move: MOVES.FURY_ATTACK }, { level: 47, move: MOVES.HORN_DRILL }],
  33: [{ level: 1, move: MOVES.LEER }, { level: 8, move: MOVES.FOCUS_ENERGY }, { level: 12, move: MOVES.DOUBLE_KICK }, { level: 18, move: MOVES.POISON_STING }, { level: 22, move: MOVES.HORN_ATTACK }, { level: 34, move: MOVES.FURY_ATTACK }, { level: 53, move: MOVES.HORN_DRILL }],
  34: [{ level: 1, move: MOVES.FOCUS_ENERGY }, { level: 22, move: MOVES.THRASH }],
  35: [{ level: 1, move: MOVES.POUND }, { level: 9, move: MOVES.SING }, { level: 21, move: MOVES.MINIMIZE }, { level: 25, move: MOVES.DEFENSE_CURL }, { level: 29, move: MOVES.METRONOME }, { level: 41, move: MOVES.LIGHT_SCREEN }],
  36: [{ level: 1, move: MOVES.SING }],
  37: [{ level: 1, move: MOVES.EMBER }, { level: 5, move: MOVES.TAIL_WHIP }, { level: 9, move: MOVES.ROAR }, { level: 13, move: MOVES.QUICK_ATTACK }, { level: 21, move: MOVES.CONFUSE_RAY }, { level: 29, move: MOVES.FLAMETHROWER }, { level: 41, move: MOVES.FIRE_SPIN }],
  38: [{ level: 1, move: MOVES.EMBER }, { level: 45, move: MOVES.FIRE_SPIN }],
  39: [{ level: 1, move: MOVES.SING }, { level: 4, move: MOVES.DEFENSE_CURL }, { level: 9, move: MOVES.POUND }, { level: 14, move: MOVES.DISABLE }, { level: 29, move: MOVES.REST }, { level: 34, move: MOVES.BODY_SLAM }, { level: 49, move: MOVES.DOUBLE_EDGE }],
  40: [{ level: 1, move: MOVES.SING }],
  41: [{ level: 1, move: MOVES.LEECH_LIFE }, { level: 11, move: MOVES.SUPERSONIC }, { level: 16, move: MOVES.BITE }, { level: 21, move: MOVES.WING_ATTACK }, { level: 26, move: MOVES.CONFUSE_RAY }, { level: 46, move: MOVES.HAZE }],
  42: [{ level: 1, move: MOVES.SCREECH }, { level: 11, move: MOVES.SUPERSONIC }, { level: 16, move: MOVES.BITE }, { level: 21, move: MOVES.WING_ATTACK }, { level: 28, move: MOVES.CONFUSE_RAY }, { level: 56, move: MOVES.HAZE }],
  43: [{ level: 1, move: MOVES.ABSORB }, { level: 14, move: MOVES.POISON_POWDER }, { level: 16, move: MOVES.STUN_SPORE }, { level: 18, move: MOVES.SLEEP_POWDER }, { level: 23, move: MOVES.ACID }],
  44: [{ level: 1, move: MOVES.ABSORB }, { level: 14, move: MOVES.POISON_POWDER }, { level: 16, move: MOVES.STUN_SPORE }, { level: 18, move: MOVES.SLEEP_POWDER }, { level: 24, move: MOVES.ACID }],
  45: [{ level: 1, move: MOVES.ABSORB }],
  46: [{ level: 1, move: MOVES.SCRATCH }, { level: 7, move: MOVES.STUN_SPORE }, { level: 13, move: MOVES.POISON_POWDER }, { level: 19, move: MOVES.LEECH_LIFE }, { level: 25, move: MOVES.SPORE }, { level: 31, move: MOVES.SLASH }, { level: 37, move: MOVES.GROWTH }],
  47: [{ level: 1, move: MOVES.SCRATCH }, { level: 7, move: MOVES.STUN_SPORE }, { level: 13, move: MOVES.POISON_POWDER }, { level: 19, move: MOVES.LEECH_LIFE }, { level: 27, move: MOVES.SPORE }, { level: 35, move: MOVES.SLASH }, { level: 43, move: MOVES.GROWTH }],
  48: [{ level: 1, move: MOVES.TACKLE }, { level: 9, move: MOVES.SUPERSONIC }, { level: 17, move: MOVES.CONFUSION }, { level: 20, move: MOVES.POISON_POWDER }, { level: 25, move: MOVES.LEECH_LIFE }, { level: 28, move: MOVES.STUN_SPORE }, { level: 33, move: MOVES.PSYBEAM }, { level: 36, move: MOVES.SLEEP_POWDER }],
  49: [{ level: 1, move: MOVES.TACKLE }, { level: 9, move: MOVES.SUPERSONIC }, { level: 17, move: MOVES.CONFUSION }, { level: 20, move: MOVES.POISON_POWDER }, { level: 25, move: MOVES.LEECH_LIFE }, { level: 28, move: MOVES.STUN_SPORE }, { level: 36, move: MOVES.PSYBEAM }, { level: 42, move: MOVES.SLEEP_POWDER }],
  50: [{ level: 1, move: MOVES.SAND_ATTACK }, { level: 5, move: MOVES.GROWL }, { level: 17, move: MOVES.DIG }, { level: 21, move: MOVES.FURY_SWIPES }, { level: 33, move: MOVES.SLASH }, { level: 41, move: MOVES.EARTHQUAKE }],
  51: [{ level: 1, move: MOVES.TRI_ATTACK }, { level: 5, move: MOVES.GROWL }, { level: 17, move: MOVES.DIG }, { level: 21, move: MOVES.FURY_SWIPES }, { level: 38, move: MOVES.SLASH }, { level: 51, move: MOVES.EARTHQUAKE }],
  52: [{ level: 1, move: MOVES.SCRATCH }, { level: 10, move: MOVES.BITE }, { level: 18, move: MOVES.PAY_DAY }, { level: 31, move: MOVES.SCREECH }, { level: 36, move: MOVES.FURY_SWIPES }, { level: 40, move: MOVES.SLASH }],
  53: [{ level: 1, move: MOVES.SCRATCH }, { level: 10, move: MOVES.BITE }, { level: 18, move: MOVES.PAY_DAY }, { level: 34, move: MOVES.SCREECH }, { level: 42, move: MOVES.FURY_SWIPES }, { level: 49, move: MOVES.SLASH }],
  54: [{ level: 1, move: MOVES.SCRATCH }, { level: 5, move: MOVES.TAIL_WHIP }, { level: 10, move: MOVES.DISABLE }, { level: 16, move: MOVES.CONFUSION }, { level: 23, move: MOVES.SCREECH }, { level: 40, move: MOVES.FURY_SWIPES }, { level: 50, move: MOVES.HYDRO_PUMP }],
  55: [{ level: 1, move: MOVES.SCRATCH }, { level: 5, move: MOVES.TAIL_WHIP }, { level: 10, move: MOVES.DISABLE }, { level: 16, move: MOVES.CONFUSION }, { level: 23, move: MOVES.SCREECH }, { level: 44, move: MOVES.FURY_SWIPES }, { level: 58, move: MOVES.HYDRO_PUMP }],
  56: [{ level: 1, move: MOVES.SCRATCH }, { level: 6, move: MOVES.LOW_KICK }, { level: 11, move: MOVES.KARATE_CHOP }, { level: 16, move: MOVES.FURY_SWIPES }, { level: 21, move: MOVES.FOCUS_ENERGY }, { level: 26, move: MOVES.SEISMIC_TOSS }, { level: 41, move: MOVES.SCREECH }, { level: 46, move: MOVES.THRASH }],
  57: [{ level: 1, move: MOVES.SCRATCH }, { level: 6, move: MOVES.LOW_KICK }, { level: 11, move: MOVES.KARATE_CHOP }, { level: 16, move: MOVES.FURY_SWIPES }, { level: 21, move: MOVES.FOCUS_ENERGY }, { level: 26, move: MOVES.SEISMIC_TOSS }, { level: 28, move: MOVES.RAGE }, { level: 53, move: MOVES.SCREECH }, { level: 62, move: MOVES.THRASH }],
  58: [{ level: 1, move: MOVES.BITE }, { level: 7, move: MOVES.EMBER }, { level: 13, move: MOVES.LEER }, { level: 25, move: MOVES.TAKE_DOWN }, { level: 43, move: MOVES.AGILITY }, { level: 49, move: MOVES.FLAMETHROWER }],
  59: [{ level: 1, move: MOVES.BITE }],
  60: [{ level: 1, move: MOVES.BUBBLE }, { level: 7, move: MOVES.HYPNOSIS }, { level: 13, move: MOVES.WATER_GUN }, { level: 31, move: MOVES.BODY_SLAM }, { level: 43, move: MOVES.HYDRO_PUMP }],
  61: [{ level: 1, move: MOVES.BUBBLE }, { level: 7, move: MOVES.HYPNOSIS }, { level: 13, move: MOVES.WATER_GUN }, { level: 35, move: MOVES.BODY_SLAM }, { level: 51, move: MOVES.HYDRO_PUMP }],
  62: [{ level: 1, move: MOVES.WATER_GUN }, { level: 35, move: MOVES.SUBMISSION }],
  64: [{ level: 1, move: MOVES.CONFUSION }, { level: 16, move: MOVES.CONFUSION }, { level: 18, move: MOVES.DISABLE }, { level: 21, move: MOVES.PSYBEAM }, { level: 23, move: MOVES.REFLECT }, { level: 25, move: MOVES.RECOVER }],
  65: [{ level: 1, move: MOVES.CONFUSION }, { level: 16, move: MOVES.CONFUSION }, { level: 18, move: MOVES.DISABLE }, { level: 21, move: MOVES.PSYBEAM }, { level: 23, move: MOVES.REFLECT }, { level: 25, move: MOVES.RECOVER }],
  66: [{ level: 1, move: MOVES.LOW_KICK }, { level: 7, move: MOVES.FOCUS_ENERGY }, { level: 13, move: MOVES.KARATE_CHOP }, { level: 19, move: MOVES.SEISMIC_TOSS }, { level: 37, move: MOVES.SUBMISSION }],
  67: [{ level: 1, move: MOVES.LOW_KICK }, { level: 7, move: MOVES.FOCUS_ENERGY }, { level: 13, move: MOVES.KARATE_CHOP }, { level: 19, move: MOVES.SEISMIC_TOSS }, { level: 41, move: MOVES.SUBMISSION }],
  68: [{ level: 1, move: MOVES.LOW_KICK }, { level: 7, move: MOVES.FOCUS_ENERGY }, { level: 13, move: MOVES.KARATE_CHOP }, { level: 19, move: MOVES.SEISMIC_TOSS }, { level: 41, move: MOVES.SUBMISSION }],
  69: [{ level: 1, move: MOVES.VINE_WHIP }, { level: 6, move: MOVES.GROWTH }, { level: 11, move: MOVES.WRAP }, { level: 15, move: MOVES.SLEEP_POWDER }, { level: 17, move: MOVES.POISON_POWDER }, { level: 19, move: MOVES.STUN_SPORE }, { level: 23, move: MOVES.ACID }, { level: 37, move: MOVES.RAZOR_LEAF }, { level: 45, move: MOVES.SLAM }],
  70: [{ level: 1, move: MOVES.VINE_WHIP }, { level: 6, move: MOVES.GROWTH }, { level: 11, move: MOVES.WRAP }, { level: 15, move: MOVES.SLEEP_POWDER }, { level: 17, move: MOVES.POISON_POWDER }, { level: 19, move: MOVES.STUN_SPORE }, { level: 24, move: MOVES.ACID }, { level: 42, move: MOVES.RAZOR_LEAF }, { level: 54, move: MOVES.SLAM }],
  71: [{ level: 1, move: MOVES.VINE_WHIP }],
  72: [{ level: 1, move: MOVES.POISON_STING }, { level: 6, move: MOVES.SUPERSONIC }, { level: 12, move: MOVES.CONSTRICT }, { level: 19, move: MOVES.ACID }, { level: 30, move: MOVES.WRAP }, { level: 36, move: MOVES.BARRIER }, { level: 43, move: MOVES.SCREECH }, { level: 49, move: MOVES.HYDRO_PUMP }],
  73: [{ level: 1, move: MOVES.POISON_STING }, { level: 6, move: MOVES.SUPERSONIC }, { level: 12, move: MOVES.CONSTRICT }, { level: 19, move: MOVES.ACID }, { level: 30, move: MOVES.WRAP }, { level: 38, move: MOVES.BARRIER }, { level: 47, move: MOVES.SCREECH }, { level: 55, move: MOVES.HYDRO_PUMP }],
  74: [{ level: 1, move: MOVES.TACKLE }, { level: 11, move: MOVES.ROCK_THROW }, { level: 36, move: MOVES.EARTHQUAKE }, { level: 41, move: MOVES.EXPLOSION }, { level: 46, move: MOVES.DOUBLE_EDGE }],
  75: [{ level: 1, move: MOVES.TACKLE }, { level: 11, move: MOVES.ROCK_THROW }, { level: 45, move: MOVES.EARTHQUAKE }, { level: 53, move: MOVES.EXPLOSION }, { level: 62, move: MOVES.DOUBLE_EDGE }],
  76: [{ level: 1, move: MOVES.TACKLE }, { level: 11, move: MOVES.ROCK_THROW }, { level: 45, move: MOVES.EARTHQUAKE }, { level: 53, move: MOVES.EXPLOSION }, { level: 62, move: MOVES.DOUBLE_EDGE }],
  77: [{ level: 1, move: MOVES.QUICK_ATTACK }, { level: 5, move: MOVES.GROWL }, { level: 9, move: MOVES.TAIL_WHIP }, { level: 14, move: MOVES.EMBER }, { level: 19, move: MOVES.STOMP }, { level: 25, move: MOVES.FIRE_SPIN }, { level: 31, move: MOVES.TAKE_DOWN }, { level: 38, move: MOVES.AGILITY }],
  78: [{ level: 1, move: MOVES.QUICK_ATTACK }, { level: 5, move: MOVES.GROWL }, { level: 9, move: MOVES.TAIL_WHIP }, { level: 14, move: MOVES.EMBER }, { level: 19, move: MOVES.STOMP }, { level: 25, move: MOVES.FIRE_SPIN }, { level: 31, move: MOVES.TAKE_DOWN }, { level: 38, move: MOVES.AGILITY }, { level: 40, move: MOVES.FURY_ATTACK }],
  79: [{ level: 1, move: MOVES.TACKLE }, { level: 6, move: MOVES.GROWL }, { level: 13, move: MOVES.WATER_GUN }, { level: 17, move: MOVES.CONFUSION }, { level: 24, move: MOVES.DISABLE }, { level: 29, move: MOVES.HEADBUTT }, { level: 36, move: MOVES.AMNESIA }],
  80: [{ level: 1, move: MOVES.TACKLE }, { level: 6, move: MOVES.GROWL }, { level: 13, move: MOVES.WATER_GUN }, { level: 17, move: MOVES.CONFUSION }, { level: 24, move: MOVES.DISABLE }, { level: 29, move: MOVES.HEADBUTT }, { level: 36, move: MOVES.AMNESIA }, { level: 37, move: MOVES.WITHDRAW }],
  81: [{ level: 1, move: MOVES.TACKLE }, { level: 11, move: MOVES.SUPERSONIC }, { level: 21, move: MOVES.THUNDER_WAVE }, { level: 38, move: MOVES.SWIFT }, { level: 44, move: MOVES.SCREECH }],
  82: [{ level: 1, move: MOVES.TACKLE }, { level: 11, move: MOVES.SUPERSONIC }, { level: 21, move: MOVES.THUNDER_WAVE }, { level: 44, move: MOVES.TRI_ATTACK }, { level: 53, move: MOVES.SCREECH }],
  83: [{ level: 6, move: MOVES.SAND_ATTACK }, { level: 11, move: MOVES.LEER }, { level: 16, move: MOVES.FURY_ATTACK }, { level: 31, move: MOVES.SWORDS_DANCE }, { level: 36, move: MOVES.AGILITY }, { level: 41, move: MOVES.SLASH }],
  84: [{ level: 1, move: MOVES.GROWL }, { level: 13, move: MOVES.FURY_ATTACK }, { level: 21, move: MOVES.TRI_ATTACK }, { level: 25, move: MOVES.RAGE }, { level: 37, move: MOVES.DRILL_PECK }, { level: 45, move: MOVES.AGILITY }],
  85: [{ level: 1, move: MOVES.GROWL }, { level: 13, move: MOVES.FURY_ATTACK }, { level: 21, move: MOVES.TRI_ATTACK }, { level: 25, move: MOVES.RAGE }, { level: 47, move: MOVES.DRILL_PECK }, { level: 60, move: MOVES.AGILITY }],
  86: [{ level: 1, move: MOVES.HEADBUTT }, { level: 9, move: MOVES.GROWL }, { level: 21, move: MOVES.AURORA_BEAM }, { level: 29, move: MOVES.REST }, { level: 37, move: MOVES.TAKE_DOWN }, { level: 41, move: MOVES.ICE_BEAM }],
  87: [{ level: 1, move: MOVES.HEADBUTT }, { level: 9, move: MOVES.GROWL }, { level: 21, move: MOVES.AURORA_BEAM }, { level: 29, move: MOVES.REST }, { level: 42, move: MOVES.TAKE_DOWN }, { level: 51, move: MOVES.ICE_BEAM }],
  88: [{ level: 1, move: MOVES.POISON_GAS }, { level: 4, move: MOVES.HARDEN }, { level: 8, move: MOVES.DISABLE }, { level: 13, move: MOVES.SLUDGE }, { level: 19, move: MOVES.MINIMIZE }, { level: 26, move: MOVES.SCREECH }, { level: 34, move: MOVES.ACID_ARMOR }],
  89: [{ level: 1, move: MOVES.POISON_GAS }, { level: 4, move: MOVES.HARDEN }, { level: 8, move: MOVES.DISABLE }, { level: 13, move: MOVES.SLUDGE }, { level: 19, move: MOVES.MINIMIZE }, { level: 26, move: MOVES.SCREECH }, { level: 34, move: MOVES.ACID_ARMOR }],
  90: [{ level: 1, move: MOVES.TACKLE }, { level: 15, move: MOVES.SUPERSONIC }, { level: 22, move: MOVES.AURORA_BEAM }, { level: 36, move: MOVES.LEER }, { level: 43, move: MOVES.CLAMP }, { level: 50, move: MOVES.ICE_BEAM }],
  91: [{ level: 1, move: MOVES.WITHDRAW }, { level: 43, move: MOVES.SPIKE_CANNON }],
  92: [{ level: 1, move: MOVES.HYPNOSIS }, { level: 21, move: MOVES.CONFUSE_RAY }, { level: 28, move: MOVES.DREAM_EATER }],
  93: [{ level: 1, move: MOVES.HYPNOSIS }, { level: 21, move: MOVES.CONFUSE_RAY }, { level: 31, move: MOVES.DREAM_EATER }],
  94: [{ level: 1, move: MOVES.HYPNOSIS }, { level: 21, move: MOVES.CONFUSE_RAY }, { level: 31, move: MOVES.DREAM_EATER }],
  95: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.BIND }, { level: 12, move: MOVES.ROCK_THROW }, { level: 19, move: MOVES.HARDEN }, { level: 23, move: MOVES.RAGE }, { level: 41, move: MOVES.SLAM }, { level: 56, move: MOVES.DOUBLE_EDGE }],
  96: [{ level: 1, move: MOVES.POUND }, { level: 7, move: MOVES.DISABLE }, { level: 11, move: MOVES.CONFUSION }, { level: 17, move: MOVES.HEADBUTT }, { level: 21, move: MOVES.POISON_GAS }, { level: 27, move: MOVES.MEDITATE }],
  97: [{ level: 1, move: MOVES.POUND }, { level: 7, move: MOVES.DISABLE }, { level: 11, move: MOVES.CONFUSION }, { level: 17, move: MOVES.HEADBUTT }, { level: 21, move: MOVES.POISON_GAS }, { level: 29, move: MOVES.MEDITATE }],
  98: [{ level: 1, move: MOVES.BUBBLE }, { level: 5, move: MOVES.LEER }, { level: 16, move: MOVES.HARDEN }, { level: 27, move: MOVES.STOMP }, { level: 34, move: MOVES.GUILLOTINE }, { level: 45, move: MOVES.CRABHAMMER }],
  99: [{ level: 1, move: MOVES.BUBBLE }, { level: 5, move: MOVES.LEER }, { level: 16, move: MOVES.HARDEN }, { level: 27, move: MOVES.STOMP }, { level: 38, move: MOVES.GUILLOTINE }, { level: 57, move: MOVES.CRABHAMMER }],
  100: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.SCREECH }, { level: 37, move: MOVES.LIGHT_SCREEN }, { level: 42, move: MOVES.SWIFT }, { level: 46, move: MOVES.EXPLOSION }],
  101: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.SCREECH }, { level: 41, move: MOVES.LIGHT_SCREEN }, { level: 48, move: MOVES.SWIFT }, { level: 54, move: MOVES.EXPLOSION }],
  102: [{ level: 1, move: MOVES.HYPNOSIS }, { level: 7, move: MOVES.REFLECT }, { level: 13, move: MOVES.LEECH_SEED }, { level: 19, move: MOVES.CONFUSION }, { level: 25, move: MOVES.STUN_SPORE }, { level: 31, move: MOVES.POISON_POWDER }, { level: 37, move: MOVES.SLEEP_POWDER }, { level: 43, move: MOVES.SOLAR_BEAM }],
  103: [{ level: 1, move: MOVES.HYPNOSIS }, { level: 19, move: MOVES.STOMP }],
  104: [{ level: 1, move: MOVES.GROWL }, { level: 5, move: MOVES.TAIL_WHIP }, { level: 13, move: MOVES.HEADBUTT }, { level: 17, move: MOVES.LEER }, { level: 21, move: MOVES.FOCUS_ENERGY }, { level: 25, move: MOVES.BONEMERANG }, { level: 29, move: MOVES.RAGE }, { level: 37, move: MOVES.THRASH }, { level: 45, move: MOVES.DOUBLE_EDGE }],
  105: [{ level: 1, move: MOVES.GROWL }, { level: 5, move: MOVES.TAIL_WHIP }, { level: 13, move: MOVES.HEADBUTT }, { level: 17, move: MOVES.LEER }, { level: 21, move: MOVES.FOCUS_ENERGY }, { level: 25, move: MOVES.BONEMERANG }, { level: 32, move: MOVES.RAGE }, { level: 46, move: MOVES.THRASH }, { level: 61, move: MOVES.DOUBLE_EDGE }],
  106: [{ level: 1, move: MOVES.DOUBLE_KICK }, { level: 6, move: MOVES.MEDITATE }, { level: 11, move: MOVES.ROLLING_KICK }, { level: 16, move: MOVES.JUMP_KICK }, { level: 21, move: MOVES.FOCUS_ENERGY }, { level: 26, move: MOVES.HI_JUMP_KICK }, { level: 46, move: MOVES.MEGA_KICK }],
  107: [{ level: 7, move: MOVES.AGILITY }, { level: 26, move: MOVES.ICE_PUNCH }, { level: 38, move: MOVES.MEGA_PUNCH }, { level: 50, move: MOVES.COUNTER }],
  108: [{ level: 1, move: MOVES.LICK }, { level: 7, move: MOVES.SUPERSONIC }, { level: 12, move: MOVES.DEFENSE_CURL }, { level: 23, move: MOVES.STOMP }, { level: 29, move: MOVES.WRAP }, { level: 34, move: MOVES.DISABLE }, { level: 40, move: MOVES.SLAM }, { level: 45, move: MOVES.SCREECH }],
  109: [{ level: 1, move: MOVES.POISON_GAS }, { level: 9, move: MOVES.SMOG }, { level: 21, move: MOVES.SLUDGE }, { level: 25, move: MOVES.SMOKESCREEN }, { level: 33, move: MOVES.HAZE }, { level: 41, move: MOVES.EXPLOSION }],
  110: [{ level: 1, move: MOVES.POISON_GAS }, { level: 9, move: MOVES.SMOG }, { level: 21, move: MOVES.SLUDGE }, { level: 25, move: MOVES.SMOKESCREEN }, { level: 33, move: MOVES.HAZE }, { level: 44, move: MOVES.EXPLOSION }],
  111: [{ level: 1, move: MOVES.HORN_ATTACK }, { level: 10, move: MOVES.STOMP }, { level: 15, move: MOVES.FURY_ATTACK }, { level: 38, move: MOVES.HORN_DRILL }, { level: 43, move: MOVES.TAKE_DOWN }, { level: 52, move: MOVES.EARTHQUAKE }],
  112: [{ level: 1, move: MOVES.HORN_ATTACK }, { level: 10, move: MOVES.STOMP }, { level: 15, move: MOVES.FURY_ATTACK }, { level: 38, move: MOVES.HORN_DRILL }, { level: 46, move: MOVES.TAKE_DOWN }, { level: 58, move: MOVES.EARTHQUAKE }],
  113: [{ level: 1, move: MOVES.POUND }, { level: 5, move: MOVES.TAIL_WHIP }, { level: 23, move: MOVES.MINIMIZE }, { level: 29, move: MOVES.SING }, { level: 41, move: MOVES.DEFENSE_CURL }, { level: 49, move: MOVES.LIGHT_SCREEN }, { level: 57, move: MOVES.DOUBLE_EDGE }],
  114: [{ level: 1, move: MOVES.CONSTRICT }, { level: 4, move: MOVES.SLEEP_POWDER }, { level: 10, move: MOVES.ABSORB }, { level: 13, move: MOVES.GROWTH }, { level: 19, move: MOVES.POISON_POWDER }, { level: 22, move: MOVES.VINE_WHIP }, { level: 28, move: MOVES.BIND }, { level: 37, move: MOVES.STUN_SPORE }, { level: 40, move: MOVES.SLAM }],
  115: [{ level: 1, move: MOVES.LEER }, { level: 7, move: MOVES.BITE }, { level: 13, move: MOVES.TAIL_WHIP }, { level: 25, move: MOVES.MEGA_PUNCH }, { level: 31, move: MOVES.RAGE }, { level: 43, move: MOVES.DIZZY_PUNCH }],
  116: [{ level: 1, move: MOVES.BUBBLE }, { level: 8, move: MOVES.SMOKESCREEN }, { level: 15, move: MOVES.LEER }, { level: 22, move: MOVES.WATER_GUN }, { level: 36, move: MOVES.AGILITY }, { level: 43, move: MOVES.HYDRO_PUMP }],
  117: [{ level: 1, move: MOVES.BUBBLE }, { level: 8, move: MOVES.SMOKESCREEN }, { level: 15, move: MOVES.LEER }, { level: 22, move: MOVES.WATER_GUN }, { level: 40, move: MOVES.AGILITY }, { level: 51, move: MOVES.HYDRO_PUMP }],
  118: [{ level: 1, move: MOVES.TAIL_WHIP }, { level: 10, move: MOVES.SUPERSONIC }, { level: 15, move: MOVES.HORN_ATTACK }, { level: 29, move: MOVES.FURY_ATTACK }, { level: 43, move: MOVES.HORN_DRILL }, { level: 52, move: MOVES.AGILITY }],
  119: [{ level: 1, move: MOVES.TAIL_WHIP }, { level: 10, move: MOVES.SUPERSONIC }, { level: 15, move: MOVES.HORN_ATTACK }, { level: 29, move: MOVES.FURY_ATTACK }, { level: 49, move: MOVES.HORN_DRILL }, { level: 61, move: MOVES.AGILITY }],
  120: [{ level: 1, move: MOVES.TACKLE }, { level: 6, move: MOVES.WATER_GUN }, { level: 15, move: MOVES.RECOVER }, { level: 24, move: MOVES.SWIFT }, { level: 33, move: MOVES.MINIMIZE }, { level: 37, move: MOVES.LIGHT_SCREEN }, { level: 46, move: MOVES.HYDRO_PUMP }],
  121: [{ level: 1, move: MOVES.WATER_GUN }, { level: 33, move: MOVES.CONFUSE_RAY }],
  122: [{ level: 1, move: MOVES.BARRIER }, { level: 5, move: MOVES.CONFUSION }, { level: 12, move: MOVES.MEDITATE }, { level: 19, move: MOVES.LIGHT_SCREEN }, { level: 29, move: MOVES.PSYBEAM }],
  123: [{ level: 1, move: MOVES.QUICK_ATTACK }, { level: 6, move: MOVES.FOCUS_ENERGY }, { level: 21, move: MOVES.AGILITY }, { level: 26, move: MOVES.WING_ATTACK }, { level: 31, move: MOVES.SLASH }, { level: 36, move: MOVES.SWORDS_DANCE }, { level: 41, move: MOVES.DOUBLE_TEAM }],
  124: [{ level: 1, move: MOVES.POUND }, { level: 25, move: MOVES.ICE_PUNCH }, { level: 51, move: MOVES.BODY_SLAM }, { level: 67, move: MOVES.BLIZZARD }],
  125: [{ level: 1, move: MOVES.QUICK_ATTACK }, { level: 17, move: MOVES.LIGHT_SCREEN }, { level: 25, move: MOVES.SWIFT }, { level: 36, move: MOVES.SCREECH }, { level: 58, move: MOVES.THUNDER }],
  126: [{ level: 1, move: MOVES.EMBER }, { level: 7, move: MOVES.LEER }, { level: 13, move: MOVES.SMOG }, { level: 19, move: MOVES.FIRE_PUNCH }, { level: 25, move: MOVES.SMOKESCREEN }, { level: 41, move: MOVES.FLAMETHROWER }, { level: 49, move: MOVES.CONFUSE_RAY }],
  127: [{ level: 1, move: MOVES.FOCUS_ENERGY }, { level: 7, move: MOVES.BIND }, { level: 13, move: MOVES.SEISMIC_TOSS }, { level: 19, move: MOVES.HARDEN }, { level: 37, move: MOVES.GUILLOTINE }, { level: 43, move: MOVES.SUBMISSION }, { level: 49, move: MOVES.SWORDS_DANCE }],
  128: [{ level: 1, move: MOVES.TACKLE }, { level: 4, move: MOVES.RAGE }, { level: 8, move: MOVES.HORN_ATTACK }, { level: 34, move: MOVES.REST }, { level: 43, move: MOVES.THRASH }, { level: 53, move: MOVES.TAKE_DOWN }],
  129: [{ level: 15, move: MOVES.TACKLE }],
  130: [{ level: 1, move: MOVES.THRASH }, { level: 20, move: MOVES.BITE }, { level: 25, move: MOVES.DRAGON_RAGE }, { level: 30, move: MOVES.LEER }, { level: 40, move: MOVES.HYDRO_PUMP }, { level: 55, move: MOVES.HYPER_BEAM }],
  131: [{ level: 1, move: MOVES.WATER_GUN }, { level: 7, move: MOVES.MIST }, { level: 13, move: MOVES.BODY_SLAM }, { level: 19, move: MOVES.CONFUSE_RAY }, { level: 31, move: MOVES.ICE_BEAM }, { level: 49, move: MOVES.HYDRO_PUMP }],
  132: [{ level: 1, move: MOVES.TRANSFORM }],
  133: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.SAND_ATTACK }, { level: 16, move: MOVES.GROWL }, { level: 23, move: MOVES.QUICK_ATTACK }, { level: 30, move: MOVES.BITE }, { level: 42, move: MOVES.TAKE_DOWN }],
  134: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.SAND_ATTACK }, { level: 16, move: MOVES.WATER_GUN }, { level: 23, move: MOVES.QUICK_ATTACK }, { level: 30, move: MOVES.BITE }, { level: 36, move: MOVES.AURORA_BEAM }, { level: 42, move: MOVES.HAZE }, { level: 47, move: MOVES.ACID_ARMOR }, { level: 52, move: MOVES.HYDRO_PUMP }],
  135: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.SAND_ATTACK }, { level: 23, move: MOVES.QUICK_ATTACK }, { level: 30, move: MOVES.DOUBLE_KICK }, { level: 36, move: MOVES.PIN_MISSILE }, { level: 42, move: MOVES.THUNDER_WAVE }, { level: 47, move: MOVES.AGILITY }, { level: 52, move: MOVES.THUNDER }],
  136: [{ level: 1, move: MOVES.TACKLE }, { level: 8, move: MOVES.SAND_ATTACK }, { level: 16, move: MOVES.EMBER }, { level: 23, move: MOVES.QUICK_ATTACK }, { level: 30, move: MOVES.BITE }, { level: 36, move: MOVES.FIRE_SPIN }, { level: 42, move: MOVES.SMOG }, { level: 47, move: MOVES.LEER }, { level: 52, move: MOVES.FLAMETHROWER }],
  137: [{ level: 1, move: MOVES.TACKLE }, { level: 9, move: MOVES.AGILITY }, { level: 12, move: MOVES.PSYBEAM }, { level: 20, move: MOVES.RECOVER }, { level: 36, move: MOVES.TRI_ATTACK }],
  138: [{ level: 1, move: MOVES.CONSTRICT }, { level: 13, move: MOVES.BITE }, { level: 19, move: MOVES.WATER_GUN }, { level: 31, move: MOVES.LEER }, { level: 55, move: MOVES.HYDRO_PUMP }],
  139: [{ level: 1, move: MOVES.CONSTRICT }, { level: 13, move: MOVES.BITE }, { level: 19, move: MOVES.WATER_GUN }, { level: 31, move: MOVES.LEER }, { level: 40, move: MOVES.SPIKE_CANNON }, { level: 65, move: MOVES.HYDRO_PUMP }],
  140: [{ level: 1, move: MOVES.SCRATCH }, { level: 13, move: MOVES.ABSORB }, { level: 19, move: MOVES.LEER }, { level: 31, move: MOVES.SAND_ATTACK }],
  141: [{ level: 1, move: MOVES.SCRATCH }, { level: 13, move: MOVES.ABSORB }, { level: 19, move: MOVES.LEER }, { level: 31, move: MOVES.SAND_ATTACK }, { level: 40, move: MOVES.SLASH }],
  142: [{ level: 1, move: MOVES.WING_ATTACK }, { level: 8, move: MOVES.AGILITY }, { level: 15, move: MOVES.BITE }, { level: 22, move: MOVES.SUPERSONIC }, { level: 43, move: MOVES.TAKE_DOWN }, { level: 50, move: MOVES.HYPER_BEAM }],
  143: [{ level: 1, move: MOVES.TACKLE }, { level: 5, move: MOVES.AMNESIA }, { level: 9, move: MOVES.DEFENSE_CURL }, { level: 17, move: MOVES.HEADBUTT }, { level: 25, move: MOVES.REST }, { level: 33, move: MOVES.BODY_SLAM }, { level: 53, move: MOVES.HYPER_BEAM }],
  144: [{ level: 13, move: MOVES.MIST }, { level: 25, move: MOVES.AGILITY }, { level: 49, move: MOVES.ICE_BEAM }, { level: 61, move: MOVES.REFLECT }, { level: 73, move: MOVES.BLIZZARD }],
  145: [{ level: 13, move: MOVES.THUNDER_WAVE }, { level: 25, move: MOVES.AGILITY }, { level: 49, move: MOVES.DRILL_PECK }, { level: 73, move: MOVES.LIGHT_SCREEN }, { level: 85, move: MOVES.THUNDER }],
  146: [{ level: 1, move: MOVES.WING_ATTACK }, { level: 13, move: MOVES.FIRE_SPIN }, { level: 25, move: MOVES.AGILITY }, { level: 49, move: MOVES.FLAMETHROWER }, { level: 85, move: MOVES.SKY_ATTACK }],
  147: [{ level: 1, move: MOVES.WRAP }, { level: 8, move: MOVES.THUNDER_WAVE }, { level: 22, move: MOVES.DRAGON_RAGE }, { level: 29, move: MOVES.SLAM }, { level: 36, move: MOVES.AGILITY }, { level: 57, move: MOVES.HYPER_BEAM }],
  148: [{ level: 1, move: MOVES.WRAP }, { level: 8, move: MOVES.THUNDER_WAVE }, { level: 22, move: MOVES.DRAGON_RAGE }, { level: 29, move: MOVES.SLAM }, { level: 38, move: MOVES.AGILITY }, { level: 65, move: MOVES.HYPER_BEAM }],
  149: [{ level: 1, move: MOVES.WRAP }, { level: 8, move: MOVES.THUNDER_WAVE }, { level: 22, move: MOVES.DRAGON_RAGE }, { level: 29, move: MOVES.SLAM }, { level: 38, move: MOVES.AGILITY }, { level: 55, move: MOVES.WING_ATTACK }, { level: 75, move: MOVES.HYPER_BEAM }],
  150: [{ level: 1, move: MOVES.CONFUSION }, { level: 11, move: MOVES.BARRIER }, { level: 22, move: MOVES.MIST }, { level: 33, move: MOVES.SWIFT }, { level: 44, move: MOVES.RECOVER }, { level: 99, move: MOVES.AMNESIA }],
  151: [{ level: 1, move: MOVES.POUND }, { level: 10, move: MOVES.TRANSFORM }, { level: 20, move: MOVES.MEGA_PUNCH }, { level: 30, move: MOVES.METRONOME }],
};
/** Used automatically when all moves have 0 PP. Typeless, 50 power, 1/4 recoil. */
export const STRUGGLE_MOVE: Move = {
  name: 'Forcejeo', type: 'normal', power: 50, accuracy: 100,
  pp: Infinity, maxPp: Infinity, sfxType: 'noise',
};
