import { type Pokemon } from '../types';
import { MOVES } from './moves';
import { makePokemon } from './pokemon';

/** Gen I encounter rate per map (0–255). Roll 0–255; if roll < rate, battle starts. */
export const WILD_ENCOUNTER_RATES: Record<string, number> = {
  KANTO_OVERWORLD: 10,   // fallback; per-zone rates applied in tryWildEncounter
  ROUTE_1: 10,
  ROUTE_2: 10,
  VIRIDIAN_FOREST: 16,
  ROUTE_3: 10,
  MT_MOON: 8,
  MT_MOON_B1F: 8,
  MT_MOON_B2F: 8,
  ROUTE_4: 10,
  ROUTE_5: 10,
  ROUTE_6: 10,
  ROUTE_9: 10,
  ROUTE_10: 10,
  ROCK_TUNNEL_1F: 15,
  POKEMON_TOWER_3F: 10,
  ROUTE_7: 15,
  ROUTE_8: 15,
  ROUTE_11: 15,
  ROUTE_12: 15,
  ROUTE_13: 20,
  ROUTE_14: 15,
  ROUTE_15: 15,
  ROUTE_16: 25,
  ROUTE_17: 25,
  ROUTE_18: 25,
  ROUTE_21: 25,
  ROUTE_22: 25,
  ROUTE_24: 25,
  ROUTE_25: 15,
  VICTORY_ROAD_1F: 15,
  VICTORY_ROAD_2F: 10,
  VICTORY_ROAD_3F: 15,
  SEAFOAM_ISLANDS_1F: 15,
  POKEMON_MANSION_1F: 10,
  POKEMON_MANSION_2F: 10,
  POKEMON_MANSION_3F: 10,
  CERULEAN_CAVE_1F: 10,
  CERULEAN_CAVE_2F: 15,
  CERULEAN_CAVE_B_1F: 25,
  DIGLETTS_CAVE: 20,
  POWER_PLANT: 10,
  POKEMON_TOWER_4F: 10,
  POKEMON_TOWER_5F: 10,
  POKEMON_TOWER_6F: 15,
  POKEMON_TOWER_7F: 15,
  SAFARI_ZONE_CENTER: 30,
  SAFARI_ZONE_EAST: 30,
  SAFARI_ZONE_NORTH: 30,
  SAFARI_ZONE_WEST: 30,
};
/**
 * Offsets of each outdoor zone inside KANTO_OVERWORLD — auto-generated from
 * pokefirered's connection graph by scripts/stitch-firered-overworld.mjs.
 * Used to map an absolute (x,y) back to the legacy zone name so per-zone
 * encounter tables and minimap still work.
 */
import { KANTO_FIRERED_ZONE_OFFSETS } from '../data/firered/kantoZoneOffsets.generated';
const KANTO_ZONE_OFFSETS: Record<string, { x: number; y: number; w: number; h: number }> = {
  ...KANTO_FIRERED_ZONE_OFFSETS,
};
/** Given an absolute (x,y) in KANTO_OVERWORLD, return the legacy zone name. */
export function getKantoRegion(x: number, y: number): string {
  for (const [zone, r] of Object.entries(KANTO_ZONE_OFFSETS)) {
    if (x >= r.x && x < r.x + r.w && y >= r.y && y < r.y + r.h) return zone;
  }
  return 'ROUTE_1'; // fallback
}
export const WILD_POKEMON_DATABASE: Record<string, Pokemon[]> = {
  ROUTE_1: [
    makePokemon('pidgey', 'PIDGEY', 4, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('rattata', 'RATTATA', 4, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('caterpie', 'CATERPIE', 3, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('weedle', 'WEEDLE', 3, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
    makePokemon('spearow', 'SPEAROW', 5, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('mankey', 'MANKEY', 5, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('pikachu', 'PIKACHU', 6, 'electric', [MOVES.THUNDERSHOCK, MOVES.GROWL], 25),
  ],
  ROUTE_2: [
    makePokemon('pidgey', 'PIDGEY', 7, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('rattata', 'RATTATA', 7, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('nidoran-f', 'NIDORAN_F', 7, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
    makePokemon('nidoran-m', 'NIDORAN_M', 7, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('caterpie', 'CATERPIE', 6, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('weedle', 'WEEDLE', 6, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
  ],
  VIRIDIAN_FOREST: [
    makePokemon('caterpie', 'CATERPIE', 4, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('weedle', 'WEEDLE', 4, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
    makePokemon('metapod', 'METAPOD', 6, 'bug', [MOVES.HARDEN], 11),
    makePokemon('pikachu', 'PIKACHU', 6, 'electric', [MOVES.THUNDERSHOCK, MOVES.GROWL], 25),
  ],
  ROUTE_3: [
    makePokemon('spearow', 'SPEAROW', 9, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('jigglypuff', 'JIGGLYPUFF', 9, 'normal', [MOVES.POUND, MOVES.GROWL], 39),
    makePokemon('mankey', 'MANKEY', 10, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('nidoran-m', 'NIDORAN_M', 9, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('nidoran-f', 'NIDORAN_F', 9, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
  ],
  MT_MOON: [
    makePokemon('zubat', 'ZUBAT', 8, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('geodude', 'GEODUDE', 8, 'rock', [MOVES.TACKLE], 74, { types: ['rock', 'ground'] }),
    makePokemon('paras', 'PARAS', 9, 'bug', [MOVES.SCRATCH], 59, { types: ['bug', 'grass'] }),
    makePokemon('clefairy', 'CLEFAIRY', 8, 'normal', [MOVES.POUND, MOVES.GROWL], 68),
  ],
  MT_MOON_B1F: [
    makePokemon('zubat', 'ZUBAT', 9, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('geodude', 'GEODUDE', 10, 'rock', [MOVES.TACKLE], 74, { types: ['rock', 'ground'] }),
    makePokemon('paras', 'PARAS', 10, 'bug', [MOVES.SCRATCH], 59, { types: ['bug', 'grass'] }),
  ],
  MT_MOON_B2F: [
    makePokemon('zubat', 'ZUBAT', 10, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('geodude', 'GEODUDE', 11, 'rock', [MOVES.TACKLE], 74, { types: ['rock', 'ground'] }),
    makePokemon('paras', 'PARAS', 11, 'bug', [MOVES.SCRATCH], 59, { types: ['bug', 'grass'] }),
    makePokemon('clefairy', 'CLEFAIRY', 10, 'normal', [MOVES.POUND, MOVES.GROWL], 68),
  ],
  ROUTE_4: [
    makePokemon('spearow', 'SPEAROW', 10, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('rattata', 'RATTATA', 10, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('sandshrew', 'SANDSHREW', 11, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 60),
    makePokemon('ekans', 'EKANS', 10, 'poison', [MOVES.TACKLE, MOVES.GROWL], 62),
  ],
  ROUTE_5: [
    makePokemon('pidgey', 'PIDGEY', 13, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('oddish', 'ODDISH', 13, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('mankey', 'MANKEY', 13, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('meowth', 'MEOWTH', 13, 'normal', [MOVES.SCRATCH, MOVES.GROWL], 69),
  ],
  ROUTE_6: [
    makePokemon('pidgey', 'PIDGEY', 14, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('oddish', 'ODDISH', 14, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('mankey', 'MANKEY', 14, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('meowth', 'MEOWTH', 14, 'normal', [MOVES.SCRATCH, MOVES.GROWL], 69),
  ],
  ROUTE_9: [
    makePokemon('rattata', 'RATTATA', 16, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('spearow', 'SPEAROW', 14, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('ekans', 'EKANS', 15, 'poison', [MOVES.TACKLE, MOVES.GROWL], 62),
    makePokemon('sandshrew', 'SANDSHREW', 15, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 60),
  ],
  ROUTE_10: [
    makePokemon('rattata', 'RATTATA', 17, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('spearow', 'SPEAROW', 16, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('voltorb', 'VOLTORB', 17, 'electric', [MOVES.TACKLE, MOVES.THUNDERSHOCK], 100, { types: ['electric'] }),
    makePokemon('ekans', 'EKANS', 17, 'poison', [MOVES.TACKLE, MOVES.GROWL], 62),
  ],
  ROCK_TUNNEL_1F: [
    makePokemon('zubat', 'ZUBAT', 15, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('geodude', 'GEODUDE', 16, 'rock', [MOVES.TACKLE], 74, { types: ['rock', 'ground'] }),
    makePokemon('machop', 'MACHOP', 15, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 61),
    makePokemon('onix', 'ONIX', 17, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 95, { types: ['rock', 'ground'] }),
  ],
  POKEMON_TOWER_3F: [
    makePokemon('gastly', 'GASTLY', 20, 'ghost', [MOVES.TACKLE, MOVES.LICK], 92, { types: ['ghost', 'poison'] }),
    makePokemon('cubone', 'CUBONE', 20, 'ground', [MOVES.TACKLE, MOVES.GROWL], 104),
    makePokemon('haunter', 'HAUNTER', 25, 'ghost', [MOVES.TACKLE, MOVES.LICK], 93, { types: ['ghost', 'poison'] }),
  ],
  ROUTE_7: [
    makePokemon('pidgey', 'PIDGEY', 19, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('oddish', 'ODDISH', 19, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('mankey', 'MANKEY', 17, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('growlithe', 'GROWLITHE', 18, 'fire', [MOVES.EMBER, MOVES.TACKLE], 58, { types: ['fire'] }),
    makePokemon('bellsprout', 'BELLSPROUT', 19, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
    makePokemon('meowth', 'MEOWTH', 17, 'normal', [MOVES.SCRATCH, MOVES.GROWL], 52),
    makePokemon('vulpix', 'VULPIX', 18, 'fire', [MOVES.EMBER, MOVES.TACKLE], 37, { types: ['fire'] }),
  ],
  ROUTE_8: [
    makePokemon('pidgey', 'PIDGEY', 18, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('mankey', 'MANKEY', 18, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('ekans', 'EKANS', 17, 'poison', [MOVES.TACKLE, MOVES.GROWL], 23, { types: ['poison'] }),
    makePokemon('growlithe', 'GROWLITHE', 15, 'fire', [MOVES.EMBER, MOVES.TACKLE], 58, { types: ['fire'] }),
    makePokemon('meowth', 'MEOWTH', 18, 'normal', [MOVES.SCRATCH, MOVES.GROWL], 52),
    makePokemon('sandshrew', 'SANDSHREW', 17, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 27),
    makePokemon('vulpix', 'VULPIX', 15, 'fire', [MOVES.EMBER, MOVES.TACKLE], 37, { types: ['fire'] }),
  ],
  ROUTE_11: [
    makePokemon('ekans', 'EKANS', 12, 'poison', [MOVES.TACKLE, MOVES.GROWL], 23, { types: ['poison'] }),
    makePokemon('spearow', 'SPEAROW', 13, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('drowzee', 'DROWZEE', 9, 'psychic', [MOVES.POUND, MOVES.GROWL], 96, { types: ['psychic'] }),
    makePokemon('sandshrew', 'SANDSHREW', 12, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 27),
  ],
  ROUTE_12: [
    makePokemon('oddish', 'ODDISH', 22, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('pidgey', 'PIDGEY', 23, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('venonat', 'VENONAT', 24, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 48, { types: ['bug', 'poison'] }),
    makePokemon('gloom', 'GLOOM', 28, 'grass', [MOVES.POUND, MOVES.POISON_POWDER], 44, { types: ['grass', 'poison'] }),
    makePokemon('bellsprout', 'BELLSPROUT', 22, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
    makePokemon('weepinbell', 'WEEPINBELL', 28, 'grass', [MOVES.VINE_WHIP, MOVES.SLEEP_POWDER], 70, { types: ['grass', 'poison'] }),
  ],
  ROUTE_13: [
    makePokemon('oddish', 'ODDISH', 22, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('pidgey', 'PIDGEY', 25, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('venonat', 'VENONAT', 24, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 48, { types: ['bug', 'poison'] }),
    makePokemon('ditto', 'DITTO', 25, 'normal', [MOVES.TACKLE], 132),
    makePokemon('gloom', 'GLOOM', 28, 'grass', [MOVES.POUND, MOVES.POISON_POWDER], 44, { types: ['grass', 'poison'] }),
    makePokemon('bellsprout', 'BELLSPROUT', 22, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
    makePokemon('weepinbell', 'WEEPINBELL', 28, 'grass', [MOVES.VINE_WHIP, MOVES.SLEEP_POWDER], 70, { types: ['grass', 'poison'] }),
  ],
  ROUTE_14: [
    makePokemon('oddish', 'ODDISH', 22, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('pidgey', 'PIDGEY', 26, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('ditto', 'DITTO', 23, 'normal', [MOVES.TACKLE], 132),
    makePokemon('venonat', 'VENONAT', 24, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 48, { types: ['bug', 'poison'] }),
    makePokemon('gloom', 'GLOOM', 30, 'grass', [MOVES.POUND, MOVES.POISON_POWDER], 44, { types: ['grass', 'poison'] }),
    makePokemon('bellsprout', 'BELLSPROUT', 22, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
    makePokemon('weepinbell', 'WEEPINBELL', 30, 'grass', [MOVES.VINE_WHIP, MOVES.SLEEP_POWDER], 70, { types: ['grass', 'poison'] }),
    makePokemon('pidgeotto', 'PIDGEOTTO', 28, 'flying', [MOVES.TACKLE, MOVES.GUST], 17, { types: ['normal', 'flying'] }),
  ],
  ROUTE_15: [
    makePokemon('oddish', 'ODDISH', 22, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('ditto', 'DITTO', 26, 'normal', [MOVES.TACKLE], 132),
    makePokemon('pidgey', 'PIDGEY', 23, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('venonat', 'VENONAT', 26, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 48, { types: ['bug', 'poison'] }),
    makePokemon('gloom', 'GLOOM', 30, 'grass', [MOVES.POUND, MOVES.POISON_POWDER], 44, { types: ['grass', 'poison'] }),
    makePokemon('bellsprout', 'BELLSPROUT', 22, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
    makePokemon('weepinbell', 'WEEPINBELL', 30, 'grass', [MOVES.VINE_WHIP, MOVES.SLEEP_POWDER], 70, { types: ['grass', 'poison'] }),
    makePokemon('pidgeotto', 'PIDGEOTTO', 28, 'flying', [MOVES.TACKLE, MOVES.GUST], 17, { types: ['normal', 'flying'] }),
  ],
  ROUTE_16: [
    makePokemon('spearow', 'SPEAROW', 20, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('rattata', 'RATTATA', 18, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('doduo', 'DODUO', 18, 'flying', [MOVES.PECK, MOVES.GROWL], 84, { types: ['normal', 'flying'] }),
    makePokemon('raticate', 'RATICATE', 23, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 20),
  ],
  ROUTE_17: [
    makePokemon('spearow', 'SPEAROW', 20, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('raticate', 'RATICATE', 25, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 20),
    makePokemon('doduo', 'DODUO', 24, 'flying', [MOVES.PECK, MOVES.GROWL], 84, { types: ['normal', 'flying'] }),
    makePokemon('fearow', 'FEAROW', 25, 'flying', [MOVES.PECK, MOVES.GROWL], 22, { types: ['normal', 'flying'] }),
  ],
  ROUTE_18: [
    makePokemon('spearow', 'SPEAROW', 20, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('raticate', 'RATICATE', 25, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 20),
    makePokemon('doduo', 'DODUO', 24, 'flying', [MOVES.PECK, MOVES.GROWL], 84, { types: ['normal', 'flying'] }),
    makePokemon('fearow', 'FEAROW', 25, 'flying', [MOVES.PECK, MOVES.GROWL], 22, { types: ['normal', 'flying'] }),
  ],
  ROUTE_21: [
    makePokemon('rattata', 'RATTATA', 21, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('pidgey', 'PIDGEY', 21, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('raticate', 'RATICATE', 30, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 20),
    makePokemon('pidgeotto', 'PIDGEOTTO', 30, 'flying', [MOVES.TACKLE, MOVES.GUST], 17, { types: ['normal', 'flying'] }),
    makePokemon('tangela', 'TANGELA', 28, 'grass', [MOVES.VINE_WHIP, MOVES.SLEEP_POWDER], 114),
    makePokemon('tentacool', 'TENTACOOL', 15, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 72, { types: ['water', 'poison'] }),
  ],
  ROUTE_22: [
    makePokemon('rattata', 'RATTATA', 2, 'normal', [MOVES.TACKLE], 19),
    makePokemon('nidoran-m', 'NIDORAN_M', 2, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('spearow', 'SPEAROW', 3, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('nidoran-f', 'NIDORAN_F', 2, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
  ],
  ROUTE_24: [
    makePokemon('weedle', 'WEEDLE', 7, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
    makePokemon('kakuna', 'KAKUNA', 8, 'bug', [MOVES.HARDEN], 14, { types: ['bug', 'poison'] }),
    makePokemon('pidgey', 'PIDGEY', 12, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('oddish', 'ODDISH', 12, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('abra', 'ABRA', 8, 'psychic', [MOVES.POUND], 63, { types: ['psychic'] }),
    makePokemon('caterpie', 'CATERPIE', 7, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('metapod', 'METAPOD', 8, 'bug', [MOVES.HARDEN], 11),
    makePokemon('bellsprout', 'BELLSPROUT', 12, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
  ],
  ROUTE_25: [
    makePokemon('weedle', 'WEEDLE', 8, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
    makePokemon('kakuna', 'KAKUNA', 7, 'bug', [MOVES.HARDEN], 14, { types: ['bug', 'poison'] }),
    makePokemon('pidgey', 'PIDGEY', 13, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('oddish', 'ODDISH', 12, 'grass', [MOVES.POUND, MOVES.SLEEP_POWDER], 43, { types: ['grass', 'poison'] }),
    makePokemon('abra', 'ABRA', 10, 'psychic', [MOVES.POUND], 63, { types: ['psychic'] }),
    makePokemon('metapod', 'METAPOD', 7, 'bug', [MOVES.HARDEN], 11),
    makePokemon('caterpie', 'CATERPIE', 8, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('bellsprout', 'BELLSPROUT', 12, 'grass', [MOVES.VINE_WHIP, MOVES.GROWL], 69, { types: ['grass', 'poison'] }),
  ],
  // ── Dungeons ──
  VICTORY_ROAD_1F: [
    makePokemon('machop', 'MACHOP', 24, 'fighting', [MOVES.SCRATCH], 66),
    makePokemon('geodude', 'GEODUDE', 26, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 74, { types: ['rock', 'ground'] }),
    makePokemon('zubat', 'ZUBAT', 22, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('onix', 'ONIX', 39, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 95, { types: ['rock', 'ground'] }),
    makePokemon('graveler', 'GRAVELER', 41, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 75, { types: ['rock', 'ground'] }),
    makePokemon('golbat', 'GOLBAT', 41, 'poison', [MOVES.TACKLE, MOVES.LICK], 42, { types: ['poison', 'flying'] }),
    makePokemon('machoke', 'MACHOKE', 42, 'fighting', [MOVES.SCRATCH], 67),
    makePokemon('marowak', 'MAROWAK', 43, 'ground', [MOVES.TACKLE], 105),
  ],
  VICTORY_ROAD_2F: [
    makePokemon('machop', 'MACHOP', 22, 'fighting', [MOVES.SCRATCH], 66),
    makePokemon('geodude', 'GEODUDE', 24, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 74, { types: ['rock', 'ground'] }),
    makePokemon('zubat', 'ZUBAT', 22, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('onix', 'ONIX', 39, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 95, { types: ['rock', 'ground'] }),
    makePokemon('machoke', 'MACHOKE', 41, 'fighting', [MOVES.SCRATCH], 67),
    makePokemon('golbat', 'GOLBAT', 40, 'poison', [MOVES.TACKLE, MOVES.LICK], 42, { types: ['poison', 'flying'] }),
    makePokemon('marowak', 'MAROWAK', 40, 'ground', [MOVES.TACKLE], 105),
    makePokemon('graveler', 'GRAVELER', 43, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 75, { types: ['rock', 'ground'] }),
  ],
  VICTORY_ROAD_3F: [
    makePokemon('machop', 'MACHOP', 24, 'fighting', [MOVES.SCRATCH], 66),
    makePokemon('geodude', 'GEODUDE', 26, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 74, { types: ['rock', 'ground'] }),
    makePokemon('zubat', 'ZUBAT', 22, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('onix', 'ONIX', 42, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 95, { types: ['rock', 'ground'] }),
    makePokemon('venomoth', 'VENOMOTH', 40, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 49, { types: ['bug', 'poison'] }),
    makePokemon('graveler', 'GRAVELER', 43, 'rock', [MOVES.TACKLE, MOVES.ROCK_THROW], 75, { types: ['rock', 'ground'] }),
    makePokemon('golbat', 'GOLBAT', 41, 'poison', [MOVES.TACKLE, MOVES.LICK], 42, { types: ['poison', 'flying'] }),
    makePokemon('machoke', 'MACHOKE', 42, 'fighting', [MOVES.SCRATCH], 67),
  ],
  SEAFOAM_ISLANDS_1F: [
    makePokemon('seel', 'SEEL', 30, 'water', [MOVES.WATER_GUN], 86, { types: ['water'] }),
    makePokemon('slowpoke', 'SLOWPOKE', 30, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 79, { types: ['water', 'psychic'] }),
    makePokemon('shellder', 'SHELLDER', 30, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 90, { types: ['water'] }),
    makePokemon('horsea', 'HORSEA', 29, 'water', [MOVES.WATER_GUN], 116, { types: ['water'] }),
    makePokemon('zubat', 'ZUBAT', 21, 'poison', [MOVES.TACKLE], 41, { types: ['poison', 'flying'] }),
    makePokemon('golbat', 'GOLBAT', 29, 'poison', [MOVES.TACKLE, MOVES.LICK], 42, { types: ['poison', 'flying'] }),
    makePokemon('psyduck', 'PSYDUCK', 28, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 54, { types: ['water'] }),
    makePokemon('golduck', 'GOLDUCK', 38, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 55, { types: ['water'] }),
    makePokemon('staryu', 'STARYU', 28, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 120, { types: ['water'] }),
    makePokemon('krabby', 'KRABBY', 28, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 98, { types: ['water'] }),
    makePokemon('slowbro', 'SLOWBRO', 38, 'water', [MOVES.TACKLE, MOVES.WATER_GUN], 80, { types: ['water', 'psychic'] }),
  ],
  POKEMON_MANSION_1F: [
    makePokemon('koffing', 'KOFFING', 32, 'poison', [MOVES.TACKLE, MOVES.POISON_POWDER], 109, { types: ['poison'] }),
    makePokemon('ponyta', 'PONYTA', 34, 'fire', [MOVES.EMBER, MOVES.TACKLE], 77, { types: ['fire'] }),
    makePokemon('growlithe', 'GROWLITHE', 34, 'fire', [MOVES.EMBER, MOVES.TACKLE], 58, { types: ['fire'] }),
    makePokemon('grimer', 'GRIMER', 30, 'poison', [MOVES.POUND, MOVES.POISON_POWDER], 88, { types: ['poison'] }),
    makePokemon('weezing', 'WEEZING', 37, 'poison', [MOVES.TACKLE, MOVES.POISON_POWDER], 110, { types: ['poison'] }),
    makePokemon('muk', 'MUK', 39, 'poison', [MOVES.POUND, MOVES.POISON_POWDER], 89, { types: ['poison'] }),
    makePokemon('vulpix', 'VULPIX', 34, 'fire', [MOVES.EMBER, MOVES.TACKLE], 37, { types: ['fire'] }),
  ],
  POKEMON_MANSION_2F: [
    makePokemon('growlithe', 'GROWLITHE', 32, 'fire', [MOVES.EMBER, MOVES.TACKLE], 58, { types: ['fire'] }),
    makePokemon('koffing', 'KOFFING', 30, 'poison', [MOVES.TACKLE, MOVES.POISON_POWDER], 109, { types: ['poison'] }),
    makePokemon('ponyta', 'PONYTA', 28, 'fire', [MOVES.EMBER, MOVES.TACKLE], 77, { types: ['fire'] }),
    makePokemon('grimer', 'GRIMER', 30, 'poison', [MOVES.POUND, MOVES.POISON_POWDER], 88, { types: ['poison'] }),
    makePokemon('weezing', 'WEEZING', 37, 'poison', [MOVES.TACKLE, MOVES.POISON_POWDER], 110, { types: ['poison'] }),
    makePokemon('muk', 'MUK', 37, 'poison', [MOVES.POUND, MOVES.POISON_POWDER], 89, { types: ['poison'] }),
    makePokemon('vulpix', 'VULPIX', 32, 'fire', [MOVES.EMBER, MOVES.TACKLE], 37, { types: ['fire'] }),
  ],
  POKEMON_MANSION_3F: [
    makePokemon('koffing', 'KOFFING', 33, 'poison', [MOVES.TACKLE, MOVES.POISON_POWDER], 109, { types: ['poison'] }),
    makePokemon('growlithe', 'GROWLITHE', 33, 'fire', [MOVES.EMBER, MOVES.TACKLE], 58, { types: ['fire'] }),
    makePokemon('ponyta', 'PONYTA', 36, 'fire', [MOVES.EMBER, MOVES.TACKLE], 77, { types: ['fire'] }),
    makePokemon('weezing', 'WEEZING', 38, 'poison', [MOVES.TACKLE, MOVES.POISON_POWDER], 110, { types: ['poison'] }),
    makePokemon('grimer', 'GRIMER', 31, 'poison', [MOVES.POUND, MOVES.POISON_POWDER], 88, { types: ['poison'] }),
    makePokemon('muk', 'MUK', 38, 'poison', [MOVES.POUND, MOVES.POISON_POWDER], 89, { types: ['poison'] }),
    makePokemon('vulpix', 'VULPIX', 33, 'fire', [MOVES.EMBER, MOVES.TACKLE], 37, { types: ['fire'] }),
    makePokemon('magmar', 'MAGMAR', 34, 'fire', [MOVES.EMBER, MOVES.TACKLE], 126, { types: ['fire'] }),
  ],
  CERULEAN_CAVE_1F: [
    makePokemon('golbat', 'GOLBAT', 46, 'poison', [MOVES.TACKLE, MOVES.LICK], 42, { types: ['poison', 'flying'] }),
    makePokemon('hypno', 'HYPNO', 46, 'psychic', [MOVES.POUND], 97, { types: ['psychic'] }),
    makePokemon('magneton', 'MAGNETON', 46, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 82, { types: ['electric'] }),
    makePokemon('dodrio', 'DODRIO', 49, 'flying', [MOVES.PECK, MOVES.GROWL], 85, { types: ['normal', 'flying'] }),
    makePokemon('venomoth', 'VENOMOTH', 49, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 49, { types: ['bug', 'poison'] }),
    makePokemon('arbok', 'ARBOK', 52, 'poison', [MOVES.TACKLE, MOVES.GROWL], 24, { types: ['poison'] }),
    makePokemon('sandslash', 'SANDSLASH', 52, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 28),
    makePokemon('kadabra', 'KADABRA', 49, 'psychic', [MOVES.POUND], 64, { types: ['psychic'] }),
    makePokemon('parasect', 'PARASECT', 52, 'bug', [MOVES.SCRATCH, MOVES.STRING_SHOT], 47, { types: ['bug', 'grass'] }),
    makePokemon('raichu', 'RAICHU', 53, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 26, { types: ['electric'] }),
    makePokemon('ditto', 'DITTO', 53, 'normal', [MOVES.TACKLE], 132),
  ],
  CERULEAN_CAVE_2F: [
    makePokemon('dodrio', 'DODRIO', 51, 'flying', [MOVES.PECK, MOVES.GROWL], 85, { types: ['normal', 'flying'] }),
    makePokemon('venomoth', 'VENOMOTH', 51, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 49, { types: ['bug', 'poison'] }),
    makePokemon('kadabra', 'KADABRA', 51, 'psychic', [MOVES.POUND], 64, { types: ['psychic'] }),
    makePokemon('rhydon', 'RHYDON', 52, 'ground', [MOVES.TACKLE, MOVES.ROCK_THROW], 112, { types: ['ground', 'rock'] }),
    makePokemon('marowak', 'MAROWAK', 52, 'ground', [MOVES.TACKLE], 105),
    makePokemon('electrode', 'ELECTRODE', 52, 'electric', [MOVES.TACKLE, MOVES.THUNDERSHOCK], 101, { types: ['electric'] }),
    makePokemon('chansey', 'CHANSEY', 56, 'normal', [MOVES.POUND], 113),
    makePokemon('wigglytuff', 'WIGGLYTUFF', 54, 'normal', [MOVES.POUND, MOVES.GROWL], 40),
    makePokemon('ditto', 'DITTO', 55, 'normal', [MOVES.TACKLE], 132),
  ],
  CERULEAN_CAVE_B_1F: [
    makePokemon('rhydon', 'RHYDON', 55, 'ground', [MOVES.TACKLE, MOVES.ROCK_THROW], 112, { types: ['ground', 'rock'] }),
    makePokemon('marowak', 'MAROWAK', 55, 'ground', [MOVES.TACKLE], 105),
    makePokemon('electrode', 'ELECTRODE', 55, 'electric', [MOVES.TACKLE, MOVES.THUNDERSHOCK], 101, { types: ['electric'] }),
    makePokemon('chansey', 'CHANSEY', 64, 'normal', [MOVES.POUND], 113),
    makePokemon('parasect', 'PARASECT', 64, 'bug', [MOVES.SCRATCH, MOVES.STRING_SHOT], 47, { types: ['bug', 'grass'] }),
    makePokemon('raichu', 'RAICHU', 64, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 26, { types: ['electric'] }),
    makePokemon('arbok', 'ARBOK', 57, 'poison', [MOVES.TACKLE, MOVES.GROWL], 24, { types: ['poison'] }),
    makePokemon('sandslash', 'SANDSLASH', 57, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 28),
    makePokemon('ditto', 'DITTO', 67, 'normal', [MOVES.TACKLE], 132),
  ],
  DIGLETTS_CAVE: [
    makePokemon('diglett', 'DIGLETT', 18, 'ground', [MOVES.SCRATCH], 50),
    makePokemon('dugtrio', 'DUGTRIO', 30, 'ground', [MOVES.SCRATCH, MOVES.TACKLE], 51),
  ],
  POWER_PLANT: [
    makePokemon('voltorb', 'VOLTORB', 23, 'electric', [MOVES.TACKLE, MOVES.THUNDERSHOCK], 100, { types: ['electric'] }),
    makePokemon('magnemite', 'MAGNEMITE', 23, 'electric', [MOVES.TACKLE, MOVES.THUNDERSHOCK], 81, { types: ['electric'] }),
    makePokemon('pikachu', 'PIKACHU', 24, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 25, { types: ['electric'] }),
    makePokemon('magneton', 'MAGNETON', 35, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 82, { types: ['electric'] }),
    makePokemon('electabuzz', 'ELECTABUZZ', 36, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 125, { types: ['electric'] }),
    makePokemon('raichu', 'RAICHU', 36, 'electric', [MOVES.THUNDERSHOCK, MOVES.TACKLE], 26, { types: ['electric'] }),
  ],
  POKEMON_TOWER_4F: [
    makePokemon('gastly', 'GASTLY', 21, 'ghost', [MOVES.TACKLE, MOVES.LICK], 92, { types: ['ghost', 'poison'] }),
    makePokemon('cubone', 'CUBONE', 22, 'ground', [MOVES.TACKLE, MOVES.GROWL], 104),
    makePokemon('haunter', 'HAUNTER', 23, 'ghost', [MOVES.TACKLE, MOVES.LICK], 93, { types: ['ghost', 'poison'] }),
  ],
  POKEMON_TOWER_5F: [
    makePokemon('gastly', 'GASTLY', 22, 'ghost', [MOVES.TACKLE, MOVES.LICK], 92, { types: ['ghost', 'poison'] }),
    makePokemon('cubone', 'CUBONE', 23, 'ground', [MOVES.TACKLE, MOVES.GROWL], 104),
    makePokemon('haunter', 'HAUNTER', 24, 'ghost', [MOVES.TACKLE, MOVES.LICK], 93, { types: ['ghost', 'poison'] }),
  ],
  POKEMON_TOWER_6F: [
    makePokemon('gastly', 'GASTLY', 23, 'ghost', [MOVES.TACKLE, MOVES.LICK], 92, { types: ['ghost', 'poison'] }),
    makePokemon('cubone', 'CUBONE', 24, 'ground', [MOVES.TACKLE, MOVES.GROWL], 104),
    makePokemon('haunter', 'HAUNTER', 25, 'ghost', [MOVES.TACKLE, MOVES.LICK], 93, { types: ['ghost', 'poison'] }),
  ],
  POKEMON_TOWER_7F: [
    makePokemon('gastly', 'GASTLY', 24, 'ghost', [MOVES.TACKLE, MOVES.LICK], 92, { types: ['ghost', 'poison'] }),
    makePokemon('haunter', 'HAUNTER', 26, 'ghost', [MOVES.TACKLE, MOVES.LICK], 93, { types: ['ghost', 'poison'] }),
    makePokemon('cubone', 'CUBONE', 25, 'ground', [MOVES.TACKLE, MOVES.GROWL], 104),
  ],
  SAFARI_ZONE_CENTER: [
    makePokemon('nidoran-m', 'NIDORAN_M', 22, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('rhyhorn', 'RHYHORN', 25, 'ground', [MOVES.TACKLE, MOVES.ROCK_THROW], 111, { types: ['ground', 'rock'] }),
    makePokemon('venonat', 'VENONAT', 22, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 48, { types: ['bug', 'poison'] }),
    makePokemon('exeggcute', 'EXEGGCUTE', 24, 'grass', [MOVES.POUND], 102, { types: ['grass', 'psychic'] }),
    makePokemon('nidorino', 'NIDORINO', 31, 'poison', [MOVES.TACKLE, MOVES.GROWL], 33, { types: ['poison'] }),
    makePokemon('scyther', 'SCYTHER', 23, 'bug', [MOVES.SCRATCH, MOVES.SLASH], 123, { types: ['bug', 'flying'] }),
    makePokemon('parasect', 'PARASECT', 30, 'bug', [MOVES.SCRATCH, MOVES.STRING_SHOT], 47, { types: ['bug', 'grass'] }),
    makePokemon('chansey', 'CHANSEY', 23, 'normal', [MOVES.POUND], 113),
    makePokemon('nidoran-f', 'NIDORAN_F', 22, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
    makePokemon('nidorina', 'NIDORINA', 31, 'poison', [MOVES.TACKLE, MOVES.GROWL], 30, { types: ['poison'] }),
    makePokemon('pinsir', 'PINSIR', 23, 'bug', [MOVES.STRING_SHOT, MOVES.SLASH], 127),
  ],
  SAFARI_ZONE_EAST: [
    makePokemon('nidoran-m', 'NIDORAN_M', 24, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('doduo', 'DODUO', 26, 'flying', [MOVES.PECK, MOVES.GROWL], 84, { types: ['normal', 'flying'] }),
    makePokemon('paras', 'PARAS', 22, 'bug', [MOVES.SCRATCH, MOVES.STRING_SHOT], 46, { types: ['bug', 'grass'] }),
    makePokemon('exeggcute', 'EXEGGCUTE', 25, 'grass', [MOVES.POUND], 102, { types: ['grass', 'psychic'] }),
    makePokemon('nidorino', 'NIDORINO', 33, 'poison', [MOVES.TACKLE, MOVES.GROWL], 33, { types: ['poison'] }),
    makePokemon('kangaskhan', 'KANGASKHAN', 25, 'normal', [MOVES.TACKLE, MOVES.SLASH], 115),
    makePokemon('parasect', 'PARASECT', 25, 'bug', [MOVES.SCRATCH, MOVES.STRING_SHOT], 47, { types: ['bug', 'grass'] }),
    makePokemon('scyther', 'SCYTHER', 28, 'bug', [MOVES.SCRATCH, MOVES.SLASH], 123, { types: ['bug', 'flying'] }),
    makePokemon('nidoran-f', 'NIDORAN_F', 24, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
    makePokemon('nidorina', 'NIDORINA', 33, 'poison', [MOVES.TACKLE, MOVES.GROWL], 30, { types: ['poison'] }),
    makePokemon('pinsir', 'PINSIR', 28, 'bug', [MOVES.STRING_SHOT, MOVES.SLASH], 127),
  ],
  SAFARI_ZONE_NORTH: [
    makePokemon('nidoran-m', 'NIDORAN_M', 22, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('rhyhorn', 'RHYHORN', 26, 'ground', [MOVES.TACKLE, MOVES.ROCK_THROW], 111, { types: ['ground', 'rock'] }),
    makePokemon('paras', 'PARAS', 23, 'bug', [MOVES.SCRATCH, MOVES.STRING_SHOT], 46, { types: ['bug', 'grass'] }),
    makePokemon('exeggcute', 'EXEGGCUTE', 27, 'grass', [MOVES.POUND], 102, { types: ['grass', 'psychic'] }),
    makePokemon('nidorino', 'NIDORINO', 30, 'poison', [MOVES.TACKLE, MOVES.GROWL], 33, { types: ['poison'] }),
    makePokemon('nidorina', 'NIDORINA', 30, 'poison', [MOVES.TACKLE, MOVES.GROWL], 30, { types: ['poison'] }),
    makePokemon('nidoran-f', 'NIDORAN_F', 22, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
    makePokemon('venomoth', 'VENOMOTH', 32, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 49, { types: ['bug', 'poison'] }),
    makePokemon('chansey', 'CHANSEY', 26, 'normal', [MOVES.POUND], 113),
    makePokemon('tauros', 'TAUROS', 28, 'normal', [MOVES.TACKLE], 128),
  ],
  SAFARI_ZONE_WEST: [
    makePokemon('nidoran-m', 'NIDORAN_M', 25, 'poison', [MOVES.TACKLE, MOVES.GROWL], 32, { types: ['poison'] }),
    makePokemon('doduo', 'DODUO', 26, 'flying', [MOVES.PECK, MOVES.GROWL], 84, { types: ['normal', 'flying'] }),
    makePokemon('venonat', 'VENONAT', 23, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 48, { types: ['bug', 'poison'] }),
    makePokemon('exeggcute', 'EXEGGCUTE', 26, 'grass', [MOVES.POUND], 102, { types: ['grass', 'psychic'] }),
    makePokemon('nidorino', 'NIDORINO', 33, 'poison', [MOVES.TACKLE, MOVES.GROWL], 33, { types: ['poison'] }),
    makePokemon('nidoran-f', 'NIDORAN_F', 25, 'poison', [MOVES.TACKLE, MOVES.GROWL], 29, { types: ['poison'] }),
    makePokemon('nidorina', 'NIDORINA', 33, 'poison', [MOVES.TACKLE, MOVES.GROWL], 30, { types: ['poison'] }),
    makePokemon('venomoth', 'VENOMOTH', 31, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 49, { types: ['bug', 'poison'] }),
    makePokemon('tauros', 'TAUROS', 26, 'normal', [MOVES.TACKLE], 128),
    makePokemon('kangaskhan', 'KANGASKHAN', 28, 'normal', [MOVES.TACKLE, MOVES.SLASH], 115),
  ],
};
