/**
 * FireRed → game-engine bridge.
 *
 * Converts a FireRed layout JSON (output of `scripts/build-firered-pipeline.mjs`)
 * into the same ParsedMap shape the rest of the game consumes. This lets us
 * swap the underlying source from the lossy pokered char-grid pipeline to the
 * canonical FireRed disassembly without rewriting movement, collision, or
 * interaction logic.
 *
 * The bridge does NOT touch the unified KANTO_OVERWORLD — that map is still
 * stitched from pokered data. Per-map FireRed migration happens through the
 * `firered` flag on the parsed map; the renderer uses it to pick the right
 * draw path.
 */

import type { Tile, Position, Direction } from '../../types';
import { tileFromBehavior, WALL } from './behaviorMappings';

// Avoid importing MapID from ../../types — that file's MapID is derived from
// the worldMaps object which itself imports from this bridge, creating a
// cycle. The runtime mapping uses a plain string and is validated against
// the live MapID enum at the consuming site (data/maps/index.ts).
type MapIdString = string;

interface FireredEvent {
  /** Discriminator on bg_events: 'sign' for interactive signposts, 'hidden_item' for buried items, etc. */
  type?: string;
  x: number;
  y: number;
  elevation?: number;
  dest_map?: string;
  dest_warp_id?: string;
}

interface FireredObjectEvent {
  local_id?: string;
  graphics_id?: string;
  x: number;
  y: number;
  movement_type?: string;
  script?: string;
}

export interface FireredLayoutJson {
  id: string;
  name: string;
  width: number;
  height: number;
  primaryTileset: string;
  secondaryTileset: string;
  grid: number[][];
  collision: number[][];
  elevation: number[][];
  behavior?: number[][];
  meta?: {
    warp_events?: FireredEvent[];
    object_events?: FireredObjectEvent[];
    bg_events?: FireredEvent[];
    connections?: { map: string; offset: number; direction: string }[];
    map_type?: string;
  };
}

export interface FireredParsedMap {
  /** Marker so the renderer can branch into FireredMapView. */
  firered: true;
  /** FireRed layout payload — needed for pixel-accurate rendering. */
  layout: FireredLayoutJson;
  /** Per-tile semantics derived from FireRed collision bits + metatile behavior. */
  tiles: Tile[][];
  /** Resolved warps in our coord space. `targetMap` is validated against MapID at the call site. */
  warps: Array<{ x: number; y: number; targetMap: MapIdString; targetPos: Position; targetDir?: Direction; destWarpId?: string }>;
  /** True if this map is underground / cave / dark (Flash-eligible). */
  isUnderground: boolean;
}

/**
 * Mapping from FireRed map IDs (MAP_PALLET_TOWN_PLAYERS_HOUSE_2F) to our
 * internal MapID enum. Indoor entries are auto-generated by
 * scripts/generate-indoor-maps.mjs; outdoor entries are added here because
 * the stitched KANTO_OVERWORLD swallows every Kanto outdoor zone behind
 * one MapID.
 */
import { FIRERED_MAP_ID_TO_INTERNAL } from '../../data/firered/mapIds.generated';

const KANTO_OUTDOOR_MAP_IDS = [
  'MAP_PALLET_TOWN', 'MAP_VIRIDIAN_CITY', 'MAP_PEWTER_CITY', 'MAP_CERULEAN_CITY',
  'MAP_LAVENDER_TOWN', 'MAP_VERMILION_CITY', 'MAP_CELADON_CITY', 'MAP_FUCHSIA_CITY',
  'MAP_CINNABAR_ISLAND', 'MAP_INDIGO_PLATEAU_EXTERIOR', 'MAP_SAFFRON_CITY',
  'MAP_SAFFRON_CITY_CONNECTION',
  'MAP_ROUTE1', 'MAP_ROUTE2', 'MAP_ROUTE3', 'MAP_ROUTE4', 'MAP_ROUTE5',
  'MAP_ROUTE6', 'MAP_ROUTE7', 'MAP_ROUTE8', 'MAP_ROUTE9', 'MAP_ROUTE10',
  'MAP_ROUTE11', 'MAP_ROUTE12', 'MAP_ROUTE13', 'MAP_ROUTE14', 'MAP_ROUTE15',
  'MAP_ROUTE16', 'MAP_ROUTE17', 'MAP_ROUTE18', 'MAP_ROUTE19', 'MAP_ROUTE20',
  'MAP_ROUTE21_NORTH', 'MAP_ROUTE21_SOUTH', 'MAP_ROUTE22', 'MAP_ROUTE23',
  'MAP_ROUTE24', 'MAP_ROUTE25',
  // Gate / connection rooms collapse to the outdoor map they sit on. Without
  // this, VForest's warps to its tiny entrance gate maps don't resolve
  // (silently dropped → "middle of nowhere" warp errors).
  'MAP_ROUTE2_VIRIDIAN_FOREST_SOUTH_ENTRANCE',
  'MAP_ROUTE2_VIRIDIAN_FOREST_NORTH_ENTRANCE',
];

export const FIRERED_MAP_ID_TO_OURS: Record<string, MapIdString> = {
  ...FIRERED_MAP_ID_TO_INTERNAL,
  ...Object.fromEntries(KANTO_OUTDOOR_MAP_IDS.map(id => [id, 'KANTO_OVERWORLD'])),
};

/**
 * Where outgoing warps from a FireRed-migrated indoor map should land in our
 * legacy stitched KANTO_OVERWORLD coord space. Keyed by the source map's
 * FireRed layout ID (so each migrated indoor map can pin its exit door).
 *
 * Without this, a FireRed warp like "MAP_PALLET_TOWN at (5, 8)" would teleport
 * the player to world (5, 8) — empty void in the unified overworld — instead
 * of in front of the building's door. Once KANTO_OVERWORLD itself migrates
 * to per-map FireRed layouts, this can go away.
 */
export const FIRERED_EXIT_TO_KANTO_OVERWORLD: Record<string, { x: number; y: number }> = {
  // FireRed Pallet Town is at world (60, 260); the player's-house door warp
  // is at FireRed local (6, 7) → world (66, 267). Land one tile south so the
  // player isn't standing on the warp tile (avoids immediate re-warp on the
  // arrival animation) and is on a walkable path tile in Pallet Town.
  LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_1F: { x: 66, y: 268 },
};

export function bridgeFireredLayout(layout: FireredLayoutJson): FireredParsedMap {
  const behaviorGrid = layout.behavior;
  // FireRed marks tiles as MB_SIGNPOST (→ 'sign', walkable: false) for any
  // metatile drawn with a sign post — but only the ones with a `bg_events`
  // entry are *interactive*. A phantom sign (signpost behavior with no
  // bg_event) blocks movement without any visible cue and reads as an
  // "invisible wall" on the path. Build the interactive-sign set from the
  // layout's bg_events so we can downgrade phantoms to walkable floor.
  const signEvents = new Set(
    (layout.meta?.bg_events ?? [])
      .filter(e => e.type === 'sign')
      .map(e => `${e.x},${e.y}`)
  );
  const tiles: Tile[][] = [];
  for (let y = 0; y < layout.height; y++) {
    const row: Tile[] = [];
    for (let x = 0; x < layout.width; x++) {
      const behavior = behaviorGrid?.[y]?.[x] ?? 0;
      let t = tileFromBehavior(behavior, false);
      if (t.type === 'sign' && !signEvents.has(`${x},${y}`)) {
        // Phantom sign — no interactive bg_event. Treat as a normal walkable
        // floor tile so it doesn't silently block the player.
        t = { type: 'floor', walkable: true };
      }
      // Door / sign / warp_pad / counter / ledge metatiles have collision=1 but should NOT be WALL.
      // Same for tiles with directional blockFrom (MB_IMPASSABLE_<DIR>).
      const blocked = layout.collision[y][x] !== 0;
      if (blocked && t.type !== 'door' && t.type !== 'sign' && t.type !== 'warp_pad' && t.type !== 'counter' && !t.type.startsWith('ledge_') && !t.blockFrom) {
        row.push(WALL);
      } else {
        row.push(t);
      }
    }
    tiles.push(row);
  }

  const exitPos = FIRERED_EXIT_TO_KANTO_OVERWORLD[layout.id];

  const warps = (layout.meta?.warp_events ?? [])
    .map(w => {
      if (!w.dest_map) return null;
      const targetMap = FIRERED_MAP_ID_TO_OURS[w.dest_map];
      if (!targetMap) return null; // unmapped destination → drop the warp for now

      // Outgoing warp to KANTO_OVERWORLD: use the exit-pin if present so the
      // player lands on the right outdoor tile rather than at the FireRed
      // interior coord on the (much larger) stitched overworld.
      const targetPos = targetMap === 'KANTO_OVERWORLD' && exitPos
        ? exitPos
        : { x: w.x, y: w.y };

      return { x: w.x, y: w.y, targetMap, targetPos, destWarpId: w.dest_warp_id };
    })
    .filter((w): w is NonNullable<typeof w> => w !== null);

  const isUnderground = layout.meta?.map_type === 'MAP_TYPE_UNDERGROUND';

  return { firered: true, layout, tiles, warps, isUnderground };
}
