// AUTOGENERATED by scripts/extract-game-data.mjs — do not edit.

export interface FireredItem {
  english: string;
  price: number;
  pocket: string | null;
  description: string;
  holdEffect: string | null;
}
export const FIRERED_ITEMS: Record<string, FireredItem> = {
  "ITEM_NONE": {
    "english": "????????",
    "price": 0,
    "pocket": "ITEMS",
    "description": "?????",
    "holdEffect": "NONE"
  },
  "ITEM_MASTER_BALL": {
    "english": "MASTER BALL",
    "price": 0,
    "pocket": "POKE_BALLS",
    "description": "The best BALL with the ultimate\\nperformance. It will catch any wild\\nPOKéMON without fail.",
    "holdEffect": "NONE"
  },
  "ITEM_ULTRA_BALL": {
    "english": "ULTRA BALL",
    "price": 1200,
    "pocket": "POKE_BALLS",
    "description": "A very high-grade BALL that offers\\na higher POKéMON catch rate than\\na GREAT BALL.",
    "holdEffect": "NONE"
  },
  "ITEM_GREAT_BALL": {
    "english": "GREAT BALL",
    "price": 600,
    "pocket": "POKE_BALLS",
    "description": "A good, quality BALL that offers\\na higher POKéMON catch rate than\\na standard POKé BALL.",
    "holdEffect": "NONE"
  },
  "ITEM_POKE_BALL": {
    "english": "POKé BALL",
    "price": 200,
    "pocket": "POKE_BALLS",
    "description": "A BALL thrown to catch a wild\\nPOKéMON. It is designed in a\\ncapsule style.",
    "holdEffect": "NONE"
  },
  "ITEM_SAFARI_BALL": {
    "english": "SAFARI BALL",
    "price": 0,
    "pocket": "POKE_BALLS",
    "description": "A special BALL that is used only in\\nthe SAFARI ZONE. It is finished in\\na camouflage pattern.",
    "holdEffect": "NONE"
  },
  "ITEM_NET_BALL": {
    "english": "NET BALL",
    "price": 1000,
    "pocket": "POKE_BALLS",
    "description": "A somewhat different BALL that\\nworks especially well on WATER- and\\nBUG-type POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_DIVE_BALL": {
    "english": "DIVE BALL",
    "price": 1000,
    "pocket": "POKE_BALLS",
    "description": "A somewhat different BALL that\\nworks especially well on POKéMON\\ndeep in the sea.",
    "holdEffect": "NONE"
  },
  "ITEM_NEST_BALL": {
    "english": "NEST BALL",
    "price": 1000,
    "pocket": "POKE_BALLS",
    "description": "A somewhat different BALL that\\nworks especially well on weaker\\nPOKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_REPEAT_BALL": {
    "english": "REPEAT BALL",
    "price": 1000,
    "pocket": "POKE_BALLS",
    "description": "A somewhat different BALL that\\nworks especially well on POKéMON\\ncaught before.",
    "holdEffect": "NONE"
  },
  "ITEM_TIMER_BALL": {
    "english": "TIMER BALL",
    "price": 1000,
    "pocket": "POKE_BALLS",
    "description": "A somewhat different BALL that\\nbecomes progressively better the\\nmore turns there are in a battle.",
    "holdEffect": "NONE"
  },
  "ITEM_LUXURY_BALL": {
    "english": "LUXURY BALL",
    "price": 1000,
    "pocket": "POKE_BALLS",
    "description": "A comfortable BALL that makes a\\ncaptured wild POKéMON quickly grow\\nfriendly.",
    "holdEffect": "NONE"
  },
  "ITEM_PREMIER_BALL": {
    "english": "PREMIER BALL",
    "price": 200,
    "pocket": "POKE_BALLS",
    "description": "A rare BALL that has been\\nspecially made to commemorate an\\nevent of some sort.",
    "holdEffect": "NONE"
  },
  "ITEM_POTION": {
    "english": "POTION",
    "price": 300,
    "pocket": "ITEMS",
    "description": "A spray-type wound medicine.\\nIt restores the HP of one POKéMON\\nby 20 points.",
    "holdEffect": "NONE"
  },
  "ITEM_ANTIDOTE": {
    "english": "ANTIDOTE",
    "price": 100,
    "pocket": "ITEMS",
    "description": "A spray-type medicine.\\nIt heals one POKéMON from a\\npoisoning.",
    "holdEffect": "NONE"
  },
  "ITEM_BURN_HEAL": {
    "english": "BURN HEAL",
    "price": 250,
    "pocket": "ITEMS",
    "description": "A spray-type medicine.\\nIt heals one POKéMON of a burn.",
    "holdEffect": "NONE"
  },
  "ITEM_ICE_HEAL": {
    "english": "ICE HEAL",
    "price": 250,
    "pocket": "ITEMS",
    "description": "A spray-type medicine.\\nIt defrosts a frozen POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_AWAKENING": {
    "english": "AWAKENING",
    "price": 250,
    "pocket": "ITEMS",
    "description": "A spray-type medicine.\\nIt awakens a sleeping POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_PARALYZE_HEAL": {
    "english": "PARLYZ HEAL",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A spray-type medicine.\\nIt heals one POKéMON from\\nparalysis.",
    "holdEffect": "NONE"
  },
  "ITEM_FULL_RESTORE": {
    "english": "FULL RESTORE",
    "price": 3000,
    "pocket": "ITEMS",
    "description": "A medicine that fully restores the\\nHP and heals any status problems\\nof one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_MAX_POTION": {
    "english": "MAX POTION",
    "price": 2500,
    "pocket": "ITEMS",
    "description": "A spray-type wound medicine.\\nIt fully restores the HP of one\\nPOKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_HYPER_POTION": {
    "english": "HYPER POTION",
    "price": 1200,
    "pocket": "ITEMS",
    "description": "A spray-type wound medicine.\\nIt restores the HP of one POKéMON\\nby 200 points.",
    "holdEffect": "NONE"
  },
  "ITEM_SUPER_POTION": {
    "english": "SUPER POTION",
    "price": 700,
    "pocket": "ITEMS",
    "description": "A spray-type wound medicine.\\nIt restores the HP of one POKéMON\\nby 50 points.",
    "holdEffect": "NONE"
  },
  "ITEM_FULL_HEAL": {
    "english": "FULL HEAL",
    "price": 600,
    "pocket": "ITEMS",
    "description": "A spray-type medicine.\\nIt heals all the status problems of\\none POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_REVIVE": {
    "english": "REVIVE",
    "price": 1500,
    "pocket": "ITEMS",
    "description": "A medicine that revives a fainted\\nPOKéMON, restoring HP by half the\\nmaximum amount.",
    "holdEffect": "NONE"
  },
  "ITEM_MAX_REVIVE": {
    "english": "MAX REVIVE",
    "price": 4000,
    "pocket": "ITEMS",
    "description": "A medicine that revives a fainted\\nPOKéMON, restoring HP fully.",
    "holdEffect": "NONE"
  },
  "ITEM_FRESH_WATER": {
    "english": "FRESH WATER",
    "price": 200,
    "pocket": "ITEMS",
    "description": "Water with a high mineral content.\\nIt restores the HP of one POKéMON\\nby 50 points.",
    "holdEffect": "NONE"
  },
  "ITEM_SODA_POP": {
    "english": "SODA POP",
    "price": 300,
    "pocket": "ITEMS",
    "description": "A fizzy soda drink.\\nIt restores the HP of one POKéMON\\nby 60 points.",
    "holdEffect": "NONE"
  },
  "ITEM_LEMONADE": {
    "english": "LEMONADE",
    "price": 350,
    "pocket": "ITEMS",
    "description": "A very sweet drink.\\nIt restores the HP of one POKéMON\\nby 80 points.",
    "holdEffect": "NONE"
  },
  "ITEM_MOOMOO_MILK": {
    "english": "MOOMOO MILK",
    "price": 500,
    "pocket": "ITEMS",
    "description": "Highly nutritious milk.\\nIt restores the HP of one POKéMON\\nby 100 points.",
    "holdEffect": "NONE"
  },
  "ITEM_ENERGY_POWDER": {
    "english": "ENERGYPOWDER",
    "price": 500,
    "pocket": "ITEMS",
    "description": "A very bitter medicine powder.\\nIt restores the HP of one POKéMON\\nby 50 points.",
    "holdEffect": "NONE"
  },
  "ITEM_ENERGY_ROOT": {
    "english": "ENERGY ROOT",
    "price": 800,
    "pocket": "ITEMS",
    "description": "A very bitter root.\\nIt restores the HP of one POKéMON\\nby 200 points.",
    "holdEffect": "NONE"
  },
  "ITEM_HEAL_POWDER": {
    "english": "HEAL POWDER",
    "price": 450,
    "pocket": "ITEMS",
    "description": "A very bitter medicine powder.\\nIt heals all the status problems of\\none POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_REVIVAL_HERB": {
    "english": "REVIVAL HERB",
    "price": 2800,
    "pocket": "ITEMS",
    "description": "A very bitter medicinal herb.\\nIt revives a fainted POKéMON,\\nrestoring HP fully.",
    "holdEffect": "NONE"
  },
  "ITEM_ETHER": {
    "english": "ETHER",
    "price": 1200,
    "pocket": "ITEMS",
    "description": "Restores a selected move's PP by\\n10 points for one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_MAX_ETHER": {
    "english": "MAX ETHER",
    "price": 2000,
    "pocket": "ITEMS",
    "description": "Fully restores a selected move's PP\\nfor one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_ELIXIR": {
    "english": "ELIXIR",
    "price": 3000,
    "pocket": "ITEMS",
    "description": "Restores the PP of all moves for\\none POKéMON by 10 points each.",
    "holdEffect": "NONE"
  },
  "ITEM_MAX_ELIXIR": {
    "english": "MAX ELIXIR",
    "price": 4500,
    "pocket": "ITEMS",
    "description": "Fully restores the PP of all moves\\nfor one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_LAVA_COOKIE": {
    "english": "LAVA COOKIE",
    "price": 200,
    "pocket": "ITEMS",
    "description": "LAVARIDGE TOWN's local specialty.\\nIt heals all the status problems of\\none POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_BLUE_FLUTE": {
    "english": "BLUE FLUTE",
    "price": 100,
    "pocket": "ITEMS",
    "description": "A blue glass flute that awakens\\na sleeping POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_YELLOW_FLUTE": {
    "english": "YELLOW FLUTE",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A yellow glass flute that snaps one\\nPOKéMON out of confusion.",
    "holdEffect": "NONE"
  },
  "ITEM_RED_FLUTE": {
    "english": "RED FLUTE",
    "price": 300,
    "pocket": "ITEMS",
    "description": "A red glass flute that snaps one\\nPOKéMON out of infatuation.",
    "holdEffect": "NONE"
  },
  "ITEM_BLACK_FLUTE": {
    "english": "BLACK FLUTE",
    "price": 400,
    "pocket": "ITEMS",
    "description": "A black glass flute.\\nWhen blown, it makes wild POKéMON\\nless likely to appear.",
    "holdEffect": "NONE"
  },
  "ITEM_WHITE_FLUTE": {
    "english": "WHITE FLUTE",
    "price": 500,
    "pocket": "ITEMS",
    "description": "A white glass flute.\\nWhen blown, it makes wild POKéMON\\nmore likely to appear.",
    "holdEffect": "NONE"
  },
  "ITEM_BERRY_JUICE": {
    "english": "BERRY JUICE",
    "price": 100,
    "pocket": "ITEMS",
    "description": "A 100% pure juice.\\nIt restores the HP of one POKéMON\\nby 20 points.",
    "holdEffect": "RESTORE_HP"
  },
  "ITEM_SACRED_ASH": {
    "english": "SACRED ASH",
    "price": 200,
    "pocket": "ITEMS",
    "description": "Revives all fainted POKéMON,\\nrestoring HP fully.",
    "holdEffect": "NONE"
  },
  "ITEM_SHOAL_SALT": {
    "english": "SHOAL SALT",
    "price": 20,
    "pocket": "ITEMS",
    "description": "Pure salt obtained from deep inside\\nthe SHOAL CAVE. It is extremely\\nsalty.",
    "holdEffect": "NONE"
  },
  "ITEM_SHOAL_SHELL": {
    "english": "SHOAL SHELL",
    "price": 20,
    "pocket": "ITEMS",
    "description": "A pretty seashell found deep inside\\nthe SHOAL CAVE. It is striped in\\nblue and white.",
    "holdEffect": "NONE"
  },
  "ITEM_RED_SHARD": {
    "english": "RED SHARD",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A small red shard.\\nIt appears to be from some sort of\\na tool made long ago.",
    "holdEffect": "NONE"
  },
  "ITEM_BLUE_SHARD": {
    "english": "BLUE SHARD",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A small blue shard.\\nIt appears to be from some sort of\\na tool made long ago.",
    "holdEffect": "NONE"
  },
  "ITEM_YELLOW_SHARD": {
    "english": "YELLOW SHARD",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A small yellow shard.\\nIt appears to be from some sort of\\na tool made long ago.",
    "holdEffect": "NONE"
  },
  "ITEM_GREEN_SHARD": {
    "english": "GREEN SHARD",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A small green shard.\\nIt appears to be from some sort of\\na tool made long ago.",
    "holdEffect": "NONE"
  },
  "ITEM_HP_UP": {
    "english": "HP UP",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A nutritious drink for POKéMON.\\nIt raises the base HP of one\\nPOKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_PROTEIN": {
    "english": "PROTEIN",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A nutritious drink for POKéMON.\\nIt raises the base ATTACK stat of\\none POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_IRON": {
    "english": "IRON",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A nutritious drink for POKéMON.\\nIt raises the base DEFENSE stat of\\none POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_CARBOS": {
    "english": "CARBOS",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A nutritious drink for POKéMON.\\nIt raises the base SPEED stat of\\none POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_CALCIUM": {
    "english": "CALCIUM",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A nutritious drink for POKéMON.\\nIt raises the base SP. ATK stat\\nof one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_RARE_CANDY": {
    "english": "RARE CANDY",
    "price": 4800,
    "pocket": "ITEMS",
    "description": "A candy that is packed with energy.\\nIt raises the level of a POKéMON\\nby one.",
    "holdEffect": "NONE"
  },
  "ITEM_PP_UP": {
    "english": "PP UP",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "Slightly raises the maximum PP of\\na selected move for one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_ZINC": {
    "english": "ZINC",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A nutritious drink for POKéMON.\\nIt raises the base SP. DEF stat\\nof one POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_PP_MAX": {
    "english": "PP MAX",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "Raises the PP of a selected move\\nto its maximum level for one\\nPOKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_GUARD_SPEC": {
    "english": "GUARD SPEC.",
    "price": 700,
    "pocket": "ITEMS",
    "description": "An item that prevents stat reduction\\namong party POKéMON for five turns\\nafter use.",
    "holdEffect": "NONE"
  },
  "ITEM_DIRE_HIT": {
    "english": "DIRE HIT",
    "price": 650,
    "pocket": "ITEMS",
    "description": "Raises the critical-hit ratio of\\nPOKéMON in battle. Wears off if the\\nPOKéMON is withdrawn.",
    "holdEffect": "NONE"
  },
  "ITEM_X_ATTACK": {
    "english": "X ATTACK",
    "price": 500,
    "pocket": "ITEMS",
    "description": "Raises the ATTACK stat of POKéMON\\nin battle. Wears off if the POKéMON\\nis withdrawn.",
    "holdEffect": "NONE"
  },
  "ITEM_X_DEFEND": {
    "english": "X DEFEND",
    "price": 550,
    "pocket": "ITEMS",
    "description": "Raises the DEFENSE stat of POKéMON\\nin battle. Wears off if the POKéMON\\nis withdrawn.",
    "holdEffect": "NONE"
  },
  "ITEM_X_SPEED": {
    "english": "X SPEED",
    "price": 350,
    "pocket": "ITEMS",
    "description": "Raises the SPEED stat of POKéMON\\nin battle. Wears off if the POKéMON\\nis withdrawn.",
    "holdEffect": "NONE"
  },
  "ITEM_X_ACCURACY": {
    "english": "X ACCURACY",
    "price": 950,
    "pocket": "ITEMS",
    "description": "Raises the accuracy stat of\\nPOKéMON in battle. Wears off if the\\nPOKéMON is withdrawn.",
    "holdEffect": "NONE"
  },
  "ITEM_X_SPECIAL": {
    "english": "X SPECIAL",
    "price": 350,
    "pocket": "ITEMS",
    "description": "Raises the SP. ATK stat of\\nPOKéMON in battle. Wears off if the\\nPOKéMON is withdrawn.",
    "holdEffect": "NONE"
  },
  "ITEM_POKE_DOLL": {
    "english": "POKé DOLL",
    "price": 1000,
    "pocket": "ITEMS",
    "description": "An attractive doll.\\nUse it to flee from any battle with\\na wild POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_FLUFFY_TAIL": {
    "english": "FLUFFY TAIL",
    "price": 1000,
    "pocket": "ITEMS",
    "description": "An attractive item.\\nUse it to flee from any battle with\\na wild POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_SUPER_REPEL": {
    "english": "SUPER REPEL",
    "price": 500,
    "pocket": "ITEMS",
    "description": "Prevents weak wild POKéMON from\\nappearing for 200 steps.",
    "holdEffect": "NONE"
  },
  "ITEM_MAX_REPEL": {
    "english": "MAX REPEL",
    "price": 700,
    "pocket": "ITEMS",
    "description": "Prevents weak wild POKéMON from\\nappearing for 250 steps.",
    "holdEffect": "NONE"
  },
  "ITEM_ESCAPE_ROPE": {
    "english": "ESCAPE ROPE",
    "price": 550,
    "pocket": "ITEMS",
    "description": "A long, durable rope.\\nUse it to escape instantly from a\\ncave or a dungeon.",
    "holdEffect": "NONE"
  },
  "ITEM_REPEL": {
    "english": "REPEL",
    "price": 350,
    "pocket": "ITEMS",
    "description": "Prevents weak wild POKéMON from\\nappearing for 100 steps.",
    "holdEffect": "NONE"
  },
  "ITEM_SUN_STONE": {
    "english": "SUN STONE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A peculiar stone that makes certain\\nspecies of POKéMON evolve.\\nIt is as red as the sun.",
    "holdEffect": "NONE"
  },
  "ITEM_MOON_STONE": {
    "english": "MOON STONE",
    "price": 0,
    "pocket": "ITEMS",
    "description": "A peculiar stone that makes certain\\nspecies of POKéMON evolve.\\nIt is as black as the night sky.",
    "holdEffect": "NONE"
  },
  "ITEM_FIRE_STONE": {
    "english": "FIRE STONE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A peculiar stone that makes certain\\nspecies of POKéMON evolve.\\nIt is colored orange.",
    "holdEffect": "NONE"
  },
  "ITEM_THUNDER_STONE": {
    "english": "THUNDERSTONE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A peculiar stone that makes certain\\nspecies of POKéMON evolve.\\nIt has a thunderbolt pattern.",
    "holdEffect": "NONE"
  },
  "ITEM_WATER_STONE": {
    "english": "WATER STONE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A peculiar stone that makes certain\\nspecies of POKéMON evolve.\\nIt is a clear light blue.",
    "holdEffect": "NONE"
  },
  "ITEM_LEAF_STONE": {
    "english": "LEAF STONE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A peculiar stone that makes certain\\nspecies of POKéMON evolve.\\nIt has a leaf pattern.",
    "holdEffect": "NONE"
  },
  "ITEM_TINY_MUSHROOM": {
    "english": "TINYMUSHROOM",
    "price": 500,
    "pocket": "ITEMS",
    "description": "A small and rare mushroom.\\nIt is quite popular among certain\\npeople.",
    "holdEffect": "NONE"
  },
  "ITEM_BIG_MUSHROOM": {
    "english": "BIG MUSHROOM",
    "price": 5000,
    "pocket": "ITEMS",
    "description": "A large and rare mushroom.\\nIt is very popular among certain\\npeople.",
    "holdEffect": "NONE"
  },
  "ITEM_PEARL": {
    "english": "PEARL",
    "price": 1400,
    "pocket": "ITEMS",
    "description": "A relatively small pearl that\\nsparkles in a pretty silver color.\\nIt can be sold cheaply.",
    "holdEffect": "NONE"
  },
  "ITEM_BIG_PEARL": {
    "english": "BIG PEARL",
    "price": 7500,
    "pocket": "ITEMS",
    "description": "A quite-large pearl that sparkles\\nin a pretty silver color.\\nIt can be sold at a high price.",
    "holdEffect": "NONE"
  },
  "ITEM_STARDUST": {
    "english": "STARDUST",
    "price": 2000,
    "pocket": "ITEMS",
    "description": "A pretty red sand with a loose,\\nsilky feel.\\nIt can be sold at a high price.",
    "holdEffect": "NONE"
  },
  "ITEM_STAR_PIECE": {
    "english": "STAR PIECE",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "A shard of a pretty gem that\\nsparkles in a red color.\\nIt can be sold at a high price.",
    "holdEffect": "NONE"
  },
  "ITEM_NUGGET": {
    "english": "NUGGET",
    "price": 10000,
    "pocket": "ITEMS",
    "description": "A nugget of pure gold that gives\\noff a lustrous gleam.\\nIt can be sold at a high price.",
    "holdEffect": "NONE"
  },
  "ITEM_HEART_SCALE": {
    "english": "HEART SCALE",
    "price": 100,
    "pocket": "ITEMS",
    "description": "A pretty, heart-shaped scale that\\nis extremely rare. It glows faintly\\nin the colors of a rainbow.",
    "holdEffect": "NONE"
  },
  "ITEM_ORANGE_MAIL": {
    "english": "ORANGE MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nZIGZAGOON print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_HARBOR_MAIL": {
    "english": "HARBOR MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nWINGULL print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_GLITTER_MAIL": {
    "english": "GLITTER MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nPIKACHU print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_MECH_MAIL": {
    "english": "MECH MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nMAGNEMITE print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_WOOD_MAIL": {
    "english": "WOOD MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nSLAKOTH print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_WAVE_MAIL": {
    "english": "WAVE MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nWAILMER print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_BEAD_MAIL": {
    "english": "BEAD MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL to be held by a\\nPOKéMON. It will bear the print of\\nthe POKéMON holding it.",
    "holdEffect": "NONE"
  },
  "ITEM_SHADOW_MAIL": {
    "english": "SHADOW MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nDUSKULL print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_TROPIC_MAIL": {
    "english": "TROPIC MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a cute\\nBELLOSSOM print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_DREAM_MAIL": {
    "english": "DREAM MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL to be held by a\\nPOKéMON. It will bear the print of\\nthe POKéMON holding it.",
    "holdEffect": "NONE"
  },
  "ITEM_FAB_MAIL": {
    "english": "FAB MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a\\ngorgeous, extravagant print.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_RETRO_MAIL": {
    "english": "RETRO MAIL",
    "price": 50,
    "pocket": "ITEMS",
    "description": "A piece of MAIL featuring a print\\nof three cute POKéMON.\\nIt is to be held by a POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_CHERI_BERRY": {
    "english": "CHERI BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to heal paralysis.",
    "holdEffect": "CURE_PAR"
  },
  "ITEM_CHESTO_BERRY": {
    "english": "CHESTO BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to wake up.",
    "holdEffect": "CURE_SLP"
  },
  "ITEM_PECHA_BERRY": {
    "english": "PECHA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to cure poison.",
    "holdEffect": "CURE_PSN"
  },
  "ITEM_RAWST_BERRY": {
    "english": "RAWST BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to heal a burn.",
    "holdEffect": "CURE_BRN"
  },
  "ITEM_ASPEAR_BERRY": {
    "english": "ASPEAR BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle for defrosting.",
    "holdEffect": "CURE_FRZ"
  },
  "ITEM_LEPPA_BERRY": {
    "english": "LEPPA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to restore 10 PP.",
    "holdEffect": "RESTORE_PP"
  },
  "ITEM_ORAN_BERRY": {
    "english": "ORAN BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to restore 10 HP.",
    "holdEffect": "RESTORE_HP"
  },
  "ITEM_PERSIM_BERRY": {
    "english": "PERSIM BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to lift confusion.",
    "holdEffect": "CURE_CONFUSION"
  },
  "ITEM_LUM_BERRY": {
    "english": "LUM BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to heal any problem.",
    "holdEffect": "CURE_STATUS"
  },
  "ITEM_SITRUS_BERRY": {
    "english": "SITRUS BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it will be\\nused in battle to restore 30 HP.",
    "holdEffect": "RESTORE_HP"
  },
  "ITEM_FIGY_BERRY": {
    "english": "FIGY BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "A hold item that restores HP but\\nmay cause confusion when used.",
    "holdEffect": "CONFUSE_SPICY"
  },
  "ITEM_WIKI_BERRY": {
    "english": "WIKI BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "A hold item that restores HP but\\nmay cause confusion when used.",
    "holdEffect": "CONFUSE_DRY"
  },
  "ITEM_MAGO_BERRY": {
    "english": "MAGO BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "A hold item that restores HP but\\nmay cause confusion when used.",
    "holdEffect": "CONFUSE_SWEET"
  },
  "ITEM_AGUAV_BERRY": {
    "english": "AGUAV BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "A hold item that restores HP but\\nmay cause confusion when used.",
    "holdEffect": "CONFUSE_BITTER"
  },
  "ITEM_IAPAPA_BERRY": {
    "english": "IAPAPA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "A hold item that restores HP but\\nmay cause confusion when used.",
    "holdEffect": "CONFUSE_SOUR"
  },
  "ITEM_RAZZ_BERRY": {
    "english": "RAZZ BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_BLUK_BERRY": {
    "english": "BLUK BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_NANAB_BERRY": {
    "english": "NANAB BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_WEPEAR_BERRY": {
    "english": "WEPEAR BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_PINAP_BERRY": {
    "english": "PINAP BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_POMEG_BERRY": {
    "english": "POMEG BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_KELPSY_BERRY": {
    "english": "KELPSY BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_QUALOT_BERRY": {
    "english": "QUALOT BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_HONDEW_BERRY": {
    "english": "HONDEW BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_GREPA_BERRY": {
    "english": "GREPA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_TAMATO_BERRY": {
    "english": "TAMATO BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_CORNN_BERRY": {
    "english": "CORNN BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_MAGOST_BERRY": {
    "english": "MAGOST BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_RABUTA_BERRY": {
    "english": "RABUTA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_NOMEL_BERRY": {
    "english": "NOMEL BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_SPELON_BERRY": {
    "english": "SPELON BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_PAMTRE_BERRY": {
    "english": "PAMTRE BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_WATMEL_BERRY": {
    "english": "WATMEL BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_DURIN_BERRY": {
    "english": "DURIN BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_BELUE_BERRY": {
    "english": "BELUE BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_LIECHI_BERRY": {
    "english": "LIECHI BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it raises\\nthe ATTACK stat in a pinch.",
    "holdEffect": "ATTACK_UP"
  },
  "ITEM_GANLON_BERRY": {
    "english": "GANLON BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it raises\\nthe DEFENSE stat in a pinch.",
    "holdEffect": "DEFENSE_UP"
  },
  "ITEM_SALAC_BERRY": {
    "english": "SALAC BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it raises\\nthe SPEED stat in a pinch.",
    "holdEffect": "SPEED_UP"
  },
  "ITEM_PETAYA_BERRY": {
    "english": "PETAYA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it raises\\nthe SP. ATK stat in a pinch.",
    "holdEffect": "SP_ATTACK_UP"
  },
  "ITEM_APICOT_BERRY": {
    "english": "APICOT BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it raises\\nthe SP. DEF stat in a pinch.",
    "holdEffect": "SP_DEFENSE_UP"
  },
  "ITEM_LANSAT_BERRY": {
    "english": "LANSAT BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it raises\\nthe critical-hit ratio in a pinch.",
    "holdEffect": "CRITICAL_UP"
  },
  "ITEM_STARF_BERRY": {
    "english": "STARF BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "When held by a POKéMON, it sharply\\nraises one stat in a pinch.",
    "holdEffect": "RANDOM_STAT_UP"
  },
  "ITEM_ENIGMA_BERRY": {
    "english": "ENIGMA BERRY",
    "price": 20,
    "pocket": "BERRY_POUCH",
    "description": "Can be ground up into a powder as\\nan ingredient for medicine.",
    "holdEffect": "NONE"
  },
  "ITEM_BRIGHT_POWDER": {
    "english": "BRIGHTPOWDER",
    "price": 10,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt casts a tricky glare that lowers\\nthe opponent's accuracy.",
    "holdEffect": "EVASION_UP"
  },
  "ITEM_WHITE_HERB": {
    "english": "WHITE HERB",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt restores any lowered stat in\\nbattle. It can be used only once.",
    "holdEffect": "RESTORE_STATS"
  },
  "ITEM_MACHO_BRACE": {
    "english": "MACHO BRACE",
    "price": 3000,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt promotes strong growth but\\nlowers SPEED while it is held.",
    "holdEffect": "MACHO_BRACE"
  },
  "ITEM_EXP_SHARE": {
    "english": "EXP. SHARE",
    "price": 3000,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nThe holder gets a share of EXP.\\npoints without having to battle.",
    "holdEffect": "EXP_SHARE"
  },
  "ITEM_QUICK_CLAW": {
    "english": "QUICK CLAW",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA light and sharp claw. The holder\\nmay be able to strike first.",
    "holdEffect": "QUICK_CLAW"
  },
  "ITEM_SOOTHE_BELL": {
    "english": "SOOTHE BELL",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA bell with a comforting chime that\\nmakes the holder calm and friendly.",
    "holdEffect": "FRIENDSHIP_UP"
  },
  "ITEM_MENTAL_HERB": {
    "english": "MENTAL HERB",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt snaps the holder out of\\ninfatuation. It can be used once.",
    "holdEffect": "CURE_ATTRACT"
  },
  "ITEM_CHOICE_BAND": {
    "english": "CHOICE BAND",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt powers up one move, which\\nbecomes the only usable one.",
    "holdEffect": "CHOICE_BAND"
  },
  "ITEM_KINGS_ROCK": {
    "english": "KING'S ROCK",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt may cause the foe to flinch\\nupon taking damage.",
    "holdEffect": "FLINCH"
  },
  "ITEM_SILVER_POWDER": {
    "english": "SILVERPOWDER",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA shiny silver powder that boosts\\nthe power of BUG-type moves.",
    "holdEffect": "BUG_POWER"
  },
  "ITEM_AMULET_COIN": {
    "english": "AMULET COIN",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt doubles the battle money if the\\nholding POKéMON takes part.",
    "holdEffect": "DOUBLE_PRIZE"
  },
  "ITEM_CLEANSE_TAG": {
    "english": "CLEANSE TAG",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt repels wild POKéMON if the\\nholder is first in the party.",
    "holdEffect": "REPEL"
  },
  "ITEM_SOUL_DEW": {
    "english": "SOUL DEW",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An orb to be held by a LATIOS or\\nLATIAS. It raises the SP. ATK\\nand SP. DEF stats.",
    "holdEffect": "SOUL_DEW"
  },
  "ITEM_DEEP_SEA_TOOTH": {
    "english": "DEEPSEATOOTH",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA fang that gleams a sharp silver.\\nIt raises the SP. ATK stat.",
    "holdEffect": "DEEP_SEA_TOOTH"
  },
  "ITEM_DEEP_SEA_SCALE": {
    "english": "DEEPSEASCALE",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA scale that shines a faint pink.\\nIt raises the SP. DEF stat.",
    "holdEffect": "DEEP_SEA_SCALE"
  },
  "ITEM_SMOKE_BALL": {
    "english": "SMOKE BALL",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nThe holding POKéMON can flee from\\nany wild POKéMON for sure.",
    "holdEffect": "CAN_ALWAYS_RUN"
  },
  "ITEM_EVERSTONE": {
    "english": "EVERSTONE",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nThe holding POKéMON is prevented\\nfrom evolving.",
    "holdEffect": "PREVENT_EVOLVE"
  },
  "ITEM_FOCUS_BAND": {
    "english": "FOCUS BAND",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nThe holding POKéMON may endure an\\nattack, leaving just 1 HP.",
    "holdEffect": "FOCUS_BAND"
  },
  "ITEM_LUCKY_EGG": {
    "english": "LUCKY EGG",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nAn egg filled with happiness that\\nearns extra EXP. points in battle.",
    "holdEffect": "LUCKY_EGG"
  },
  "ITEM_SCOPE_LENS": {
    "english": "SCOPE LENS",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA lens that boosts the critical-hit\\nratio of the holding POKéMON.",
    "holdEffect": "SCOPE_LENS"
  },
  "ITEM_METAL_COAT": {
    "english": "METAL COAT",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA special metallic film that boosts\\nthe power of STEEL-type moves.",
    "holdEffect": "STEEL_POWER"
  },
  "ITEM_LEFTOVERS": {
    "english": "LEFTOVERS",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nThe holding POKéMON gradually\\nregains HP during battle.",
    "holdEffect": "LEFTOVERS"
  },
  "ITEM_DRAGON_SCALE": {
    "english": "DRAGON SCALE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A thick and tough scale.\\nA DRAGON-type POKéMON may be\\nholding it.",
    "holdEffect": "DRAGON_SCALE"
  },
  "ITEM_LIGHT_BALL": {
    "english": "LIGHT BALL",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An orb to be held by a PIKACHU\\nthat raises the SP. ATK stat.\\nTouching it may cause a shock.",
    "holdEffect": "LIGHT_BALL"
  },
  "ITEM_SOFT_SAND": {
    "english": "SOFT SAND",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA loose, silky sand that boosts the\\npower of GROUND-type moves.",
    "holdEffect": "GROUND_POWER"
  },
  "ITEM_HARD_STONE": {
    "english": "HARD STONE",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nAn unbreakable stone that boosts\\nthe power of ROCK-type moves.",
    "holdEffect": "ROCK_POWER"
  },
  "ITEM_MIRACLE_SEED": {
    "english": "MIRACLE SEED",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA seed imbued with life that boosts\\nthe power of GRASS-type moves.",
    "holdEffect": "GRASS_POWER"
  },
  "ITEM_BLACK_GLASSES": {
    "english": "BLACKGLASSES",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA shady-looking pair of glasses\\nthat boosts DARK-type moves.",
    "holdEffect": "DARK_POWER"
  },
  "ITEM_BLACK_BELT": {
    "english": "BLACK BELT",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA belt that boosts determination\\nand FIGHTING-type moves.",
    "holdEffect": "FIGHTING_POWER"
  },
  "ITEM_MAGNET": {
    "english": "MAGNET",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA powerful magnet that boosts the\\npower of ELECTRIC-type moves.",
    "holdEffect": "ELECTRIC_POWER"
  },
  "ITEM_MYSTIC_WATER": {
    "english": "MYSTIC WATER",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA teardrop-shaped gem that boosts\\nthe power of WATER-type moves.",
    "holdEffect": "WATER_POWER"
  },
  "ITEM_SHARP_BEAK": {
    "english": "SHARP BEAK",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA long, sharp beak that boosts the\\npower of FLYING-type moves.",
    "holdEffect": "FLYING_POWER"
  },
  "ITEM_POISON_BARB": {
    "english": "POISON BARB",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA small, poisonous barb that boosts\\nthe power of POISON-type moves.",
    "holdEffect": "POISON_POWER"
  },
  "ITEM_NEVER_MELT_ICE": {
    "english": "NEVERMELTICE",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA piece of ice that repels heat\\nand boosts ICE-type moves.",
    "holdEffect": "ICE_POWER"
  },
  "ITEM_SPELL_TAG": {
    "english": "SPELL TAG",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA sinister, eerie tag that boosts\\nGHOST-type moves.",
    "holdEffect": "GHOST_POWER"
  },
  "ITEM_TWISTED_SPOON": {
    "english": "TWISTEDSPOON",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA spoon imbued with telekinetic\\npower boosts PSYCHIC-type moves.",
    "holdEffect": "PSYCHIC_POWER"
  },
  "ITEM_CHARCOAL": {
    "english": "CHARCOAL",
    "price": 9800,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA combustible fuel that boosts the\\npower of FIRE-type moves.",
    "holdEffect": "FIRE_POWER"
  },
  "ITEM_DRAGON_FANG": {
    "english": "DRAGON FANG",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA hard and sharp fang that boosts\\nthe power of DRAGON-type moves.",
    "holdEffect": "DRAGON_POWER"
  },
  "ITEM_SILK_SCARF": {
    "english": "SILK SCARF",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nA sumptuous scarf that boosts the\\npower of NORMAL-type moves.",
    "holdEffect": "NORMAL_POWER"
  },
  "ITEM_UP_GRADE": {
    "english": "UP-GRADE",
    "price": 2100,
    "pocket": "ITEMS",
    "description": "A transparent device filled with all\\nsorts of data.\\nIt is made by SILPH CO.",
    "holdEffect": "UP_GRADE"
  },
  "ITEM_SHELL_BELL": {
    "english": "SHELL BELL",
    "price": 200,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nThe holding POKéMON regains some\\nHP upon striking the foe.",
    "holdEffect": "SHELL_BELL"
  },
  "ITEM_SEA_INCENSE": {
    "english": "SEA INCENSE",
    "price": 9600,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt slightly boosts the power of\\nWATER-type moves.",
    "holdEffect": "WATER_POWER"
  },
  "ITEM_LAX_INCENSE": {
    "english": "LAX INCENSE",
    "price": 9600,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIts tricky aroma slightly reduces\\nthe foe's accuracy.",
    "holdEffect": "EVASION_UP"
  },
  "ITEM_LUCKY_PUNCH": {
    "english": "LUCKY PUNCH",
    "price": 10,
    "pocket": "ITEMS",
    "description": "A glove to be held by a CHANSEY.\\nIt raises CHANSEY's critical-hit\\nratio.",
    "holdEffect": "LUCKY_PUNCH"
  },
  "ITEM_METAL_POWDER": {
    "english": "METAL POWDER",
    "price": 10,
    "pocket": "ITEMS",
    "description": "A fine, hard powder to be held by\\na DITTO.\\nIt raises DITTO's DEFENSE stat.",
    "holdEffect": "METAL_POWDER"
  },
  "ITEM_THICK_CLUB": {
    "english": "THICK CLUB",
    "price": 500,
    "pocket": "ITEMS",
    "description": "A hard bone of some sort to be\\nheld by a CUBONE or MAROWAK.\\nIt raises the ATTACK stat.",
    "holdEffect": "THICK_CLUB"
  },
  "ITEM_STICK": {
    "english": "STICK",
    "price": 200,
    "pocket": "ITEMS",
    "description": "A stick of leek to be held by a\\nFARFETCH'D. It raises FARFETCH'D's\\ncritical-hit ratio.",
    "holdEffect": "STICK"
  },
  "ITEM_RED_SCARF": {
    "english": "RED SCARF",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt boosts the holding POKéMON's\\nCOOL condition in CONTESTS.",
    "holdEffect": "NONE"
  },
  "ITEM_BLUE_SCARF": {
    "english": "BLUE SCARF",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt boosts the holding POKéMON's\\nBEAUTY condition in CONTESTS.",
    "holdEffect": "NONE"
  },
  "ITEM_PINK_SCARF": {
    "english": "PINK SCARF",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt boosts the holding POKéMON's\\nCUTE condition in CONTESTS.",
    "holdEffect": "NONE"
  },
  "ITEM_GREEN_SCARF": {
    "english": "GREEN SCARF",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt boosts the holding POKéMON's\\nSMART condition in CONTESTS.",
    "holdEffect": "NONE"
  },
  "ITEM_YELLOW_SCARF": {
    "english": "YELLOW SCARF",
    "price": 100,
    "pocket": "ITEMS",
    "description": "An item to be held by a POKéMON.\\nIt boosts the holding POKéMON's\\nTOUGH condition in CONTESTS.",
    "holdEffect": "NONE"
  },
  "ITEM_MACH_BIKE": {
    "english": "MACH BIKE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A folding bicycle that is at least\\ntwice as fast as walking.",
    "holdEffect": "NONE"
  },
  "ITEM_COIN_CASE": {
    "english": "COIN CASE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A case for holding COINS obtained\\nat the GAME CORNER.\\nIt holds up to 9,999 COINS.",
    "holdEffect": "NONE"
  },
  "ITEM_ITEMFINDER": {
    "english": "ITEMFINDER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A device used for finding items.\\nIf there is a hidden item nearby\\nwhen it is used, it emits a signal.",
    "holdEffect": "NONE"
  },
  "ITEM_OLD_ROD": {
    "english": "OLD ROD",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An old and beat-up fishing rod.\\nUse it by any body of water to \\nfish for wild POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_GOOD_ROD": {
    "english": "GOOD ROD",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A new, good-quality fishing rod.\\nUse it by any body of water to \\nfish for wild POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_SUPER_ROD": {
    "english": "SUPER ROD",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An awesome, high-tech fishing rod.\\nUse it by any body of water to fish\\nfor wild POKéMON.",
    "holdEffect": "NONE"
  },
  "ITEM_SS_TICKET": {
    "english": "S.S. TICKET",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "The ticket required for sailing on\\nthe ferry S.S. ANNE.\\nIt has a drawing of a ship on it.",
    "holdEffect": "NONE"
  },
  "ITEM_CONTEST_PASS": {
    "english": "CONTEST PASS",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "The pass required for entering\\nPOKéMON CONTESTS. It has a\\ndrawing of an award ribbon on it.",
    "holdEffect": "NONE"
  },
  "ITEM_WAILMER_PAIL": {
    "english": "WAILMER PAIL",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A nifty watering pail.\\nUse it to promote strong growth in\\nBERRIES planted in soft soil.",
    "holdEffect": "NONE"
  },
  "ITEM_DEVON_GOODS": {
    "english": "DEVON GOODS",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A package that contains mechanical\\nparts of some sort made by the\\nDEVON CORPORATION.",
    "holdEffect": "NONE"
  },
  "ITEM_SOOT_SACK": {
    "english": "SOOT SACK",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A sack used to collect volcanic\\nash automatically during walks\\nover deep ash.",
    "holdEffect": "NONE"
  },
  "ITEM_BASEMENT_KEY": {
    "english": "BASEMENT KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "The key to NEW MAUVILLE, which\\nwas constructed beneath MAUVILLE\\nCITY.",
    "holdEffect": "NONE"
  },
  "ITEM_ACRO_BIKE": {
    "english": "ACRO BIKE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A folding bicycle that is capable\\nof stunts like jumps and wheelies.",
    "holdEffect": "NONE"
  },
  "ITEM_POKEBLOCK_CASE": {
    "english": "{POKEBLOCK} CASE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A case for holding {POKEBLOCK}S made\\nwith a BERRY BLENDER. It releases\\none {POKEBLOCK} when shaken.",
    "holdEffect": "NONE"
  },
  "ITEM_LETTER": {
    "english": "LETTER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An extremely important letter to\\nSTEVEN from the PRESIDENT of the\\nDEVON CORPORATION.",
    "holdEffect": "NONE"
  },
  "ITEM_EON_TICKET": {
    "english": "EON TICKET",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "The ticket required for sailing on a\\nferry to a distant southern island.\\nIt features a drawing of an island.",
    "holdEffect": "NONE"
  },
  "ITEM_RED_ORB": {
    "english": "RED ORB",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An orb that glows red.\\nIt is said to contain an incredible\\npower from ancient times.",
    "holdEffect": "NONE"
  },
  "ITEM_BLUE_ORB": {
    "english": "BLUE ORB",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An orb that glows blue.\\nIt is said to contain an incredible\\npower from ancient times.",
    "holdEffect": "NONE"
  },
  "ITEM_SCANNER": {
    "english": "SCANNER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A device used to search for\\nlife-forms in water.\\nIt looks too difficult to use.",
    "holdEffect": "NONE"
  },
  "ITEM_GO_GOGGLES": {
    "english": "GO-GOGGLES",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A pair of protective goggles.\\nThey enable a TRAINER to travel\\nthrough even desert sandstorms.",
    "holdEffect": "NONE"
  },
  "ITEM_METEORITE": {
    "english": "METEORITE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A meteorite that fell from space\\nonto MT. MOON long ago.\\nIt is very lumpy and hard.",
    "holdEffect": "NONE"
  },
  "ITEM_ROOM_1_KEY": {
    "english": "RM. 1 KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A key that opens the door to Room\\n1 inside the ABANDONED SHIP.\\nIt is old and looks easily broken.",
    "holdEffect": "NONE"
  },
  "ITEM_ROOM_2_KEY": {
    "english": "RM. 2 KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A key that opens the door to Room\\n2 inside the ABANDONED SHIP.\\nIt is old and looks easily broken.",
    "holdEffect": "NONE"
  },
  "ITEM_ROOM_4_KEY": {
    "english": "RM. 4 KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A key that opens the door to Room\\n4 inside the ABANDONED SHIP.\\nIt is old and looks easily broken.",
    "holdEffect": "NONE"
  },
  "ITEM_ROOM_6_KEY": {
    "english": "RM. 6 KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A key that opens the door to Room\\n6 inside the ABANDONED SHIP.\\nIt is old and looks easily broken.",
    "holdEffect": "NONE"
  },
  "ITEM_STORAGE_KEY": {
    "english": "STORAGE KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A key that opens the storage hold\\ninside the ABANDONED SHIP.\\nIt is old and looks easily broken.",
    "holdEffect": "NONE"
  },
  "ITEM_ROOT_FOSSIL": {
    "english": "ROOT FOSSIL",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A fossil of an ancient, seafloor-\\ndwelling POKéMON. It appears to be\\npart of a plant root.",
    "holdEffect": "NONE"
  },
  "ITEM_CLAW_FOSSIL": {
    "english": "CLAW FOSSIL",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A fossil of an ancient, seafloor-\\ndwelling POKéMON. It appears to be\\npart of a claw.",
    "holdEffect": "NONE"
  },
  "ITEM_DEVON_SCOPE": {
    "english": "DEVON SCOPE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A scope that signals the presence\\nof any unseeable POKéMON.\\nIt is made by the DEVON CORP.",
    "holdEffect": "NONE"
  },
  "ITEM_TM01": {
    "english": "TM01",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "An extremely powerful attack.\\nHowever, if the user is hit before\\nusing the move, they will flinch.",
    "holdEffect": "NONE"
  },
  "ITEM_TM02": {
    "english": "TM02",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "Sharp, huge claws hook and slash\\nthe foe quickly and with great\\npower.",
    "holdEffect": "NONE"
  },
  "ITEM_TM03": {
    "english": "TM03",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The foe is hit with a pulsing blast\\nof water. It may also confuse the\\ntarget.",
    "holdEffect": "NONE"
  },
  "ITEM_TM04": {
    "english": "TM04",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The user calms its spirit and\\nfocuses its mind to raise its\\nSP. ATK and SP. DEF stats.",
    "holdEffect": "NONE"
  },
  "ITEM_TM05": {
    "english": "TM05",
    "price": 1000,
    "pocket": "TM_CASE",
    "description": "A savage roar that causes the foe\\nto switch out of battle. In the\\nwild, ROAR ends the battle.",
    "holdEffect": "NONE"
  },
  "ITEM_TM06": {
    "english": "TM06",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A move that leaves the foe badly\\npoisoned. Its poison damage worsens\\nevery turn.",
    "holdEffect": "NONE"
  },
  "ITEM_TM07": {
    "english": "TM07",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "Summons a hailstorm that lasts for\\nfive turns. The hailstorm damages\\nall types except the ICE type.",
    "holdEffect": "NONE"
  },
  "ITEM_TM08": {
    "english": "TM08",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The user tightens all its muscles\\nand bulks up, boosting both its\\nATTACK and DEFENSE stats.",
    "holdEffect": "NONE"
  },
  "ITEM_TM09": {
    "english": "TM09",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The user shoots seeds at the foe\\nin rapid succession. Two to five\\nseeds are shot at once.",
    "holdEffect": "NONE"
  },
  "ITEM_TM10": {
    "english": "TM10",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A variable move that changes type\\nand power depending on the POKéMON\\nusing it.",
    "holdEffect": "NONE"
  },
  "ITEM_TM11": {
    "english": "TM11",
    "price": 2000,
    "pocket": "TM_CASE",
    "description": "The weather is turned sunny for\\nfive turns. Over that time, FIRE-\\ntype moves are powered up.",
    "holdEffect": "NONE"
  },
  "ITEM_TM12": {
    "english": "TM12",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A taunted foe may become enraged.\\nIt will then only be able to use\\nattack moves.",
    "holdEffect": "NONE"
  },
  "ITEM_TM13": {
    "english": "TM13",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "An icy-cold beam is shot at the\\nfoe. It may leave the target\\nfrozen.",
    "holdEffect": "NONE"
  },
  "ITEM_TM14": {
    "english": "TM14",
    "price": 5500,
    "pocket": "TM_CASE",
    "description": "A vicious snow-and-wind attack that\\nstrikes all foes in battle. It may\\ncause freezing.",
    "holdEffect": "NONE"
  },
  "ITEM_TM15": {
    "english": "TM15",
    "price": 7500,
    "pocket": "TM_CASE",
    "description": "A harsh attack that inflicts severe\\ndamage on the foe. However, the\\nuser must rest the next turn.",
    "holdEffect": "NONE"
  },
  "ITEM_TM16": {
    "english": "TM16",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A wall of light is created over\\nfive turns. It reduces damage from\\nSP. ATK attacks.",
    "holdEffect": "NONE"
  },
  "ITEM_TM17": {
    "english": "TM17",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The user is completely protected\\nfrom attack in the turn it is used.\\nIt may fail if used in succession.",
    "holdEffect": "NONE"
  },
  "ITEM_TM18": {
    "english": "TM18",
    "price": 2000,
    "pocket": "TM_CASE",
    "description": "A heavy rain is summoned for five\\nturns. Over that time, WATER-type\\nmoves are powered up.",
    "holdEffect": "NONE"
  },
  "ITEM_TM19": {
    "english": "TM19",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The user strikes the foe with\\ntentacles or roots, stealing the\\ntarget's HP and healing itself.",
    "holdEffect": "NONE"
  },
  "ITEM_TM20": {
    "english": "TM20",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "Protects the party with a shield\\nagainst all status problems over\\nfive turns.",
    "holdEffect": "NONE"
  },
  "ITEM_TM21": {
    "english": "TM21",
    "price": 1000,
    "pocket": "TM_CASE",
    "description": "This attack move grows more\\npowerful the more the POKéMON\\ndislikes its TRAINER.",
    "holdEffect": "NONE"
  },
  "ITEM_TM22": {
    "english": "TM22",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A 2-turn attack that uses the first\\nturn for absorbing sunlight, then\\nblasting the foe in the next turn.",
    "holdEffect": "NONE"
  },
  "ITEM_TM23": {
    "english": "TM23",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The foe is slammed with a sturdy\\ntail of steel. It may lower the\\ntarget's DEFENSE stat.",
    "holdEffect": "NONE"
  },
  "ITEM_TM24": {
    "english": "TM24",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A massive jolt of electricity is\\nlaunched at the foe. It may cause\\nparalysis.",
    "holdEffect": "NONE"
  },
  "ITEM_TM25": {
    "english": "TM25",
    "price": 5500,
    "pocket": "TM_CASE",
    "description": "Strikes the foe with a huge\\nthunderbolt. It may cause\\nparalysis.",
    "holdEffect": "NONE"
  },
  "ITEM_TM26": {
    "english": "TM26",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "Causes an earthquake that strikes\\nall POKéMON in battle, excluding\\nthe user.",
    "holdEffect": "NONE"
  },
  "ITEM_TM27": {
    "english": "TM27",
    "price": 1000,
    "pocket": "TM_CASE",
    "description": "This attack move grows more\\npowerful the more the POKéMON\\nlikes its TRAINER.",
    "holdEffect": "NONE"
  },
  "ITEM_TM28": {
    "english": "TM28",
    "price": 2000,
    "pocket": "TM_CASE",
    "description": "A 2-turn attack in which the user\\ndigs underground, then strikes.\\nIt can be used to exit dungeons.",
    "holdEffect": "NONE"
  },
  "ITEM_TM29": {
    "english": "TM29",
    "price": 2000,
    "pocket": "TM_CASE",
    "description": "A powerful blast of telekinetic\\nenergy strikes the foe. It may\\nlower the target's SP. DEF stat.",
    "holdEffect": "NONE"
  },
  "ITEM_TM30": {
    "english": "TM30",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The foe is attacked with a shadowy\\nlump. It may lower the target's\\nSP. DEF stat.",
    "holdEffect": "NONE"
  },
  "ITEM_TM31": {
    "english": "TM31",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "Strikes the foe with a rock-hard\\nfist, etc. It shatters barriers such\\nas REFLECT and LIGHT SCREEN.",
    "holdEffect": "NONE"
  },
  "ITEM_TM32": {
    "english": "TM32",
    "price": 2000,
    "pocket": "TM_CASE",
    "description": "The user begins moving so quickly\\nthat it creates illusory copies to\\nraise its evasiveness.",
    "holdEffect": "NONE"
  },
  "ITEM_TM33": {
    "english": "TM33",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A tough barrier is put up over five\\nturns. It reduces damage from\\nphysical attacks over that time.",
    "holdEffect": "NONE"
  },
  "ITEM_TM34": {
    "english": "TM34",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A rapid jolt of electricity strikes\\nthe foe. This attack is impossible\\nto evade.",
    "holdEffect": "NONE"
  },
  "ITEM_TM35": {
    "english": "TM35",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The foe is roasted with a heavy\\nblast of fire. It may leave the\\ntarget with a burn.",
    "holdEffect": "NONE"
  },
  "ITEM_TM36": {
    "english": "TM36",
    "price": 1000,
    "pocket": "TM_CASE",
    "description": "Toxic sludge is hurled at the foe\\nwith great force. It may also\\npoison the target.",
    "holdEffect": "NONE"
  },
  "ITEM_TM37": {
    "english": "TM37",
    "price": 2000,
    "pocket": "TM_CASE",
    "description": "Summons a sandstorm that lasts for\\nfive turns. It damages all types\\nexcept ROCK, GROUND, and STEEL.",
    "holdEffect": "NONE"
  },
  "ITEM_TM38": {
    "english": "TM38",
    "price": 5500,
    "pocket": "TM_CASE",
    "description": "The foe is incinerated with an\\nintense flame. It may leave the\\ntarget with a burn.",
    "holdEffect": "NONE"
  },
  "ITEM_TM39": {
    "english": "TM39",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "Boulders are hurled at the foe.\\nIt also lowers the target's SPEED\\nstat if it hits.",
    "holdEffect": "NONE"
  },
  "ITEM_TM40": {
    "english": "TM40",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "An extremely fast attack against\\none target. It is impossible to\\nevade.",
    "holdEffect": "NONE"
  },
  "ITEM_TM41": {
    "english": "TM41",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "If enraged by this move, the target\\nbecomes incapable of using the same\\nmove twice in a row.",
    "holdEffect": "NONE"
  },
  "ITEM_TM42": {
    "english": "TM42",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "An attack move that becomes very\\npowerful if the user is poisoned,\\nburned, or paralyzed.",
    "holdEffect": "NONE"
  },
  "ITEM_TM43": {
    "english": "TM43",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "An attack move that may have an\\nadditional effect depending on the\\nbattle terrain.",
    "holdEffect": "NONE"
  },
  "ITEM_TM44": {
    "english": "TM44",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A move that makes the user fall\\nasleep over two turns to restore HP\\nand heal any status problems.",
    "holdEffect": "NONE"
  },
  "ITEM_TM45": {
    "english": "TM45",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The foe, if it is the opposite\\ngender as the user, becomes\\ninfatuated and may not attack.",
    "holdEffect": "NONE"
  },
  "ITEM_TM46": {
    "english": "TM46",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "An attack that gives the user an\\nopportunity to steal the foe's hold\\nitem.",
    "holdEffect": "NONE"
  },
  "ITEM_TM47": {
    "english": "TM47",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "The foe is struck with steel-hard\\nwings. It may also raise the user's\\nDEFENSE stat.",
    "holdEffect": "NONE"
  },
  "ITEM_TM48": {
    "english": "TM48",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A special power is transmitted to\\nthe foe, causing it to switch\\nabilities with the user.",
    "holdEffect": "NONE"
  },
  "ITEM_TM49": {
    "english": "TM49",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A move that steals the effects of\\nany status-changing or healing move\\nthat the foe tries to use.",
    "holdEffect": "NONE"
  },
  "ITEM_TM50": {
    "english": "TM50",
    "price": 3000,
    "pocket": "TM_CASE",
    "description": "A maximum-power attack of great\\nferocity, but one that also sharply\\nreduces the user's SP. ATK stat.",
    "holdEffect": "NONE"
  },
  "ITEM_HM01": {
    "english": "HM01",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "Attacks the foe with sharp blades\\nor claws. It can also cut down thin\\ntrees and grass outside of battle.",
    "holdEffect": "NONE"
  },
  "ITEM_HM02": {
    "english": "HM02",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "The user flies up on the first turn,\\nthen attacks next turn. It can be\\nused to fly to any known town.",
    "holdEffect": "NONE"
  },
  "ITEM_HM03": {
    "english": "HM03",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "Creates a huge wave, then crashes\\nit down on the foe. It can be used\\nfor traveling on water.",
    "holdEffect": "NONE"
  },
  "ITEM_HM04": {
    "english": "HM04",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "The user builds enormous power,\\nthen slams the foe. It can be used\\nfor moving large, round boulders.",
    "holdEffect": "NONE"
  },
  "ITEM_HM05": {
    "english": "HM05",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "Looses a powerful blast of light\\nthat reduces the foe's accuracy.\\nIt also lights up dark caves.",
    "holdEffect": "NONE"
  },
  "ITEM_HM06": {
    "english": "HM06",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "Hits the foe with a rock-crushingly\\ntough attack. It can smash cracked\\nboulders.",
    "holdEffect": "NONE"
  },
  "ITEM_HM07": {
    "english": "HM07",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "A powerful charge attack. It can\\nbe used for climbing a torrential\\nwaterfall.",
    "holdEffect": "NONE"
  },
  "ITEM_HM08": {
    "english": "HM08",
    "price": 0,
    "pocket": "TM_CASE",
    "description": "A 2-turn attack in which the user\\ndives underwater on the first turn,\\nthen strikes in the next turn.",
    "holdEffect": "NONE"
  },
  "ITEM_OAKS_PARCEL": {
    "english": "OAK'S PARCEL",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A parcel to be delivered to PROF.\\nOAK from VIRIDIAN CITY's POKéMON\\nMART.",
    "holdEffect": "NONE"
  },
  "ITEM_POKE_FLUTE": {
    "english": "POKé FLUTE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A flute that is said to instantly\\nawaken any POKéMON. It has a\\nlovely tone.",
    "holdEffect": "NONE"
  },
  "ITEM_SECRET_KEY": {
    "english": "SECRET KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "The key to CINNABAR ISLAND GYM's\\nfront door. It is colored red and\\ndecorated.",
    "holdEffect": "NONE"
  },
  "ITEM_BIKE_VOUCHER": {
    "english": "BIKE VOUCHER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "Take this voucher to the BIKE SHOP\\nin CERULEAN CITY and exchange it\\nfor a bicycle.",
    "holdEffect": "NONE"
  },
  "ITEM_GOLD_TEETH": {
    "english": "GOLD TEETH",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A set of false teeth lost by the\\nSAFARI ZONE'S WARDEN. It makes his\\nsmile sparkle.",
    "holdEffect": "NONE"
  },
  "ITEM_OLD_AMBER": {
    "english": "OLD AMBER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A piece of amber that contains\\nthe genes of an ancient POKéMON.\\nIt is clear with a reddish tint.",
    "holdEffect": "NONE"
  },
  "ITEM_CARD_KEY": {
    "english": "CARD KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A card-type key that unlocks doors\\nin SILPH CO.'s HEAD OFFICE in\\nSAFFRON CITY.",
    "holdEffect": "NONE"
  },
  "ITEM_LIFT_KEY": {
    "english": "LIFT KEY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A key that operates the elevator\\nin TEAM ROCKET's HIDEOUT.\\nIt bears the TEAM ROCKET logo.",
    "holdEffect": "NONE"
  },
  "ITEM_HELIX_FOSSIL": {
    "english": "HELIX FOSSIL",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A fossil of an ancient, seafloor-\\ndwelling POKéMON. It appears to be\\npart of a seashell.",
    "holdEffect": "NONE"
  },
  "ITEM_DOME_FOSSIL": {
    "english": "DOME FOSSIL",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A fossil of an ancient, seafloor-\\ndwelling POKéMON. It appears to be\\npart of a shell.",
    "holdEffect": "NONE"
  },
  "ITEM_SILPH_SCOPE": {
    "english": "SILPH SCOPE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A scope that makes unseeable\\nPOKéMON visible.\\nIt is made by SILPH CO.",
    "holdEffect": "NONE"
  },
  "ITEM_BICYCLE": {
    "english": "BICYCLE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A folding bicycle that allows\\nfaster movement than the RUNNING\\nSHOES.",
    "holdEffect": "NONE"
  },
  "ITEM_TOWN_MAP": {
    "english": "TOWN MAP",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A very convenient map that can be\\nviewed anytime. It even shows your \\npresent location.",
    "holdEffect": "NONE"
  },
  "ITEM_VS_SEEKER": {
    "english": "VS SEEKER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A device that indicates TRAINERS\\nwho want to battle. The battery\\ncharges while traveling.",
    "holdEffect": "NONE"
  },
  "ITEM_FAME_CHECKER": {
    "english": "FAME CHECKER",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A device that enables you to\\nrecall what you've heard and seen\\nabout famous people.",
    "holdEffect": "NONE"
  },
  "ITEM_TM_CASE": {
    "english": "TM CASE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A case that holds TMs and HMs.\\nIt is attached to the BAG's\\ncompartment for important items.",
    "holdEffect": "NONE"
  },
  "ITEM_BERRY_POUCH": {
    "english": "BERRY POUCH",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A pouch for carrying BERRIES.\\nIt is attached to the BAG's\\ncompartment for important items.",
    "holdEffect": "NONE"
  },
  "ITEM_TEACHY_TV": {
    "english": "TEACHY TV",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A television set that is tuned to\\na program with useful tips for\\nnovice TRAINERS.",
    "holdEffect": "NONE"
  },
  "ITEM_TRI_PASS": {
    "english": "TRI-PASS",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A pass for ferries between ONE,\\nTWO, and THREE ISLAND.\\nIt has a drawing of three islands.",
    "holdEffect": "NONE"
  },
  "ITEM_RAINBOW_PASS": {
    "english": "RAINBOW PASS",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A pass for ferries between\\nVERMILION and the SEVII ISLANDS.\\nIt features a drawing of a rainbow.",
    "holdEffect": "NONE"
  },
  "ITEM_TEA": {
    "english": "TEA",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An aromatic tea prepared by an old\\nlady. It will slake even the worst\\nthirst.",
    "holdEffect": "NONE"
  },
  "ITEM_MYSTIC_TICKET": {
    "english": "MYSTICTICKET",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A ticket required to board the ship\\nto NAVEL ROCK.\\nIt glows with a mystic light.",
    "holdEffect": "NONE"
  },
  "ITEM_AURORA_TICKET": {
    "english": "AURORATICKET",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A ticket required to board the ship\\nto BIRTH ISLAND.\\nIt glows beautifully.",
    "holdEffect": "NONE"
  },
  "ITEM_POWDER_JAR": {
    "english": "POWDER JAR",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "A jar for storing BERRY POWDER\\nmade using a BERRY CRUSHER.",
    "holdEffect": "NONE"
  },
  "ITEM_RUBY": {
    "english": "RUBY",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An exquisitely beautiful gem that\\nhas a red glow.\\nIt symbolizes passion.",
    "holdEffect": "NONE"
  },
  "ITEM_SAPPHIRE": {
    "english": "SAPPHIRE",
    "price": 0,
    "pocket": "KEY_ITEMS",
    "description": "An exquisitely beautiful gem that\\nhas a blue glow.\\nIt symbolizes honesty.",
    "holdEffect": "NONE"
  }
};
