// AUTOGENERATED by scripts/extract-game-data.mjs — do not edit.

interface FireredSpecies {
  baseHP: number; baseAttack: number; baseDefense: number;
  baseSpeed: number; baseSpAttack: number; baseSpDefense: number;
  types: [string, string] | null;
  catchRate: number;
  expYield: number;
}
export const FIRERED_SPECIES: Record<string, FireredSpecies> = {
  "IVYSAUR": {
    "baseHP": 60,
    "baseAttack": 62,
    "baseDefense": 63,
    "baseSpeed": 60,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 141
  },
  "VENUSAUR": {
    "baseHP": 80,
    "baseAttack": 82,
    "baseDefense": 83,
    "baseSpeed": 80,
    "baseSpAttack": 100,
    "baseSpDefense": 100,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 208
  },
  "CHARMANDER": {
    "baseHP": 39,
    "baseAttack": 52,
    "baseDefense": 43,
    "baseSpeed": 65,
    "baseSpAttack": 60,
    "baseSpDefense": 50,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 65
  },
  "CHARMELEON": {
    "baseHP": 58,
    "baseAttack": 64,
    "baseDefense": 58,
    "baseSpeed": 80,
    "baseSpAttack": 80,
    "baseSpDefense": 65,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 142
  },
  "CHARIZARD": {
    "baseHP": 78,
    "baseAttack": 84,
    "baseDefense": 78,
    "baseSpeed": 100,
    "baseSpAttack": 109,
    "baseSpDefense": 85,
    "types": [
      "FIRE",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 209
  },
  "SQUIRTLE": {
    "baseHP": 44,
    "baseAttack": 48,
    "baseDefense": 65,
    "baseSpeed": 43,
    "baseSpAttack": 50,
    "baseSpDefense": 64,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 66
  },
  "WARTORTLE": {
    "baseHP": 59,
    "baseAttack": 63,
    "baseDefense": 80,
    "baseSpeed": 58,
    "baseSpAttack": 65,
    "baseSpDefense": 80,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 143
  },
  "BLASTOISE": {
    "baseHP": 79,
    "baseAttack": 83,
    "baseDefense": 100,
    "baseSpeed": 78,
    "baseSpAttack": 85,
    "baseSpDefense": 105,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 210
  },
  "CATERPIE": {
    "baseHP": 45,
    "baseAttack": 30,
    "baseDefense": 35,
    "baseSpeed": 45,
    "baseSpAttack": 20,
    "baseSpDefense": 20,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 255,
    "expYield": 53
  },
  "METAPOD": {
    "baseHP": 50,
    "baseAttack": 20,
    "baseDefense": 55,
    "baseSpeed": 30,
    "baseSpAttack": 25,
    "baseSpDefense": 25,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 120,
    "expYield": 72
  },
  "BUTTERFREE": {
    "baseHP": 60,
    "baseAttack": 45,
    "baseDefense": 50,
    "baseSpeed": 70,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 160
  },
  "WEEDLE": {
    "baseHP": 40,
    "baseAttack": 35,
    "baseDefense": 30,
    "baseSpeed": 50,
    "baseSpAttack": 20,
    "baseSpDefense": 20,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 255,
    "expYield": 52
  },
  "KAKUNA": {
    "baseHP": 45,
    "baseAttack": 25,
    "baseDefense": 50,
    "baseSpeed": 35,
    "baseSpAttack": 25,
    "baseSpDefense": 25,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 120,
    "expYield": 71
  },
  "BEEDRILL": {
    "baseHP": 65,
    "baseAttack": 80,
    "baseDefense": 40,
    "baseSpeed": 75,
    "baseSpAttack": 45,
    "baseSpDefense": 80,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 159
  },
  "PIDGEY": {
    "baseHP": 40,
    "baseAttack": 45,
    "baseDefense": 40,
    "baseSpeed": 56,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 55
  },
  "PIDGEOTTO": {
    "baseHP": 63,
    "baseAttack": 60,
    "baseDefense": 55,
    "baseSpeed": 71,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 120,
    "expYield": 113
  },
  "PIDGEOT": {
    "baseHP": 83,
    "baseAttack": 80,
    "baseDefense": 75,
    "baseSpeed": 91,
    "baseSpAttack": 70,
    "baseSpDefense": 70,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 172
  },
  "RATTATA": {
    "baseHP": 30,
    "baseAttack": 56,
    "baseDefense": 35,
    "baseSpeed": 72,
    "baseSpAttack": 25,
    "baseSpDefense": 35,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 57
  },
  "RATICATE": {
    "baseHP": 55,
    "baseAttack": 81,
    "baseDefense": 60,
    "baseSpeed": 97,
    "baseSpAttack": 50,
    "baseSpDefense": 70,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 127,
    "expYield": 116
  },
  "SPEAROW": {
    "baseHP": 40,
    "baseAttack": 60,
    "baseDefense": 30,
    "baseSpeed": 70,
    "baseSpAttack": 31,
    "baseSpDefense": 31,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 58
  },
  "FEAROW": {
    "baseHP": 65,
    "baseAttack": 90,
    "baseDefense": 65,
    "baseSpeed": 100,
    "baseSpAttack": 61,
    "baseSpDefense": 61,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 90,
    "expYield": 162
  },
  "EKANS": {
    "baseHP": 35,
    "baseAttack": 60,
    "baseDefense": 44,
    "baseSpeed": 55,
    "baseSpAttack": 40,
    "baseSpDefense": 54,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 255,
    "expYield": 62
  },
  "ARBOK": {
    "baseHP": 60,
    "baseAttack": 85,
    "baseDefense": 69,
    "baseSpeed": 80,
    "baseSpAttack": 65,
    "baseSpDefense": 79,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 90,
    "expYield": 147
  },
  "PIKACHU": {
    "baseHP": 35,
    "baseAttack": 55,
    "baseDefense": 30,
    "baseSpeed": 90,
    "baseSpAttack": 50,
    "baseSpDefense": 40,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 190,
    "expYield": 82
  },
  "RAICHU": {
    "baseHP": 60,
    "baseAttack": 90,
    "baseDefense": 55,
    "baseSpeed": 100,
    "baseSpAttack": 90,
    "baseSpDefense": 80,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 75,
    "expYield": 122
  },
  "SANDSHREW": {
    "baseHP": 50,
    "baseAttack": 75,
    "baseDefense": 85,
    "baseSpeed": 40,
    "baseSpAttack": 20,
    "baseSpDefense": 30,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 93
  },
  "SANDSLASH": {
    "baseHP": 75,
    "baseAttack": 100,
    "baseDefense": 110,
    "baseSpeed": 65,
    "baseSpAttack": 45,
    "baseSpDefense": 55,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 90,
    "expYield": 163
  },
  "NIDORAN_F": {
    "baseHP": 55,
    "baseAttack": 47,
    "baseDefense": 52,
    "baseSpeed": 41,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 235,
    "expYield": 59
  },
  "NIDORINA": {
    "baseHP": 70,
    "baseAttack": 62,
    "baseDefense": 67,
    "baseSpeed": 56,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 120,
    "expYield": 117
  },
  "NIDOQUEEN": {
    "baseHP": 90,
    "baseAttack": 82,
    "baseDefense": 87,
    "baseSpeed": 76,
    "baseSpAttack": 75,
    "baseSpDefense": 85,
    "types": [
      "POISON",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 194
  },
  "NIDORAN_M": {
    "baseHP": 46,
    "baseAttack": 57,
    "baseDefense": 40,
    "baseSpeed": 50,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 235,
    "expYield": 60
  },
  "NIDORINO": {
    "baseHP": 61,
    "baseAttack": 72,
    "baseDefense": 57,
    "baseSpeed": 65,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 120,
    "expYield": 118
  },
  "NIDOKING": {
    "baseHP": 81,
    "baseAttack": 92,
    "baseDefense": 77,
    "baseSpeed": 85,
    "baseSpAttack": 85,
    "baseSpDefense": 75,
    "types": [
      "POISON",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 195
  },
  "CLEFAIRY": {
    "baseHP": 70,
    "baseAttack": 45,
    "baseDefense": 48,
    "baseSpeed": 35,
    "baseSpAttack": 60,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 150,
    "expYield": 68
  },
  "CLEFABLE": {
    "baseHP": 95,
    "baseAttack": 70,
    "baseDefense": 73,
    "baseSpeed": 60,
    "baseSpAttack": 85,
    "baseSpDefense": 90,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 25,
    "expYield": 129
  },
  "VULPIX": {
    "baseHP": 38,
    "baseAttack": 41,
    "baseDefense": 40,
    "baseSpeed": 65,
    "baseSpAttack": 50,
    "baseSpDefense": 65,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 190,
    "expYield": 63
  },
  "NINETALES": {
    "baseHP": 73,
    "baseAttack": 76,
    "baseDefense": 75,
    "baseSpeed": 100,
    "baseSpAttack": 81,
    "baseSpDefense": 100,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 75,
    "expYield": 178
  },
  "JIGGLYPUFF": {
    "baseHP": 115,
    "baseAttack": 45,
    "baseDefense": 20,
    "baseSpeed": 20,
    "baseSpAttack": 45,
    "baseSpDefense": 25,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 170,
    "expYield": 76
  },
  "WIGGLYTUFF": {
    "baseHP": 140,
    "baseAttack": 70,
    "baseDefense": 45,
    "baseSpeed": 45,
    "baseSpAttack": 75,
    "baseSpDefense": 50,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 50,
    "expYield": 109
  },
  "ZUBAT": {
    "baseHP": 40,
    "baseAttack": 45,
    "baseDefense": 35,
    "baseSpeed": 55,
    "baseSpAttack": 30,
    "baseSpDefense": 40,
    "types": [
      "POISON",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 54
  },
  "GOLBAT": {
    "baseHP": 75,
    "baseAttack": 80,
    "baseDefense": 70,
    "baseSpeed": 90,
    "baseSpAttack": 65,
    "baseSpDefense": 75,
    "types": [
      "POISON",
      "FLYING"
    ],
    "catchRate": 90,
    "expYield": 171
  },
  "ODDISH": {
    "baseHP": 45,
    "baseAttack": 50,
    "baseDefense": 55,
    "baseSpeed": 30,
    "baseSpAttack": 75,
    "baseSpDefense": 65,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 255,
    "expYield": 78
  },
  "GLOOM": {
    "baseHP": 60,
    "baseAttack": 65,
    "baseDefense": 70,
    "baseSpeed": 40,
    "baseSpAttack": 85,
    "baseSpDefense": 75,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 120,
    "expYield": 132
  },
  "VILEPLUME": {
    "baseHP": 75,
    "baseAttack": 80,
    "baseDefense": 85,
    "baseSpeed": 50,
    "baseSpAttack": 100,
    "baseSpDefense": 90,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 184
  },
  "PARAS": {
    "baseHP": 35,
    "baseAttack": 70,
    "baseDefense": 55,
    "baseSpeed": 25,
    "baseSpAttack": 45,
    "baseSpDefense": 55,
    "types": [
      "BUG",
      "GRASS"
    ],
    "catchRate": 190,
    "expYield": 70
  },
  "PARASECT": {
    "baseHP": 60,
    "baseAttack": 95,
    "baseDefense": 80,
    "baseSpeed": 30,
    "baseSpAttack": 60,
    "baseSpDefense": 80,
    "types": [
      "BUG",
      "GRASS"
    ],
    "catchRate": 75,
    "expYield": 128
  },
  "VENONAT": {
    "baseHP": 60,
    "baseAttack": 55,
    "baseDefense": 50,
    "baseSpeed": 45,
    "baseSpAttack": 40,
    "baseSpDefense": 55,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 190,
    "expYield": 75
  },
  "VENOMOTH": {
    "baseHP": 70,
    "baseAttack": 65,
    "baseDefense": 60,
    "baseSpeed": 90,
    "baseSpAttack": 90,
    "baseSpDefense": 75,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 75,
    "expYield": 138
  },
  "DIGLETT": {
    "baseHP": 10,
    "baseAttack": 55,
    "baseDefense": 25,
    "baseSpeed": 95,
    "baseSpAttack": 35,
    "baseSpDefense": 45,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 81
  },
  "DUGTRIO": {
    "baseHP": 35,
    "baseAttack": 80,
    "baseDefense": 50,
    "baseSpeed": 120,
    "baseSpAttack": 50,
    "baseSpDefense": 70,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 50,
    "expYield": 153
  },
  "MEOWTH": {
    "baseHP": 40,
    "baseAttack": 45,
    "baseDefense": 35,
    "baseSpeed": 90,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 69
  },
  "PERSIAN": {
    "baseHP": 65,
    "baseAttack": 70,
    "baseDefense": 60,
    "baseSpeed": 115,
    "baseSpAttack": 65,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 90,
    "expYield": 148
  },
  "PSYDUCK": {
    "baseHP": 50,
    "baseAttack": 52,
    "baseDefense": 48,
    "baseSpeed": 55,
    "baseSpAttack": 65,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 190,
    "expYield": 80
  },
  "GOLDUCK": {
    "baseHP": 80,
    "baseAttack": 82,
    "baseDefense": 78,
    "baseSpeed": 85,
    "baseSpAttack": 95,
    "baseSpDefense": 80,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 75,
    "expYield": 174
  },
  "MANKEY": {
    "baseHP": 40,
    "baseAttack": 80,
    "baseDefense": 35,
    "baseSpeed": 70,
    "baseSpAttack": 35,
    "baseSpDefense": 45,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 190,
    "expYield": 74
  },
  "PRIMEAPE": {
    "baseHP": 65,
    "baseAttack": 105,
    "baseDefense": 60,
    "baseSpeed": 95,
    "baseSpAttack": 60,
    "baseSpDefense": 70,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 75,
    "expYield": 149
  },
  "GROWLITHE": {
    "baseHP": 55,
    "baseAttack": 70,
    "baseDefense": 45,
    "baseSpeed": 60,
    "baseSpAttack": 70,
    "baseSpDefense": 50,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 190,
    "expYield": 91
  },
  "ARCANINE": {
    "baseHP": 90,
    "baseAttack": 110,
    "baseDefense": 80,
    "baseSpeed": 95,
    "baseSpAttack": 100,
    "baseSpDefense": 80,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 75,
    "expYield": 213
  },
  "POLIWAG": {
    "baseHP": 40,
    "baseAttack": 50,
    "baseDefense": 40,
    "baseSpeed": 90,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 255,
    "expYield": 77
  },
  "POLIWHIRL": {
    "baseHP": 65,
    "baseAttack": 65,
    "baseDefense": 65,
    "baseSpeed": 90,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 120,
    "expYield": 131
  },
  "POLIWRATH": {
    "baseHP": 90,
    "baseAttack": 85,
    "baseDefense": 95,
    "baseSpeed": 70,
    "baseSpAttack": 70,
    "baseSpDefense": 90,
    "types": [
      "WATER",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 185
  },
  "ABRA": {
    "baseHP": 25,
    "baseAttack": 20,
    "baseDefense": 15,
    "baseSpeed": 90,
    "baseSpAttack": 105,
    "baseSpDefense": 55,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 200,
    "expYield": 73
  },
  "KADABRA": {
    "baseHP": 40,
    "baseAttack": 35,
    "baseDefense": 30,
    "baseSpeed": 105,
    "baseSpAttack": 120,
    "baseSpDefense": 70,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 100,
    "expYield": 145
  },
  "ALAKAZAM": {
    "baseHP": 55,
    "baseAttack": 50,
    "baseDefense": 45,
    "baseSpeed": 120,
    "baseSpAttack": 135,
    "baseSpDefense": 85,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 50,
    "expYield": 186
  },
  "MACHOP": {
    "baseHP": 70,
    "baseAttack": 80,
    "baseDefense": 50,
    "baseSpeed": 35,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 180,
    "expYield": 88
  },
  "MACHOKE": {
    "baseHP": 80,
    "baseAttack": 100,
    "baseDefense": 70,
    "baseSpeed": 45,
    "baseSpAttack": 50,
    "baseSpDefense": 60,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 90,
    "expYield": 146
  },
  "MACHAMP": {
    "baseHP": 90,
    "baseAttack": 130,
    "baseDefense": 80,
    "baseSpeed": 55,
    "baseSpAttack": 65,
    "baseSpDefense": 85,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 193
  },
  "BELLSPROUT": {
    "baseHP": 50,
    "baseAttack": 75,
    "baseDefense": 35,
    "baseSpeed": 40,
    "baseSpAttack": 70,
    "baseSpDefense": 30,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 255,
    "expYield": 84
  },
  "WEEPINBELL": {
    "baseHP": 65,
    "baseAttack": 90,
    "baseDefense": 50,
    "baseSpeed": 55,
    "baseSpAttack": 85,
    "baseSpDefense": 45,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 120,
    "expYield": 151
  },
  "VICTREEBEL": {
    "baseHP": 80,
    "baseAttack": 105,
    "baseDefense": 65,
    "baseSpeed": 70,
    "baseSpAttack": 100,
    "baseSpDefense": 60,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 191
  },
  "TENTACOOL": {
    "baseHP": 40,
    "baseAttack": 40,
    "baseDefense": 35,
    "baseSpeed": 70,
    "baseSpAttack": 50,
    "baseSpDefense": 100,
    "types": [
      "WATER",
      "POISON"
    ],
    "catchRate": 190,
    "expYield": 105
  },
  "TENTACRUEL": {
    "baseHP": 80,
    "baseAttack": 70,
    "baseDefense": 65,
    "baseSpeed": 100,
    "baseSpAttack": 80,
    "baseSpDefense": 120,
    "types": [
      "WATER",
      "POISON"
    ],
    "catchRate": 60,
    "expYield": 205
  },
  "GEODUDE": {
    "baseHP": 40,
    "baseAttack": 80,
    "baseDefense": 100,
    "baseSpeed": 20,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "ROCK",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 86
  },
  "GRAVELER": {
    "baseHP": 55,
    "baseAttack": 95,
    "baseDefense": 115,
    "baseSpeed": 35,
    "baseSpAttack": 45,
    "baseSpDefense": 45,
    "types": [
      "ROCK",
      "GROUND"
    ],
    "catchRate": 120,
    "expYield": 134
  },
  "GOLEM": {
    "baseHP": 80,
    "baseAttack": 110,
    "baseDefense": 130,
    "baseSpeed": 45,
    "baseSpAttack": 55,
    "baseSpDefense": 65,
    "types": [
      "ROCK",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 177
  },
  "PONYTA": {
    "baseHP": 50,
    "baseAttack": 85,
    "baseDefense": 55,
    "baseSpeed": 90,
    "baseSpAttack": 65,
    "baseSpDefense": 65,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 190,
    "expYield": 152
  },
  "RAPIDASH": {
    "baseHP": 65,
    "baseAttack": 100,
    "baseDefense": 70,
    "baseSpeed": 105,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 60,
    "expYield": 192
  },
  "SLOWPOKE": {
    "baseHP": 90,
    "baseAttack": 65,
    "baseDefense": 65,
    "baseSpeed": 15,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "WATER",
      "PSYCHIC"
    ],
    "catchRate": 190,
    "expYield": 99
  },
  "SLOWBRO": {
    "baseHP": 95,
    "baseAttack": 75,
    "baseDefense": 110,
    "baseSpeed": 30,
    "baseSpAttack": 100,
    "baseSpDefense": 80,
    "types": [
      "WATER",
      "PSYCHIC"
    ],
    "catchRate": 75,
    "expYield": 164
  },
  "MAGNEMITE": {
    "baseHP": 25,
    "baseAttack": 35,
    "baseDefense": 70,
    "baseSpeed": 45,
    "baseSpAttack": 95,
    "baseSpDefense": 55,
    "types": [
      "ELECTRIC",
      "STEEL"
    ],
    "catchRate": 190,
    "expYield": 89
  },
  "MAGNETON": {
    "baseHP": 50,
    "baseAttack": 60,
    "baseDefense": 95,
    "baseSpeed": 70,
    "baseSpAttack": 120,
    "baseSpDefense": 70,
    "types": [
      "ELECTRIC",
      "STEEL"
    ],
    "catchRate": 60,
    "expYield": 161
  },
  "FARFETCHD": {
    "baseHP": 52,
    "baseAttack": 65,
    "baseDefense": 55,
    "baseSpeed": 60,
    "baseSpAttack": 58,
    "baseSpDefense": 62,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 94
  },
  "DODUO": {
    "baseHP": 35,
    "baseAttack": 85,
    "baseDefense": 45,
    "baseSpeed": 75,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 190,
    "expYield": 96
  },
  "DODRIO": {
    "baseHP": 60,
    "baseAttack": 110,
    "baseDefense": 70,
    "baseSpeed": 100,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 158
  },
  "SEEL": {
    "baseHP": 65,
    "baseAttack": 45,
    "baseDefense": 55,
    "baseSpeed": 45,
    "baseSpAttack": 45,
    "baseSpDefense": 70,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 190,
    "expYield": 100
  },
  "DEWGONG": {
    "baseHP": 90,
    "baseAttack": 70,
    "baseDefense": 80,
    "baseSpeed": 70,
    "baseSpAttack": 70,
    "baseSpDefense": 95,
    "types": [
      "WATER",
      "ICE"
    ],
    "catchRate": 75,
    "expYield": 176
  },
  "GRIMER": {
    "baseHP": 80,
    "baseAttack": 80,
    "baseDefense": 50,
    "baseSpeed": 25,
    "baseSpAttack": 40,
    "baseSpDefense": 50,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 190,
    "expYield": 90
  },
  "MUK": {
    "baseHP": 105,
    "baseAttack": 105,
    "baseDefense": 75,
    "baseSpeed": 50,
    "baseSpAttack": 65,
    "baseSpDefense": 100,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 75,
    "expYield": 157
  },
  "SHELLDER": {
    "baseHP": 30,
    "baseAttack": 65,
    "baseDefense": 100,
    "baseSpeed": 40,
    "baseSpAttack": 45,
    "baseSpDefense": 25,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 190,
    "expYield": 97
  },
  "CLOYSTER": {
    "baseHP": 50,
    "baseAttack": 95,
    "baseDefense": 180,
    "baseSpeed": 70,
    "baseSpAttack": 85,
    "baseSpDefense": 45,
    "types": [
      "WATER",
      "ICE"
    ],
    "catchRate": 60,
    "expYield": 203
  },
  "GASTLY": {
    "baseHP": 30,
    "baseAttack": 35,
    "baseDefense": 30,
    "baseSpeed": 80,
    "baseSpAttack": 100,
    "baseSpDefense": 35,
    "types": [
      "GHOST",
      "POISON"
    ],
    "catchRate": 190,
    "expYield": 95
  },
  "HAUNTER": {
    "baseHP": 45,
    "baseAttack": 50,
    "baseDefense": 45,
    "baseSpeed": 95,
    "baseSpAttack": 115,
    "baseSpDefense": 55,
    "types": [
      "GHOST",
      "POISON"
    ],
    "catchRate": 90,
    "expYield": 126
  },
  "GENGAR": {
    "baseHP": 60,
    "baseAttack": 65,
    "baseDefense": 60,
    "baseSpeed": 110,
    "baseSpAttack": 130,
    "baseSpDefense": 75,
    "types": [
      "GHOST",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 190
  },
  "ONIX": {
    "baseHP": 35,
    "baseAttack": 45,
    "baseDefense": 160,
    "baseSpeed": 70,
    "baseSpAttack": 30,
    "baseSpDefense": 45,
    "types": [
      "ROCK",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 108
  },
  "DROWZEE": {
    "baseHP": 60,
    "baseAttack": 48,
    "baseDefense": 45,
    "baseSpeed": 42,
    "baseSpAttack": 43,
    "baseSpDefense": 90,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 190,
    "expYield": 102
  },
  "HYPNO": {
    "baseHP": 85,
    "baseAttack": 73,
    "baseDefense": 70,
    "baseSpeed": 67,
    "baseSpAttack": 73,
    "baseSpDefense": 115,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 75,
    "expYield": 165
  },
  "KRABBY": {
    "baseHP": 30,
    "baseAttack": 105,
    "baseDefense": 90,
    "baseSpeed": 50,
    "baseSpAttack": 25,
    "baseSpDefense": 25,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 225,
    "expYield": 115
  },
  "KINGLER": {
    "baseHP": 55,
    "baseAttack": 130,
    "baseDefense": 115,
    "baseSpeed": 75,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 60,
    "expYield": 206
  },
  "VOLTORB": {
    "baseHP": 40,
    "baseAttack": 30,
    "baseDefense": 50,
    "baseSpeed": 100,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 190,
    "expYield": 103
  },
  "ELECTRODE": {
    "baseHP": 60,
    "baseAttack": 50,
    "baseDefense": 70,
    "baseSpeed": 140,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 60,
    "expYield": 150
  },
  "EXEGGCUTE": {
    "baseHP": 60,
    "baseAttack": 40,
    "baseDefense": 80,
    "baseSpeed": 40,
    "baseSpAttack": 60,
    "baseSpDefense": 45,
    "types": [
      "GRASS",
      "PSYCHIC"
    ],
    "catchRate": 90,
    "expYield": 98
  },
  "EXEGGUTOR": {
    "baseHP": 95,
    "baseAttack": 95,
    "baseDefense": 85,
    "baseSpeed": 55,
    "baseSpAttack": 125,
    "baseSpDefense": 65,
    "types": [
      "GRASS",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 212
  },
  "CUBONE": {
    "baseHP": 50,
    "baseAttack": 50,
    "baseDefense": 95,
    "baseSpeed": 35,
    "baseSpAttack": 40,
    "baseSpDefense": 50,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 190,
    "expYield": 87
  },
  "MAROWAK": {
    "baseHP": 60,
    "baseAttack": 80,
    "baseDefense": 110,
    "baseSpeed": 45,
    "baseSpAttack": 50,
    "baseSpDefense": 80,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 75,
    "expYield": 124
  },
  "HITMONLEE": {
    "baseHP": 50,
    "baseAttack": 120,
    "baseDefense": 53,
    "baseSpeed": 87,
    "baseSpAttack": 35,
    "baseSpDefense": 110,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 139
  },
  "HITMONCHAN": {
    "baseHP": 50,
    "baseAttack": 105,
    "baseDefense": 79,
    "baseSpeed": 76,
    "baseSpAttack": 35,
    "baseSpDefense": 110,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 140
  },
  "LICKITUNG": {
    "baseHP": 90,
    "baseAttack": 55,
    "baseDefense": 75,
    "baseSpeed": 30,
    "baseSpAttack": 60,
    "baseSpDefense": 75,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 127
  },
  "KOFFING": {
    "baseHP": 40,
    "baseAttack": 65,
    "baseDefense": 95,
    "baseSpeed": 35,
    "baseSpAttack": 60,
    "baseSpDefense": 45,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 190,
    "expYield": 114
  },
  "WEEZING": {
    "baseHP": 65,
    "baseAttack": 90,
    "baseDefense": 120,
    "baseSpeed": 60,
    "baseSpAttack": 85,
    "baseSpDefense": 70,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 60,
    "expYield": 173
  },
  "RHYHORN": {
    "baseHP": 80,
    "baseAttack": 85,
    "baseDefense": 95,
    "baseSpeed": 25,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "GROUND",
      "ROCK"
    ],
    "catchRate": 120,
    "expYield": 135
  },
  "RHYDON": {
    "baseHP": 105,
    "baseAttack": 130,
    "baseDefense": 120,
    "baseSpeed": 40,
    "baseSpAttack": 45,
    "baseSpDefense": 45,
    "types": [
      "GROUND",
      "ROCK"
    ],
    "catchRate": 60,
    "expYield": 204
  },
  "CHANSEY": {
    "baseHP": 250,
    "baseAttack": 5,
    "baseDefense": 5,
    "baseSpeed": 50,
    "baseSpAttack": 35,
    "baseSpDefense": 105,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 30,
    "expYield": 255
  },
  "TANGELA": {
    "baseHP": 65,
    "baseAttack": 55,
    "baseDefense": 115,
    "baseSpeed": 60,
    "baseSpAttack": 100,
    "baseSpDefense": 40,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 166
  },
  "KANGASKHAN": {
    "baseHP": 105,
    "baseAttack": 95,
    "baseDefense": 80,
    "baseSpeed": 90,
    "baseSpAttack": 40,
    "baseSpDefense": 80,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 175
  },
  "HORSEA": {
    "baseHP": 30,
    "baseAttack": 40,
    "baseDefense": 70,
    "baseSpeed": 60,
    "baseSpAttack": 70,
    "baseSpDefense": 25,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 225,
    "expYield": 83
  },
  "SEADRA": {
    "baseHP": 55,
    "baseAttack": 65,
    "baseDefense": 95,
    "baseSpeed": 85,
    "baseSpAttack": 95,
    "baseSpDefense": 45,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 75,
    "expYield": 155
  },
  "GOLDEEN": {
    "baseHP": 45,
    "baseAttack": 67,
    "baseDefense": 60,
    "baseSpeed": 63,
    "baseSpAttack": 35,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 225,
    "expYield": 111
  },
  "SEAKING": {
    "baseHP": 80,
    "baseAttack": 92,
    "baseDefense": 65,
    "baseSpeed": 68,
    "baseSpAttack": 65,
    "baseSpDefense": 80,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 60,
    "expYield": 170
  },
  "STARYU": {
    "baseHP": 30,
    "baseAttack": 45,
    "baseDefense": 55,
    "baseSpeed": 85,
    "baseSpAttack": 70,
    "baseSpDefense": 55,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 225,
    "expYield": 106
  },
  "STARMIE": {
    "baseHP": 60,
    "baseAttack": 75,
    "baseDefense": 85,
    "baseSpeed": 115,
    "baseSpAttack": 100,
    "baseSpDefense": 85,
    "types": [
      "WATER",
      "PSYCHIC"
    ],
    "catchRate": 60,
    "expYield": 207
  },
  "MR_MIME": {
    "baseHP": 40,
    "baseAttack": 45,
    "baseDefense": 65,
    "baseSpeed": 90,
    "baseSpAttack": 100,
    "baseSpDefense": 120,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 136
  },
  "SCYTHER": {
    "baseHP": 70,
    "baseAttack": 110,
    "baseDefense": 80,
    "baseSpeed": 105,
    "baseSpAttack": 55,
    "baseSpDefense": 80,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 187
  },
  "JYNX": {
    "baseHP": 65,
    "baseAttack": 50,
    "baseDefense": 35,
    "baseSpeed": 95,
    "baseSpAttack": 115,
    "baseSpDefense": 95,
    "types": [
      "ICE",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 137
  },
  "ELECTABUZZ": {
    "baseHP": 65,
    "baseAttack": 83,
    "baseDefense": 57,
    "baseSpeed": 105,
    "baseSpAttack": 95,
    "baseSpDefense": 85,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 45,
    "expYield": 156
  },
  "MAGMAR": {
    "baseHP": 65,
    "baseAttack": 95,
    "baseDefense": 57,
    "baseSpeed": 93,
    "baseSpAttack": 100,
    "baseSpDefense": 85,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 167
  },
  "PINSIR": {
    "baseHP": 65,
    "baseAttack": 125,
    "baseDefense": 100,
    "baseSpeed": 85,
    "baseSpAttack": 55,
    "baseSpDefense": 70,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 45,
    "expYield": 200
  },
  "TAUROS": {
    "baseHP": 75,
    "baseAttack": 100,
    "baseDefense": 95,
    "baseSpeed": 110,
    "baseSpAttack": 40,
    "baseSpDefense": 70,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 211
  },
  "MAGIKARP": {
    "baseHP": 20,
    "baseAttack": 10,
    "baseDefense": 55,
    "baseSpeed": 80,
    "baseSpAttack": 15,
    "baseSpDefense": 20,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 255,
    "expYield": 20
  },
  "GYARADOS": {
    "baseHP": 95,
    "baseAttack": 125,
    "baseDefense": 79,
    "baseSpeed": 81,
    "baseSpAttack": 60,
    "baseSpDefense": 100,
    "types": [
      "WATER",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 214
  },
  "LAPRAS": {
    "baseHP": 130,
    "baseAttack": 85,
    "baseDefense": 80,
    "baseSpeed": 60,
    "baseSpAttack": 85,
    "baseSpDefense": 95,
    "types": [
      "WATER",
      "ICE"
    ],
    "catchRate": 45,
    "expYield": 219
  },
  "DITTO": {
    "baseHP": 48,
    "baseAttack": 48,
    "baseDefense": 48,
    "baseSpeed": 48,
    "baseSpAttack": 48,
    "baseSpDefense": 48,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 35,
    "expYield": 61
  },
  "EEVEE": {
    "baseHP": 55,
    "baseAttack": 55,
    "baseDefense": 50,
    "baseSpeed": 55,
    "baseSpAttack": 45,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 92
  },
  "VAPOREON": {
    "baseHP": 130,
    "baseAttack": 65,
    "baseDefense": 60,
    "baseSpeed": 65,
    "baseSpAttack": 110,
    "baseSpDefense": 95,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 196
  },
  "JOLTEON": {
    "baseHP": 65,
    "baseAttack": 65,
    "baseDefense": 60,
    "baseSpeed": 130,
    "baseSpAttack": 110,
    "baseSpDefense": 95,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 45,
    "expYield": 197
  },
  "FLAREON": {
    "baseHP": 65,
    "baseAttack": 130,
    "baseDefense": 60,
    "baseSpeed": 65,
    "baseSpAttack": 95,
    "baseSpDefense": 110,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 198
  },
  "PORYGON": {
    "baseHP": 65,
    "baseAttack": 60,
    "baseDefense": 70,
    "baseSpeed": 40,
    "baseSpAttack": 85,
    "baseSpDefense": 75,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 130
  },
  "OMANYTE": {
    "baseHP": 35,
    "baseAttack": 40,
    "baseDefense": 100,
    "baseSpeed": 35,
    "baseSpAttack": 90,
    "baseSpDefense": 55,
    "types": [
      "ROCK",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 120
  },
  "OMASTAR": {
    "baseHP": 70,
    "baseAttack": 60,
    "baseDefense": 125,
    "baseSpeed": 55,
    "baseSpAttack": 115,
    "baseSpDefense": 70,
    "types": [
      "ROCK",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 199
  },
  "KABUTO": {
    "baseHP": 30,
    "baseAttack": 80,
    "baseDefense": 90,
    "baseSpeed": 55,
    "baseSpAttack": 55,
    "baseSpDefense": 45,
    "types": [
      "ROCK",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 119
  },
  "KABUTOPS": {
    "baseHP": 60,
    "baseAttack": 115,
    "baseDefense": 105,
    "baseSpeed": 80,
    "baseSpAttack": 65,
    "baseSpDefense": 70,
    "types": [
      "ROCK",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 201
  },
  "AERODACTYL": {
    "baseHP": 80,
    "baseAttack": 105,
    "baseDefense": 65,
    "baseSpeed": 130,
    "baseSpAttack": 60,
    "baseSpDefense": 75,
    "types": [
      "ROCK",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 202
  },
  "SNORLAX": {
    "baseHP": 160,
    "baseAttack": 110,
    "baseDefense": 65,
    "baseSpeed": 30,
    "baseSpAttack": 65,
    "baseSpDefense": 110,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 25,
    "expYield": 154
  },
  "ARTICUNO": {
    "baseHP": 90,
    "baseAttack": 85,
    "baseDefense": 100,
    "baseSpeed": 85,
    "baseSpAttack": 95,
    "baseSpDefense": 125,
    "types": [
      "ICE",
      "FLYING"
    ],
    "catchRate": 3,
    "expYield": 215
  },
  "ZAPDOS": {
    "baseHP": 90,
    "baseAttack": 90,
    "baseDefense": 85,
    "baseSpeed": 100,
    "baseSpAttack": 125,
    "baseSpDefense": 90,
    "types": [
      "ELECTRIC",
      "FLYING"
    ],
    "catchRate": 3,
    "expYield": 216
  },
  "MOLTRES": {
    "baseHP": 90,
    "baseAttack": 100,
    "baseDefense": 90,
    "baseSpeed": 90,
    "baseSpAttack": 125,
    "baseSpDefense": 85,
    "types": [
      "FIRE",
      "FLYING"
    ],
    "catchRate": 3,
    "expYield": 217
  },
  "DRATINI": {
    "baseHP": 41,
    "baseAttack": 64,
    "baseDefense": 45,
    "baseSpeed": 50,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "DRAGON",
      "DRAGON"
    ],
    "catchRate": 45,
    "expYield": 67
  },
  "DRAGONAIR": {
    "baseHP": 61,
    "baseAttack": 84,
    "baseDefense": 65,
    "baseSpeed": 70,
    "baseSpAttack": 70,
    "baseSpDefense": 70,
    "types": [
      "DRAGON",
      "DRAGON"
    ],
    "catchRate": 45,
    "expYield": 144
  },
  "DRAGONITE": {
    "baseHP": 91,
    "baseAttack": 134,
    "baseDefense": 95,
    "baseSpeed": 80,
    "baseSpAttack": 100,
    "baseSpDefense": 100,
    "types": [
      "DRAGON",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 218
  },
  "MEWTWO": {
    "baseHP": 106,
    "baseAttack": 110,
    "baseDefense": 90,
    "baseSpeed": 130,
    "baseSpAttack": 154,
    "baseSpDefense": 90,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 220
  },
  "MEW": {
    "baseHP": 100,
    "baseAttack": 100,
    "baseDefense": 100,
    "baseSpeed": 100,
    "baseSpAttack": 100,
    "baseSpDefense": 100,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 64
  },
  "CHIKORITA": {
    "baseHP": 45,
    "baseAttack": 49,
    "baseDefense": 65,
    "baseSpeed": 45,
    "baseSpAttack": 49,
    "baseSpDefense": 65,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 64
  },
  "BAYLEEF": {
    "baseHP": 60,
    "baseAttack": 62,
    "baseDefense": 80,
    "baseSpeed": 60,
    "baseSpAttack": 63,
    "baseSpDefense": 80,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 141
  },
  "MEGANIUM": {
    "baseHP": 80,
    "baseAttack": 82,
    "baseDefense": 100,
    "baseSpeed": 80,
    "baseSpAttack": 83,
    "baseSpDefense": 100,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 208
  },
  "CYNDAQUIL": {
    "baseHP": 39,
    "baseAttack": 52,
    "baseDefense": 43,
    "baseSpeed": 65,
    "baseSpAttack": 60,
    "baseSpDefense": 50,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 65
  },
  "QUILAVA": {
    "baseHP": 58,
    "baseAttack": 64,
    "baseDefense": 58,
    "baseSpeed": 80,
    "baseSpAttack": 80,
    "baseSpDefense": 65,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 142
  },
  "TYPHLOSION": {
    "baseHP": 78,
    "baseAttack": 84,
    "baseDefense": 78,
    "baseSpeed": 100,
    "baseSpAttack": 109,
    "baseSpDefense": 85,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 209
  },
  "TOTODILE": {
    "baseHP": 50,
    "baseAttack": 65,
    "baseDefense": 64,
    "baseSpeed": 43,
    "baseSpAttack": 44,
    "baseSpDefense": 48,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 66
  },
  "CROCONAW": {
    "baseHP": 65,
    "baseAttack": 80,
    "baseDefense": 80,
    "baseSpeed": 58,
    "baseSpAttack": 59,
    "baseSpDefense": 63,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 143
  },
  "FERALIGATR": {
    "baseHP": 85,
    "baseAttack": 105,
    "baseDefense": 100,
    "baseSpeed": 78,
    "baseSpAttack": 79,
    "baseSpDefense": 83,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 210
  },
  "SENTRET": {
    "baseHP": 35,
    "baseAttack": 46,
    "baseDefense": 34,
    "baseSpeed": 20,
    "baseSpAttack": 35,
    "baseSpDefense": 45,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 57
  },
  "FURRET": {
    "baseHP": 85,
    "baseAttack": 76,
    "baseDefense": 64,
    "baseSpeed": 90,
    "baseSpAttack": 45,
    "baseSpDefense": 55,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 90,
    "expYield": 116
  },
  "HOOTHOOT": {
    "baseHP": 60,
    "baseAttack": 30,
    "baseDefense": 30,
    "baseSpeed": 50,
    "baseSpAttack": 36,
    "baseSpDefense": 56,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 58
  },
  "NOCTOWL": {
    "baseHP": 100,
    "baseAttack": 50,
    "baseDefense": 50,
    "baseSpeed": 70,
    "baseSpAttack": 76,
    "baseSpDefense": 96,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 90,
    "expYield": 162
  },
  "LEDYBA": {
    "baseHP": 40,
    "baseAttack": 20,
    "baseDefense": 30,
    "baseSpeed": 55,
    "baseSpAttack": 40,
    "baseSpDefense": 80,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 54
  },
  "LEDIAN": {
    "baseHP": 55,
    "baseAttack": 35,
    "baseDefense": 50,
    "baseSpeed": 85,
    "baseSpAttack": 55,
    "baseSpDefense": 110,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 90,
    "expYield": 134
  },
  "SPINARAK": {
    "baseHP": 40,
    "baseAttack": 60,
    "baseDefense": 40,
    "baseSpeed": 30,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 255,
    "expYield": 54
  },
  "ARIADOS": {
    "baseHP": 70,
    "baseAttack": 90,
    "baseDefense": 70,
    "baseSpeed": 40,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 90,
    "expYield": 134
  },
  "CROBAT": {
    "baseHP": 85,
    "baseAttack": 90,
    "baseDefense": 80,
    "baseSpeed": 130,
    "baseSpAttack": 70,
    "baseSpDefense": 80,
    "types": [
      "POISON",
      "FLYING"
    ],
    "catchRate": 90,
    "expYield": 204
  },
  "CHINCHOU": {
    "baseHP": 75,
    "baseAttack": 38,
    "baseDefense": 38,
    "baseSpeed": 67,
    "baseSpAttack": 56,
    "baseSpDefense": 56,
    "types": [
      "WATER",
      "ELECTRIC"
    ],
    "catchRate": 190,
    "expYield": 90
  },
  "LANTURN": {
    "baseHP": 125,
    "baseAttack": 58,
    "baseDefense": 58,
    "baseSpeed": 67,
    "baseSpAttack": 76,
    "baseSpDefense": 76,
    "types": [
      "WATER",
      "ELECTRIC"
    ],
    "catchRate": 75,
    "expYield": 156
  },
  "PICHU": {
    "baseHP": 20,
    "baseAttack": 40,
    "baseDefense": 15,
    "baseSpeed": 60,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 190,
    "expYield": 42
  },
  "CLEFFA": {
    "baseHP": 50,
    "baseAttack": 25,
    "baseDefense": 28,
    "baseSpeed": 15,
    "baseSpAttack": 45,
    "baseSpDefense": 55,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 150,
    "expYield": 37
  },
  "IGGLYBUFF": {
    "baseHP": 90,
    "baseAttack": 30,
    "baseDefense": 15,
    "baseSpeed": 15,
    "baseSpAttack": 40,
    "baseSpDefense": 20,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 170,
    "expYield": 39
  },
  "TOGEPI": {
    "baseHP": 35,
    "baseAttack": 20,
    "baseDefense": 65,
    "baseSpeed": 20,
    "baseSpAttack": 40,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 190,
    "expYield": 74
  },
  "TOGETIC": {
    "baseHP": 55,
    "baseAttack": 40,
    "baseDefense": 85,
    "baseSpeed": 40,
    "baseSpAttack": 80,
    "baseSpDefense": 105,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 75,
    "expYield": 114
  },
  "NATU": {
    "baseHP": 40,
    "baseAttack": 50,
    "baseDefense": 45,
    "baseSpeed": 70,
    "baseSpAttack": 70,
    "baseSpDefense": 45,
    "types": [
      "PSYCHIC",
      "FLYING"
    ],
    "catchRate": 190,
    "expYield": 73
  },
  "XATU": {
    "baseHP": 65,
    "baseAttack": 75,
    "baseDefense": 70,
    "baseSpeed": 95,
    "baseSpAttack": 95,
    "baseSpDefense": 70,
    "types": [
      "PSYCHIC",
      "FLYING"
    ],
    "catchRate": 75,
    "expYield": 171
  },
  "MAREEP": {
    "baseHP": 55,
    "baseAttack": 40,
    "baseDefense": 40,
    "baseSpeed": 35,
    "baseSpAttack": 65,
    "baseSpDefense": 45,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 235,
    "expYield": 59
  },
  "FLAAFFY": {
    "baseHP": 70,
    "baseAttack": 55,
    "baseDefense": 55,
    "baseSpeed": 45,
    "baseSpAttack": 80,
    "baseSpDefense": 60,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 120,
    "expYield": 117
  },
  "AMPHAROS": {
    "baseHP": 90,
    "baseAttack": 75,
    "baseDefense": 75,
    "baseSpeed": 55,
    "baseSpAttack": 115,
    "baseSpDefense": 90,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 45,
    "expYield": 194
  },
  "BELLOSSOM": {
    "baseHP": 75,
    "baseAttack": 80,
    "baseDefense": 85,
    "baseSpeed": 50,
    "baseSpAttack": 90,
    "baseSpDefense": 100,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 184
  },
  "MARILL": {
    "baseHP": 70,
    "baseAttack": 20,
    "baseDefense": 50,
    "baseSpeed": 40,
    "baseSpAttack": 20,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 190,
    "expYield": 58
  },
  "AZUMARILL": {
    "baseHP": 100,
    "baseAttack": 50,
    "baseDefense": 80,
    "baseSpeed": 50,
    "baseSpAttack": 50,
    "baseSpDefense": 80,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 75,
    "expYield": 153
  },
  "SUDOWOODO": {
    "baseHP": 70,
    "baseAttack": 100,
    "baseDefense": 115,
    "baseSpeed": 30,
    "baseSpAttack": 30,
    "baseSpDefense": 65,
    "types": [
      "ROCK",
      "ROCK"
    ],
    "catchRate": 65,
    "expYield": 135
  },
  "POLITOED": {
    "baseHP": 90,
    "baseAttack": 75,
    "baseDefense": 75,
    "baseSpeed": 70,
    "baseSpAttack": 90,
    "baseSpDefense": 100,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 185
  },
  "HOPPIP": {
    "baseHP": 35,
    "baseAttack": 35,
    "baseDefense": 40,
    "baseSpeed": 50,
    "baseSpAttack": 35,
    "baseSpDefense": 55,
    "types": [
      "GRASS",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 74
  },
  "SKIPLOOM": {
    "baseHP": 55,
    "baseAttack": 45,
    "baseDefense": 50,
    "baseSpeed": 80,
    "baseSpAttack": 45,
    "baseSpDefense": 65,
    "types": [
      "GRASS",
      "FLYING"
    ],
    "catchRate": 120,
    "expYield": 136
  },
  "JUMPLUFF": {
    "baseHP": 75,
    "baseAttack": 55,
    "baseDefense": 70,
    "baseSpeed": 110,
    "baseSpAttack": 55,
    "baseSpDefense": 85,
    "types": [
      "GRASS",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 176
  },
  "AIPOM": {
    "baseHP": 55,
    "baseAttack": 70,
    "baseDefense": 55,
    "baseSpeed": 85,
    "baseSpAttack": 40,
    "baseSpDefense": 55,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 94
  },
  "SUNKERN": {
    "baseHP": 30,
    "baseAttack": 30,
    "baseDefense": 30,
    "baseSpeed": 30,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 235,
    "expYield": 52
  },
  "SUNFLORA": {
    "baseHP": 75,
    "baseAttack": 75,
    "baseDefense": 55,
    "baseSpeed": 30,
    "baseSpAttack": 105,
    "baseSpDefense": 85,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 120,
    "expYield": 146
  },
  "YANMA": {
    "baseHP": 65,
    "baseAttack": 65,
    "baseDefense": 45,
    "baseSpeed": 95,
    "baseSpAttack": 75,
    "baseSpDefense": 45,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 75,
    "expYield": 147
  },
  "WOOPER": {
    "baseHP": 55,
    "baseAttack": 45,
    "baseDefense": 45,
    "baseSpeed": 15,
    "baseSpAttack": 25,
    "baseSpDefense": 25,
    "types": [
      "WATER",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 52
  },
  "QUAGSIRE": {
    "baseHP": 95,
    "baseAttack": 85,
    "baseDefense": 85,
    "baseSpeed": 35,
    "baseSpAttack": 65,
    "baseSpDefense": 65,
    "types": [
      "WATER",
      "GROUND"
    ],
    "catchRate": 90,
    "expYield": 137
  },
  "ESPEON": {
    "baseHP": 65,
    "baseAttack": 65,
    "baseDefense": 60,
    "baseSpeed": 110,
    "baseSpAttack": 130,
    "baseSpDefense": 95,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 197
  },
  "UMBREON": {
    "baseHP": 95,
    "baseAttack": 65,
    "baseDefense": 110,
    "baseSpeed": 65,
    "baseSpAttack": 60,
    "baseSpDefense": 130,
    "types": [
      "DARK",
      "DARK"
    ],
    "catchRate": 45,
    "expYield": 197
  },
  "MURKROW": {
    "baseHP": 60,
    "baseAttack": 85,
    "baseDefense": 42,
    "baseSpeed": 91,
    "baseSpAttack": 85,
    "baseSpDefense": 42,
    "types": [
      "DARK",
      "FLYING"
    ],
    "catchRate": 30,
    "expYield": 107
  },
  "SLOWKING": {
    "baseHP": 95,
    "baseAttack": 75,
    "baseDefense": 80,
    "baseSpeed": 30,
    "baseSpAttack": 100,
    "baseSpDefense": 110,
    "types": [
      "WATER",
      "PSYCHIC"
    ],
    "catchRate": 70,
    "expYield": 164
  },
  "MISDREAVUS": {
    "baseHP": 60,
    "baseAttack": 60,
    "baseDefense": 60,
    "baseSpeed": 85,
    "baseSpAttack": 85,
    "baseSpDefense": 85,
    "types": [
      "GHOST",
      "GHOST"
    ],
    "catchRate": 45,
    "expYield": 147
  },
  "UNOWN": {
    "baseHP": 48,
    "baseAttack": 72,
    "baseDefense": 48,
    "baseSpeed": 48,
    "baseSpAttack": 72,
    "baseSpDefense": 48,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 225,
    "expYield": 61
  },
  "WOBBUFFET": {
    "baseHP": 190,
    "baseAttack": 33,
    "baseDefense": 58,
    "baseSpeed": 33,
    "baseSpAttack": 33,
    "baseSpDefense": 58,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 177
  },
  "GIRAFARIG": {
    "baseHP": 70,
    "baseAttack": 80,
    "baseDefense": 65,
    "baseSpeed": 85,
    "baseSpAttack": 90,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "PSYCHIC"
    ],
    "catchRate": 60,
    "expYield": 149
  },
  "PINECO": {
    "baseHP": 50,
    "baseAttack": 65,
    "baseDefense": 90,
    "baseSpeed": 15,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 190,
    "expYield": 60
  },
  "FORRETRESS": {
    "baseHP": 75,
    "baseAttack": 90,
    "baseDefense": 140,
    "baseSpeed": 40,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "BUG",
      "STEEL"
    ],
    "catchRate": 75,
    "expYield": 118
  },
  "DUNSPARCE": {
    "baseHP": 100,
    "baseAttack": 70,
    "baseDefense": 70,
    "baseSpeed": 45,
    "baseSpAttack": 65,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 190,
    "expYield": 75
  },
  "GLIGAR": {
    "baseHP": 65,
    "baseAttack": 75,
    "baseDefense": 105,
    "baseSpeed": 85,
    "baseSpAttack": 35,
    "baseSpDefense": 65,
    "types": [
      "GROUND",
      "FLYING"
    ],
    "catchRate": 60,
    "expYield": 108
  },
  "STEELIX": {
    "baseHP": 75,
    "baseAttack": 85,
    "baseDefense": 200,
    "baseSpeed": 30,
    "baseSpAttack": 55,
    "baseSpDefense": 65,
    "types": [
      "STEEL",
      "GROUND"
    ],
    "catchRate": 25,
    "expYield": 196
  },
  "SNUBBULL": {
    "baseHP": 60,
    "baseAttack": 80,
    "baseDefense": 50,
    "baseSpeed": 30,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 190,
    "expYield": 63
  },
  "GRANBULL": {
    "baseHP": 90,
    "baseAttack": 120,
    "baseDefense": 75,
    "baseSpeed": 45,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 75,
    "expYield": 178
  },
  "QWILFISH": {
    "baseHP": 65,
    "baseAttack": 95,
    "baseDefense": 75,
    "baseSpeed": 85,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "WATER",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 100
  },
  "SCIZOR": {
    "baseHP": 70,
    "baseAttack": 130,
    "baseDefense": 100,
    "baseSpeed": 65,
    "baseSpAttack": 55,
    "baseSpDefense": 80,
    "types": [
      "BUG",
      "STEEL"
    ],
    "catchRate": 25,
    "expYield": 200
  },
  "SHUCKLE": {
    "baseHP": 20,
    "baseAttack": 10,
    "baseDefense": 230,
    "baseSpeed": 5,
    "baseSpAttack": 10,
    "baseSpDefense": 230,
    "types": [
      "BUG",
      "ROCK"
    ],
    "catchRate": 190,
    "expYield": 80
  },
  "HERACROSS": {
    "baseHP": 80,
    "baseAttack": 125,
    "baseDefense": 75,
    "baseSpeed": 85,
    "baseSpAttack": 40,
    "baseSpDefense": 95,
    "types": [
      "BUG",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 200
  },
  "SNEASEL": {
    "baseHP": 55,
    "baseAttack": 95,
    "baseDefense": 55,
    "baseSpeed": 115,
    "baseSpAttack": 35,
    "baseSpDefense": 75,
    "types": [
      "DARK",
      "ICE"
    ],
    "catchRate": 60,
    "expYield": 132
  },
  "TEDDIURSA": {
    "baseHP": 60,
    "baseAttack": 80,
    "baseDefense": 50,
    "baseSpeed": 40,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 120,
    "expYield": 124
  },
  "URSARING": {
    "baseHP": 90,
    "baseAttack": 130,
    "baseDefense": 75,
    "baseSpeed": 55,
    "baseSpAttack": 75,
    "baseSpDefense": 75,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 60,
    "expYield": 189
  },
  "SLUGMA": {
    "baseHP": 40,
    "baseAttack": 40,
    "baseDefense": 40,
    "baseSpeed": 20,
    "baseSpAttack": 70,
    "baseSpDefense": 40,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 190,
    "expYield": 78
  },
  "MAGCARGO": {
    "baseHP": 50,
    "baseAttack": 50,
    "baseDefense": 120,
    "baseSpeed": 30,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "FIRE",
      "ROCK"
    ],
    "catchRate": 75,
    "expYield": 154
  },
  "SWINUB": {
    "baseHP": 50,
    "baseAttack": 50,
    "baseDefense": 40,
    "baseSpeed": 50,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "ICE",
      "GROUND"
    ],
    "catchRate": 225,
    "expYield": 78
  },
  "PILOSWINE": {
    "baseHP": 100,
    "baseAttack": 100,
    "baseDefense": 80,
    "baseSpeed": 50,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "ICE",
      "GROUND"
    ],
    "catchRate": 75,
    "expYield": 160
  },
  "CORSOLA": {
    "baseHP": 55,
    "baseAttack": 55,
    "baseDefense": 85,
    "baseSpeed": 35,
    "baseSpAttack": 65,
    "baseSpDefense": 85,
    "types": [
      "WATER",
      "ROCK"
    ],
    "catchRate": 60,
    "expYield": 113
  },
  "REMORAID": {
    "baseHP": 35,
    "baseAttack": 65,
    "baseDefense": 35,
    "baseSpeed": 65,
    "baseSpAttack": 65,
    "baseSpDefense": 35,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 190,
    "expYield": 78
  },
  "OCTILLERY": {
    "baseHP": 75,
    "baseAttack": 105,
    "baseDefense": 75,
    "baseSpeed": 45,
    "baseSpAttack": 105,
    "baseSpDefense": 75,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 75,
    "expYield": 164
  },
  "DELIBIRD": {
    "baseHP": 45,
    "baseAttack": 55,
    "baseDefense": 45,
    "baseSpeed": 75,
    "baseSpAttack": 65,
    "baseSpDefense": 45,
    "types": [
      "ICE",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 183
  },
  "MANTINE": {
    "baseHP": 65,
    "baseAttack": 40,
    "baseDefense": 70,
    "baseSpeed": 70,
    "baseSpAttack": 80,
    "baseSpDefense": 140,
    "types": [
      "WATER",
      "FLYING"
    ],
    "catchRate": 25,
    "expYield": 168
  },
  "SKARMORY": {
    "baseHP": 65,
    "baseAttack": 80,
    "baseDefense": 140,
    "baseSpeed": 70,
    "baseSpAttack": 40,
    "baseSpDefense": 70,
    "types": [
      "STEEL",
      "FLYING"
    ],
    "catchRate": 25,
    "expYield": 168
  },
  "HOUNDOUR": {
    "baseHP": 45,
    "baseAttack": 60,
    "baseDefense": 30,
    "baseSpeed": 65,
    "baseSpAttack": 80,
    "baseSpDefense": 50,
    "types": [
      "DARK",
      "FIRE"
    ],
    "catchRate": 120,
    "expYield": 114
  },
  "HOUNDOOM": {
    "baseHP": 75,
    "baseAttack": 90,
    "baseDefense": 50,
    "baseSpeed": 95,
    "baseSpAttack": 110,
    "baseSpDefense": 80,
    "types": [
      "DARK",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 204
  },
  "KINGDRA": {
    "baseHP": 75,
    "baseAttack": 95,
    "baseDefense": 95,
    "baseSpeed": 85,
    "baseSpAttack": 95,
    "baseSpDefense": 95,
    "types": [
      "WATER",
      "DRAGON"
    ],
    "catchRate": 45,
    "expYield": 207
  },
  "PHANPY": {
    "baseHP": 90,
    "baseAttack": 60,
    "baseDefense": 60,
    "baseSpeed": 40,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 120,
    "expYield": 124
  },
  "DONPHAN": {
    "baseHP": 90,
    "baseAttack": 120,
    "baseDefense": 120,
    "baseSpeed": 50,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 60,
    "expYield": 189
  },
  "PORYGON2": {
    "baseHP": 85,
    "baseAttack": 80,
    "baseDefense": 90,
    "baseSpeed": 60,
    "baseSpAttack": 105,
    "baseSpDefense": 95,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 180
  },
  "STANTLER": {
    "baseHP": 73,
    "baseAttack": 95,
    "baseDefense": 62,
    "baseSpeed": 85,
    "baseSpAttack": 85,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 165
  },
  "SMEARGLE": {
    "baseHP": 55,
    "baseAttack": 20,
    "baseDefense": 35,
    "baseSpeed": 75,
    "baseSpAttack": 20,
    "baseSpDefense": 45,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 106
  },
  "TYROGUE": {
    "baseHP": 35,
    "baseAttack": 35,
    "baseDefense": 35,
    "baseSpeed": 35,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 75,
    "expYield": 91
  },
  "HITMONTOP": {
    "baseHP": 50,
    "baseAttack": 95,
    "baseDefense": 95,
    "baseSpeed": 70,
    "baseSpAttack": 35,
    "baseSpDefense": 110,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 138
  },
  "SMOOCHUM": {
    "baseHP": 45,
    "baseAttack": 30,
    "baseDefense": 15,
    "baseSpeed": 65,
    "baseSpAttack": 85,
    "baseSpDefense": 65,
    "types": [
      "ICE",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 87
  },
  "ELEKID": {
    "baseHP": 45,
    "baseAttack": 63,
    "baseDefense": 37,
    "baseSpeed": 95,
    "baseSpAttack": 65,
    "baseSpDefense": 55,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 45,
    "expYield": 106
  },
  "MAGBY": {
    "baseHP": 45,
    "baseAttack": 75,
    "baseDefense": 37,
    "baseSpeed": 83,
    "baseSpAttack": 70,
    "baseSpDefense": 55,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 117
  },
  "MILTANK": {
    "baseHP": 95,
    "baseAttack": 80,
    "baseDefense": 105,
    "baseSpeed": 100,
    "baseSpAttack": 40,
    "baseSpDefense": 70,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 200
  },
  "BLISSEY": {
    "baseHP": 255,
    "baseAttack": 10,
    "baseDefense": 10,
    "baseSpeed": 55,
    "baseSpAttack": 75,
    "baseSpDefense": 135,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 30,
    "expYield": 255
  },
  "RAIKOU": {
    "baseHP": 90,
    "baseAttack": 85,
    "baseDefense": 75,
    "baseSpeed": 115,
    "baseSpAttack": 115,
    "baseSpDefense": 100,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 3,
    "expYield": 216
  },
  "ENTEI": {
    "baseHP": 115,
    "baseAttack": 115,
    "baseDefense": 85,
    "baseSpeed": 100,
    "baseSpAttack": 90,
    "baseSpDefense": 75,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 3,
    "expYield": 217
  },
  "SUICUNE": {
    "baseHP": 100,
    "baseAttack": 75,
    "baseDefense": 115,
    "baseSpeed": 85,
    "baseSpAttack": 90,
    "baseSpDefense": 115,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 3,
    "expYield": 215
  },
  "LARVITAR": {
    "baseHP": 50,
    "baseAttack": 64,
    "baseDefense": 50,
    "baseSpeed": 41,
    "baseSpAttack": 45,
    "baseSpDefense": 50,
    "types": [
      "ROCK",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 67
  },
  "PUPITAR": {
    "baseHP": 70,
    "baseAttack": 84,
    "baseDefense": 70,
    "baseSpeed": 51,
    "baseSpAttack": 65,
    "baseSpDefense": 70,
    "types": [
      "ROCK",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 144
  },
  "TYRANITAR": {
    "baseHP": 100,
    "baseAttack": 134,
    "baseDefense": 110,
    "baseSpeed": 61,
    "baseSpAttack": 95,
    "baseSpDefense": 100,
    "types": [
      "ROCK",
      "DARK"
    ],
    "catchRate": 45,
    "expYield": 218
  },
  "LUGIA": {
    "baseHP": 106,
    "baseAttack": 90,
    "baseDefense": 130,
    "baseSpeed": 110,
    "baseSpAttack": 90,
    "baseSpDefense": 154,
    "types": [
      "PSYCHIC",
      "FLYING"
    ],
    "catchRate": 3,
    "expYield": 220
  },
  "HO_OH": {
    "baseHP": 106,
    "baseAttack": 130,
    "baseDefense": 90,
    "baseSpeed": 90,
    "baseSpAttack": 110,
    "baseSpDefense": 154,
    "types": [
      "FIRE",
      "FLYING"
    ],
    "catchRate": 3,
    "expYield": 220
  },
  "CELEBI": {
    "baseHP": 100,
    "baseAttack": 100,
    "baseDefense": 100,
    "baseSpeed": 100,
    "baseSpAttack": 100,
    "baseSpDefense": 100,
    "types": [
      "PSYCHIC",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 64
  },
  "TREECKO": {
    "baseHP": 40,
    "baseAttack": 45,
    "baseDefense": 35,
    "baseSpeed": 70,
    "baseSpAttack": 65,
    "baseSpDefense": 55,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 65
  },
  "GROVYLE": {
    "baseHP": 50,
    "baseAttack": 65,
    "baseDefense": 45,
    "baseSpeed": 95,
    "baseSpAttack": 85,
    "baseSpDefense": 65,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 141
  },
  "SCEPTILE": {
    "baseHP": 70,
    "baseAttack": 85,
    "baseDefense": 65,
    "baseSpeed": 120,
    "baseSpAttack": 105,
    "baseSpDefense": 85,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 208
  },
  "TORCHIC": {
    "baseHP": 45,
    "baseAttack": 60,
    "baseDefense": 40,
    "baseSpeed": 45,
    "baseSpAttack": 70,
    "baseSpDefense": 50,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 45,
    "expYield": 65
  },
  "COMBUSKEN": {
    "baseHP": 60,
    "baseAttack": 85,
    "baseDefense": 60,
    "baseSpeed": 55,
    "baseSpAttack": 85,
    "baseSpDefense": 60,
    "types": [
      "FIRE",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 142
  },
  "BLAZIKEN": {
    "baseHP": 80,
    "baseAttack": 120,
    "baseDefense": 70,
    "baseSpeed": 80,
    "baseSpAttack": 110,
    "baseSpDefense": 70,
    "types": [
      "FIRE",
      "FIGHTING"
    ],
    "catchRate": 45,
    "expYield": 209
  },
  "MUDKIP": {
    "baseHP": 50,
    "baseAttack": 70,
    "baseDefense": 50,
    "baseSpeed": 40,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 65
  },
  "MARSHTOMP": {
    "baseHP": 70,
    "baseAttack": 85,
    "baseDefense": 70,
    "baseSpeed": 50,
    "baseSpAttack": 60,
    "baseSpDefense": 70,
    "types": [
      "WATER",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 143
  },
  "SWAMPERT": {
    "baseHP": 100,
    "baseAttack": 110,
    "baseDefense": 90,
    "baseSpeed": 60,
    "baseSpAttack": 85,
    "baseSpDefense": 90,
    "types": [
      "WATER",
      "GROUND"
    ],
    "catchRate": 45,
    "expYield": 210
  },
  "POOCHYENA": {
    "baseHP": 35,
    "baseAttack": 55,
    "baseDefense": 35,
    "baseSpeed": 35,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "DARK",
      "DARK"
    ],
    "catchRate": 255,
    "expYield": 55
  },
  "MIGHTYENA": {
    "baseHP": 70,
    "baseAttack": 90,
    "baseDefense": 70,
    "baseSpeed": 70,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "DARK",
      "DARK"
    ],
    "catchRate": 127,
    "expYield": 128
  },
  "ZIGZAGOON": {
    "baseHP": 38,
    "baseAttack": 30,
    "baseDefense": 41,
    "baseSpeed": 60,
    "baseSpAttack": 30,
    "baseSpDefense": 41,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 60
  },
  "LINOONE": {
    "baseHP": 78,
    "baseAttack": 70,
    "baseDefense": 61,
    "baseSpeed": 100,
    "baseSpAttack": 50,
    "baseSpDefense": 61,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 90,
    "expYield": 128
  },
  "WURMPLE": {
    "baseHP": 45,
    "baseAttack": 45,
    "baseDefense": 35,
    "baseSpeed": 20,
    "baseSpAttack": 20,
    "baseSpDefense": 30,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 255,
    "expYield": 54
  },
  "SILCOON": {
    "baseHP": 50,
    "baseAttack": 35,
    "baseDefense": 55,
    "baseSpeed": 15,
    "baseSpAttack": 25,
    "baseSpDefense": 25,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 120,
    "expYield": 71
  },
  "BEAUTIFLY": {
    "baseHP": 60,
    "baseAttack": 70,
    "baseDefense": 50,
    "baseSpeed": 65,
    "baseSpAttack": 90,
    "baseSpDefense": 50,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 161
  },
  "CASCOON": {
    "baseHP": 50,
    "baseAttack": 35,
    "baseDefense": 55,
    "baseSpeed": 15,
    "baseSpAttack": 25,
    "baseSpDefense": 25,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 120,
    "expYield": 72
  },
  "DUSTOX": {
    "baseHP": 60,
    "baseAttack": 50,
    "baseDefense": 70,
    "baseSpeed": 65,
    "baseSpAttack": 50,
    "baseSpDefense": 90,
    "types": [
      "BUG",
      "POISON"
    ],
    "catchRate": 45,
    "expYield": 160
  },
  "LOTAD": {
    "baseHP": 40,
    "baseAttack": 30,
    "baseDefense": 30,
    "baseSpeed": 30,
    "baseSpAttack": 40,
    "baseSpDefense": 50,
    "types": [
      "WATER",
      "GRASS"
    ],
    "catchRate": 255,
    "expYield": 74
  },
  "LOMBRE": {
    "baseHP": 60,
    "baseAttack": 50,
    "baseDefense": 50,
    "baseSpeed": 50,
    "baseSpAttack": 60,
    "baseSpDefense": 70,
    "types": [
      "WATER",
      "GRASS"
    ],
    "catchRate": 120,
    "expYield": 141
  },
  "LUDICOLO": {
    "baseHP": 80,
    "baseAttack": 70,
    "baseDefense": 70,
    "baseSpeed": 70,
    "baseSpAttack": 90,
    "baseSpDefense": 100,
    "types": [
      "WATER",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 181
  },
  "SEEDOT": {
    "baseHP": 40,
    "baseAttack": 40,
    "baseDefense": 50,
    "baseSpeed": 30,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 255,
    "expYield": 74
  },
  "NUZLEAF": {
    "baseHP": 70,
    "baseAttack": 70,
    "baseDefense": 40,
    "baseSpeed": 60,
    "baseSpAttack": 60,
    "baseSpDefense": 40,
    "types": [
      "GRASS",
      "DARK"
    ],
    "catchRate": 120,
    "expYield": 141
  },
  "SHIFTRY": {
    "baseHP": 90,
    "baseAttack": 100,
    "baseDefense": 60,
    "baseSpeed": 80,
    "baseSpAttack": 90,
    "baseSpDefense": 60,
    "types": [
      "GRASS",
      "DARK"
    ],
    "catchRate": 45,
    "expYield": 181
  },
  "NINCADA": {
    "baseHP": 31,
    "baseAttack": 45,
    "baseDefense": 90,
    "baseSpeed": 40,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "BUG",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 65
  },
  "NINJASK": {
    "baseHP": 61,
    "baseAttack": 90,
    "baseDefense": 45,
    "baseSpeed": 160,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 120,
    "expYield": 155
  },
  "SHEDINJA": {
    "baseHP": 1,
    "baseAttack": 90,
    "baseDefense": 45,
    "baseSpeed": 40,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "BUG",
      "GHOST"
    ],
    "catchRate": 45,
    "expYield": 95
  },
  "TAILLOW": {
    "baseHP": 40,
    "baseAttack": 55,
    "baseDefense": 30,
    "baseSpeed": 85,
    "baseSpAttack": 30,
    "baseSpDefense": 30,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 200,
    "expYield": 59
  },
  "SWELLOW": {
    "baseHP": 60,
    "baseAttack": 85,
    "baseDefense": 60,
    "baseSpeed": 125,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 162
  },
  "SHROOMISH": {
    "baseHP": 60,
    "baseAttack": 40,
    "baseDefense": 60,
    "baseSpeed": 35,
    "baseSpAttack": 40,
    "baseSpDefense": 60,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 255,
    "expYield": 65
  },
  "BRELOOM": {
    "baseHP": 60,
    "baseAttack": 130,
    "baseDefense": 80,
    "baseSpeed": 70,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "GRASS",
      "FIGHTING"
    ],
    "catchRate": 90,
    "expYield": 165
  },
  "SPINDA": {
    "baseHP": 60,
    "baseAttack": 60,
    "baseDefense": 60,
    "baseSpeed": 60,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 85
  },
  "WINGULL": {
    "baseHP": 40,
    "baseAttack": 30,
    "baseDefense": 30,
    "baseSpeed": 85,
    "baseSpAttack": 55,
    "baseSpDefense": 30,
    "types": [
      "WATER",
      "FLYING"
    ],
    "catchRate": 190,
    "expYield": 64
  },
  "PELIPPER": {
    "baseHP": 60,
    "baseAttack": 50,
    "baseDefense": 100,
    "baseSpeed": 65,
    "baseSpAttack": 85,
    "baseSpDefense": 70,
    "types": [
      "WATER",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 164
  },
  "SURSKIT": {
    "baseHP": 40,
    "baseAttack": 30,
    "baseDefense": 32,
    "baseSpeed": 65,
    "baseSpAttack": 50,
    "baseSpDefense": 52,
    "types": [
      "BUG",
      "WATER"
    ],
    "catchRate": 200,
    "expYield": 63
  },
  "MASQUERAIN": {
    "baseHP": 70,
    "baseAttack": 60,
    "baseDefense": 62,
    "baseSpeed": 60,
    "baseSpAttack": 80,
    "baseSpDefense": 82,
    "types": [
      "BUG",
      "FLYING"
    ],
    "catchRate": 75,
    "expYield": 128
  },
  "WAILMER": {
    "baseHP": 130,
    "baseAttack": 70,
    "baseDefense": 35,
    "baseSpeed": 60,
    "baseSpAttack": 70,
    "baseSpDefense": 35,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 125,
    "expYield": 137
  },
  "WAILORD": {
    "baseHP": 170,
    "baseAttack": 90,
    "baseDefense": 45,
    "baseSpeed": 60,
    "baseSpAttack": 90,
    "baseSpDefense": 45,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 60,
    "expYield": 206
  },
  "SKITTY": {
    "baseHP": 50,
    "baseAttack": 45,
    "baseDefense": 45,
    "baseSpeed": 50,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 65
  },
  "DELCATTY": {
    "baseHP": 70,
    "baseAttack": 65,
    "baseDefense": 65,
    "baseSpeed": 70,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 60,
    "expYield": 138
  },
  "KECLEON": {
    "baseHP": 60,
    "baseAttack": 90,
    "baseDefense": 70,
    "baseSpeed": 40,
    "baseSpAttack": 60,
    "baseSpDefense": 120,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 200,
    "expYield": 132
  },
  "BALTOY": {
    "baseHP": 40,
    "baseAttack": 40,
    "baseDefense": 55,
    "baseSpeed": 55,
    "baseSpAttack": 40,
    "baseSpDefense": 70,
    "types": [
      "GROUND",
      "PSYCHIC"
    ],
    "catchRate": 255,
    "expYield": 58
  },
  "CLAYDOL": {
    "baseHP": 60,
    "baseAttack": 70,
    "baseDefense": 105,
    "baseSpeed": 75,
    "baseSpAttack": 70,
    "baseSpDefense": 120,
    "types": [
      "GROUND",
      "PSYCHIC"
    ],
    "catchRate": 90,
    "expYield": 189
  },
  "NOSEPASS": {
    "baseHP": 30,
    "baseAttack": 45,
    "baseDefense": 135,
    "baseSpeed": 30,
    "baseSpAttack": 45,
    "baseSpDefense": 90,
    "types": [
      "ROCK",
      "ROCK"
    ],
    "catchRate": 255,
    "expYield": 108
  },
  "TORKOAL": {
    "baseHP": 70,
    "baseAttack": 85,
    "baseDefense": 140,
    "baseSpeed": 20,
    "baseSpAttack": 85,
    "baseSpDefense": 70,
    "types": [
      "FIRE",
      "FIRE"
    ],
    "catchRate": 90,
    "expYield": 161
  },
  "SABLEYE": {
    "baseHP": 50,
    "baseAttack": 75,
    "baseDefense": 75,
    "baseSpeed": 50,
    "baseSpAttack": 65,
    "baseSpDefense": 65,
    "types": [
      "DARK",
      "GHOST"
    ],
    "catchRate": 45,
    "expYield": 98
  },
  "BARBOACH": {
    "baseHP": 50,
    "baseAttack": 48,
    "baseDefense": 43,
    "baseSpeed": 60,
    "baseSpAttack": 46,
    "baseSpDefense": 41,
    "types": [
      "WATER",
      "GROUND"
    ],
    "catchRate": 190,
    "expYield": 92
  },
  "WHISCASH": {
    "baseHP": 110,
    "baseAttack": 78,
    "baseDefense": 73,
    "baseSpeed": 60,
    "baseSpAttack": 76,
    "baseSpDefense": 71,
    "types": [
      "WATER",
      "GROUND"
    ],
    "catchRate": 75,
    "expYield": 158
  },
  "LUVDISC": {
    "baseHP": 43,
    "baseAttack": 30,
    "baseDefense": 55,
    "baseSpeed": 97,
    "baseSpAttack": 40,
    "baseSpDefense": 65,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 225,
    "expYield": 110
  },
  "CORPHISH": {
    "baseHP": 43,
    "baseAttack": 80,
    "baseDefense": 65,
    "baseSpeed": 35,
    "baseSpAttack": 50,
    "baseSpDefense": 35,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 205,
    "expYield": 111
  },
  "CRAWDAUNT": {
    "baseHP": 63,
    "baseAttack": 120,
    "baseDefense": 85,
    "baseSpeed": 55,
    "baseSpAttack": 90,
    "baseSpDefense": 55,
    "types": [
      "WATER",
      "DARK"
    ],
    "catchRate": 155,
    "expYield": 161
  },
  "FEEBAS": {
    "baseHP": 20,
    "baseAttack": 15,
    "baseDefense": 20,
    "baseSpeed": 80,
    "baseSpAttack": 10,
    "baseSpDefense": 55,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 255,
    "expYield": 61
  },
  "MILOTIC": {
    "baseHP": 95,
    "baseAttack": 60,
    "baseDefense": 79,
    "baseSpeed": 81,
    "baseSpAttack": 100,
    "baseSpDefense": 125,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 60,
    "expYield": 213
  },
  "CARVANHA": {
    "baseHP": 45,
    "baseAttack": 90,
    "baseDefense": 20,
    "baseSpeed": 65,
    "baseSpAttack": 65,
    "baseSpDefense": 20,
    "types": [
      "WATER",
      "DARK"
    ],
    "catchRate": 225,
    "expYield": 88
  },
  "SHARPEDO": {
    "baseHP": 70,
    "baseAttack": 120,
    "baseDefense": 40,
    "baseSpeed": 95,
    "baseSpAttack": 95,
    "baseSpDefense": 40,
    "types": [
      "WATER",
      "DARK"
    ],
    "catchRate": 60,
    "expYield": 175
  },
  "TRAPINCH": {
    "baseHP": 45,
    "baseAttack": 100,
    "baseDefense": 45,
    "baseSpeed": 10,
    "baseSpAttack": 45,
    "baseSpDefense": 45,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 73
  },
  "VIBRAVA": {
    "baseHP": 50,
    "baseAttack": 70,
    "baseDefense": 50,
    "baseSpeed": 70,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "GROUND",
      "DRAGON"
    ],
    "catchRate": 120,
    "expYield": 126
  },
  "FLYGON": {
    "baseHP": 80,
    "baseAttack": 100,
    "baseDefense": 80,
    "baseSpeed": 100,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "GROUND",
      "DRAGON"
    ],
    "catchRate": 45,
    "expYield": 197
  },
  "MAKUHITA": {
    "baseHP": 72,
    "baseAttack": 60,
    "baseDefense": 30,
    "baseSpeed": 25,
    "baseSpAttack": 20,
    "baseSpDefense": 30,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 180,
    "expYield": 87
  },
  "HARIYAMA": {
    "baseHP": 144,
    "baseAttack": 120,
    "baseDefense": 60,
    "baseSpeed": 50,
    "baseSpAttack": 40,
    "baseSpDefense": 60,
    "types": [
      "FIGHTING",
      "FIGHTING"
    ],
    "catchRate": 200,
    "expYield": 184
  },
  "ELECTRIKE": {
    "baseHP": 40,
    "baseAttack": 45,
    "baseDefense": 40,
    "baseSpeed": 65,
    "baseSpAttack": 65,
    "baseSpDefense": 40,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 120,
    "expYield": 104
  },
  "MANECTRIC": {
    "baseHP": 70,
    "baseAttack": 75,
    "baseDefense": 60,
    "baseSpeed": 105,
    "baseSpAttack": 105,
    "baseSpDefense": 60,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 45,
    "expYield": 168
  },
  "NUMEL": {
    "baseHP": 60,
    "baseAttack": 60,
    "baseDefense": 40,
    "baseSpeed": 35,
    "baseSpAttack": 65,
    "baseSpDefense": 45,
    "types": [
      "FIRE",
      "GROUND"
    ],
    "catchRate": 255,
    "expYield": 88
  },
  "CAMERUPT": {
    "baseHP": 70,
    "baseAttack": 100,
    "baseDefense": 70,
    "baseSpeed": 40,
    "baseSpAttack": 105,
    "baseSpDefense": 75,
    "types": [
      "FIRE",
      "GROUND"
    ],
    "catchRate": 150,
    "expYield": 175
  },
  "SPHEAL": {
    "baseHP": 70,
    "baseAttack": 40,
    "baseDefense": 50,
    "baseSpeed": 25,
    "baseSpAttack": 55,
    "baseSpDefense": 50,
    "types": [
      "ICE",
      "WATER"
    ],
    "catchRate": 255,
    "expYield": 75
  },
  "SEALEO": {
    "baseHP": 90,
    "baseAttack": 60,
    "baseDefense": 70,
    "baseSpeed": 45,
    "baseSpAttack": 75,
    "baseSpDefense": 70,
    "types": [
      "ICE",
      "WATER"
    ],
    "catchRate": 120,
    "expYield": 128
  },
  "WALREIN": {
    "baseHP": 110,
    "baseAttack": 80,
    "baseDefense": 90,
    "baseSpeed": 65,
    "baseSpAttack": 95,
    "baseSpDefense": 90,
    "types": [
      "ICE",
      "WATER"
    ],
    "catchRate": 45,
    "expYield": 192
  },
  "CACNEA": {
    "baseHP": 50,
    "baseAttack": 85,
    "baseDefense": 40,
    "baseSpeed": 35,
    "baseSpAttack": 85,
    "baseSpDefense": 40,
    "types": [
      "GRASS",
      "GRASS"
    ],
    "catchRate": 190,
    "expYield": 97
  },
  "CACTURNE": {
    "baseHP": 70,
    "baseAttack": 115,
    "baseDefense": 60,
    "baseSpeed": 55,
    "baseSpAttack": 115,
    "baseSpDefense": 60,
    "types": [
      "GRASS",
      "DARK"
    ],
    "catchRate": 60,
    "expYield": 177
  },
  "SNORUNT": {
    "baseHP": 50,
    "baseAttack": 50,
    "baseDefense": 50,
    "baseSpeed": 50,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "ICE",
      "ICE"
    ],
    "catchRate": 190,
    "expYield": 74
  },
  "GLALIE": {
    "baseHP": 80,
    "baseAttack": 80,
    "baseDefense": 80,
    "baseSpeed": 80,
    "baseSpAttack": 80,
    "baseSpDefense": 80,
    "types": [
      "ICE",
      "ICE"
    ],
    "catchRate": 75,
    "expYield": 187
  },
  "LUNATONE": {
    "baseHP": 70,
    "baseAttack": 55,
    "baseDefense": 65,
    "baseSpeed": 70,
    "baseSpAttack": 95,
    "baseSpDefense": 85,
    "types": [
      "ROCK",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 150
  },
  "SOLROCK": {
    "baseHP": 70,
    "baseAttack": 95,
    "baseDefense": 85,
    "baseSpeed": 70,
    "baseSpAttack": 55,
    "baseSpDefense": 65,
    "types": [
      "ROCK",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 150
  },
  "AZURILL": {
    "baseHP": 50,
    "baseAttack": 20,
    "baseDefense": 40,
    "baseSpeed": 20,
    "baseSpAttack": 20,
    "baseSpDefense": 40,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 150,
    "expYield": 33
  },
  "SPOINK": {
    "baseHP": 60,
    "baseAttack": 25,
    "baseDefense": 35,
    "baseSpeed": 60,
    "baseSpAttack": 70,
    "baseSpDefense": 80,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 255,
    "expYield": 89
  },
  "GRUMPIG": {
    "baseHP": 80,
    "baseAttack": 45,
    "baseDefense": 65,
    "baseSpeed": 80,
    "baseSpAttack": 90,
    "baseSpDefense": 110,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 60,
    "expYield": 164
  },
  "PLUSLE": {
    "baseHP": 60,
    "baseAttack": 50,
    "baseDefense": 40,
    "baseSpeed": 95,
    "baseSpAttack": 85,
    "baseSpDefense": 75,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 200,
    "expYield": 120
  },
  "MINUN": {
    "baseHP": 60,
    "baseAttack": 40,
    "baseDefense": 50,
    "baseSpeed": 95,
    "baseSpAttack": 75,
    "baseSpDefense": 85,
    "types": [
      "ELECTRIC",
      "ELECTRIC"
    ],
    "catchRate": 200,
    "expYield": 120
  },
  "MAWILE": {
    "baseHP": 50,
    "baseAttack": 85,
    "baseDefense": 85,
    "baseSpeed": 50,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "STEEL",
      "STEEL"
    ],
    "catchRate": 45,
    "expYield": 98
  },
  "MEDITITE": {
    "baseHP": 30,
    "baseAttack": 40,
    "baseDefense": 55,
    "baseSpeed": 60,
    "baseSpAttack": 40,
    "baseSpDefense": 55,
    "types": [
      "FIGHTING",
      "PSYCHIC"
    ],
    "catchRate": 180,
    "expYield": 91
  },
  "MEDICHAM": {
    "baseHP": 60,
    "baseAttack": 60,
    "baseDefense": 75,
    "baseSpeed": 80,
    "baseSpAttack": 60,
    "baseSpDefense": 75,
    "types": [
      "FIGHTING",
      "PSYCHIC"
    ],
    "catchRate": 90,
    "expYield": 153
  },
  "SWABLU": {
    "baseHP": 45,
    "baseAttack": 40,
    "baseDefense": 60,
    "baseSpeed": 50,
    "baseSpAttack": 40,
    "baseSpDefense": 75,
    "types": [
      "NORMAL",
      "FLYING"
    ],
    "catchRate": 255,
    "expYield": 74
  },
  "ALTARIA": {
    "baseHP": 75,
    "baseAttack": 70,
    "baseDefense": 90,
    "baseSpeed": 80,
    "baseSpAttack": 70,
    "baseSpDefense": 105,
    "types": [
      "DRAGON",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 188
  },
  "WYNAUT": {
    "baseHP": 95,
    "baseAttack": 23,
    "baseDefense": 48,
    "baseSpeed": 23,
    "baseSpAttack": 23,
    "baseSpDefense": 48,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 125,
    "expYield": 44
  },
  "DUSKULL": {
    "baseHP": 20,
    "baseAttack": 40,
    "baseDefense": 90,
    "baseSpeed": 25,
    "baseSpAttack": 30,
    "baseSpDefense": 90,
    "types": [
      "GHOST",
      "GHOST"
    ],
    "catchRate": 190,
    "expYield": 97
  },
  "DUSCLOPS": {
    "baseHP": 40,
    "baseAttack": 70,
    "baseDefense": 130,
    "baseSpeed": 25,
    "baseSpAttack": 60,
    "baseSpDefense": 130,
    "types": [
      "GHOST",
      "GHOST"
    ],
    "catchRate": 90,
    "expYield": 179
  },
  "ROSELIA": {
    "baseHP": 50,
    "baseAttack": 60,
    "baseDefense": 45,
    "baseSpeed": 65,
    "baseSpAttack": 100,
    "baseSpDefense": 80,
    "types": [
      "GRASS",
      "POISON"
    ],
    "catchRate": 150,
    "expYield": 152
  },
  "SLAKOTH": {
    "baseHP": 60,
    "baseAttack": 60,
    "baseDefense": 60,
    "baseSpeed": 30,
    "baseSpAttack": 35,
    "baseSpDefense": 35,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 255,
    "expYield": 83
  },
  "VIGOROTH": {
    "baseHP": 80,
    "baseAttack": 80,
    "baseDefense": 80,
    "baseSpeed": 90,
    "baseSpAttack": 55,
    "baseSpDefense": 55,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 120,
    "expYield": 126
  },
  "SLAKING": {
    "baseHP": 150,
    "baseAttack": 160,
    "baseDefense": 100,
    "baseSpeed": 100,
    "baseSpAttack": 95,
    "baseSpDefense": 65,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 210
  },
  "GULPIN": {
    "baseHP": 70,
    "baseAttack": 43,
    "baseDefense": 53,
    "baseSpeed": 40,
    "baseSpAttack": 43,
    "baseSpDefense": 53,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 225,
    "expYield": 75
  },
  "SWALOT": {
    "baseHP": 100,
    "baseAttack": 73,
    "baseDefense": 83,
    "baseSpeed": 55,
    "baseSpAttack": 73,
    "baseSpDefense": 83,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 75,
    "expYield": 168
  },
  "TROPIUS": {
    "baseHP": 99,
    "baseAttack": 68,
    "baseDefense": 83,
    "baseSpeed": 51,
    "baseSpAttack": 72,
    "baseSpDefense": 87,
    "types": [
      "GRASS",
      "FLYING"
    ],
    "catchRate": 200,
    "expYield": 169
  },
  "WHISMUR": {
    "baseHP": 64,
    "baseAttack": 51,
    "baseDefense": 23,
    "baseSpeed": 28,
    "baseSpAttack": 51,
    "baseSpDefense": 23,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 190,
    "expYield": 68
  },
  "LOUDRED": {
    "baseHP": 84,
    "baseAttack": 71,
    "baseDefense": 43,
    "baseSpeed": 48,
    "baseSpAttack": 71,
    "baseSpDefense": 43,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 120,
    "expYield": 126
  },
  "EXPLOUD": {
    "baseHP": 104,
    "baseAttack": 91,
    "baseDefense": 63,
    "baseSpeed": 68,
    "baseSpAttack": 91,
    "baseSpDefense": 63,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 184
  },
  "CLAMPERL": {
    "baseHP": 35,
    "baseAttack": 64,
    "baseDefense": 85,
    "baseSpeed": 32,
    "baseSpAttack": 74,
    "baseSpDefense": 55,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 255,
    "expYield": 142
  },
  "HUNTAIL": {
    "baseHP": 55,
    "baseAttack": 104,
    "baseDefense": 105,
    "baseSpeed": 52,
    "baseSpAttack": 94,
    "baseSpDefense": 75,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 60,
    "expYield": 178
  },
  "GOREBYSS": {
    "baseHP": 55,
    "baseAttack": 84,
    "baseDefense": 105,
    "baseSpeed": 52,
    "baseSpAttack": 114,
    "baseSpDefense": 75,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 60,
    "expYield": 178
  },
  "ABSOL": {
    "baseHP": 65,
    "baseAttack": 130,
    "baseDefense": 60,
    "baseSpeed": 75,
    "baseSpAttack": 75,
    "baseSpDefense": 60,
    "types": [
      "DARK",
      "DARK"
    ],
    "catchRate": 30,
    "expYield": 174
  },
  "SHUPPET": {
    "baseHP": 44,
    "baseAttack": 75,
    "baseDefense": 35,
    "baseSpeed": 45,
    "baseSpAttack": 63,
    "baseSpDefense": 33,
    "types": [
      "GHOST",
      "GHOST"
    ],
    "catchRate": 225,
    "expYield": 97
  },
  "BANETTE": {
    "baseHP": 64,
    "baseAttack": 115,
    "baseDefense": 65,
    "baseSpeed": 65,
    "baseSpAttack": 83,
    "baseSpDefense": 63,
    "types": [
      "GHOST",
      "GHOST"
    ],
    "catchRate": 45,
    "expYield": 179
  },
  "SEVIPER": {
    "baseHP": 73,
    "baseAttack": 100,
    "baseDefense": 60,
    "baseSpeed": 65,
    "baseSpAttack": 100,
    "baseSpDefense": 60,
    "types": [
      "POISON",
      "POISON"
    ],
    "catchRate": 90,
    "expYield": 165
  },
  "ZANGOOSE": {
    "baseHP": 73,
    "baseAttack": 115,
    "baseDefense": 60,
    "baseSpeed": 90,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 90,
    "expYield": 165
  },
  "RELICANTH": {
    "baseHP": 100,
    "baseAttack": 90,
    "baseDefense": 130,
    "baseSpeed": 55,
    "baseSpAttack": 45,
    "baseSpDefense": 65,
    "types": [
      "WATER",
      "ROCK"
    ],
    "catchRate": 25,
    "expYield": 198
  },
  "ARON": {
    "baseHP": 50,
    "baseAttack": 70,
    "baseDefense": 100,
    "baseSpeed": 30,
    "baseSpAttack": 40,
    "baseSpDefense": 40,
    "types": [
      "STEEL",
      "ROCK"
    ],
    "catchRate": 180,
    "expYield": 96
  },
  "LAIRON": {
    "baseHP": 60,
    "baseAttack": 90,
    "baseDefense": 140,
    "baseSpeed": 40,
    "baseSpAttack": 50,
    "baseSpDefense": 50,
    "types": [
      "STEEL",
      "ROCK"
    ],
    "catchRate": 90,
    "expYield": 152
  },
  "AGGRON": {
    "baseHP": 70,
    "baseAttack": 110,
    "baseDefense": 180,
    "baseSpeed": 50,
    "baseSpAttack": 60,
    "baseSpDefense": 60,
    "types": [
      "STEEL",
      "ROCK"
    ],
    "catchRate": 45,
    "expYield": 205
  },
  "CASTFORM": {
    "baseHP": 70,
    "baseAttack": 70,
    "baseDefense": 70,
    "baseSpeed": 70,
    "baseSpAttack": 70,
    "baseSpDefense": 70,
    "types": [
      "NORMAL",
      "NORMAL"
    ],
    "catchRate": 45,
    "expYield": 145
  },
  "VOLBEAT": {
    "baseHP": 65,
    "baseAttack": 73,
    "baseDefense": 55,
    "baseSpeed": 85,
    "baseSpAttack": 47,
    "baseSpDefense": 75,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 150,
    "expYield": 146
  },
  "ILLUMISE": {
    "baseHP": 65,
    "baseAttack": 47,
    "baseDefense": 55,
    "baseSpeed": 85,
    "baseSpAttack": 73,
    "baseSpDefense": 75,
    "types": [
      "BUG",
      "BUG"
    ],
    "catchRate": 150,
    "expYield": 146
  },
  "LILEEP": {
    "baseHP": 66,
    "baseAttack": 41,
    "baseDefense": 77,
    "baseSpeed": 23,
    "baseSpAttack": 61,
    "baseSpDefense": 87,
    "types": [
      "ROCK",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 121
  },
  "CRADILY": {
    "baseHP": 86,
    "baseAttack": 81,
    "baseDefense": 97,
    "baseSpeed": 43,
    "baseSpAttack": 81,
    "baseSpDefense": 107,
    "types": [
      "ROCK",
      "GRASS"
    ],
    "catchRate": 45,
    "expYield": 201
  },
  "ANORITH": {
    "baseHP": 45,
    "baseAttack": 95,
    "baseDefense": 50,
    "baseSpeed": 75,
    "baseSpAttack": 40,
    "baseSpDefense": 50,
    "types": [
      "ROCK",
      "BUG"
    ],
    "catchRate": 45,
    "expYield": 119
  },
  "ARMALDO": {
    "baseHP": 75,
    "baseAttack": 125,
    "baseDefense": 100,
    "baseSpeed": 45,
    "baseSpAttack": 70,
    "baseSpDefense": 80,
    "types": [
      "ROCK",
      "BUG"
    ],
    "catchRate": 45,
    "expYield": 200
  },
  "RALTS": {
    "baseHP": 28,
    "baseAttack": 25,
    "baseDefense": 25,
    "baseSpeed": 40,
    "baseSpAttack": 45,
    "baseSpDefense": 35,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 235,
    "expYield": 70
  },
  "KIRLIA": {
    "baseHP": 38,
    "baseAttack": 35,
    "baseDefense": 35,
    "baseSpeed": 50,
    "baseSpAttack": 65,
    "baseSpDefense": 55,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 120,
    "expYield": 140
  },
  "GARDEVOIR": {
    "baseHP": 68,
    "baseAttack": 65,
    "baseDefense": 65,
    "baseSpeed": 80,
    "baseSpAttack": 125,
    "baseSpDefense": 115,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 208
  },
  "BAGON": {
    "baseHP": 45,
    "baseAttack": 75,
    "baseDefense": 60,
    "baseSpeed": 50,
    "baseSpAttack": 40,
    "baseSpDefense": 30,
    "types": [
      "DRAGON",
      "DRAGON"
    ],
    "catchRate": 45,
    "expYield": 89
  },
  "SHELGON": {
    "baseHP": 65,
    "baseAttack": 95,
    "baseDefense": 100,
    "baseSpeed": 50,
    "baseSpAttack": 60,
    "baseSpDefense": 50,
    "types": [
      "DRAGON",
      "DRAGON"
    ],
    "catchRate": 45,
    "expYield": 144
  },
  "SALAMENCE": {
    "baseHP": 95,
    "baseAttack": 135,
    "baseDefense": 80,
    "baseSpeed": 100,
    "baseSpAttack": 110,
    "baseSpDefense": 80,
    "types": [
      "DRAGON",
      "FLYING"
    ],
    "catchRate": 45,
    "expYield": 218
  },
  "BELDUM": {
    "baseHP": 40,
    "baseAttack": 55,
    "baseDefense": 80,
    "baseSpeed": 30,
    "baseSpAttack": 35,
    "baseSpDefense": 60,
    "types": [
      "STEEL",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 103
  },
  "METANG": {
    "baseHP": 60,
    "baseAttack": 75,
    "baseDefense": 100,
    "baseSpeed": 50,
    "baseSpAttack": 55,
    "baseSpDefense": 80,
    "types": [
      "STEEL",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 153
  },
  "METAGROSS": {
    "baseHP": 80,
    "baseAttack": 135,
    "baseDefense": 130,
    "baseSpeed": 70,
    "baseSpAttack": 95,
    "baseSpDefense": 90,
    "types": [
      "STEEL",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 210
  },
  "REGIROCK": {
    "baseHP": 80,
    "baseAttack": 100,
    "baseDefense": 200,
    "baseSpeed": 50,
    "baseSpAttack": 50,
    "baseSpDefense": 100,
    "types": [
      "ROCK",
      "ROCK"
    ],
    "catchRate": 3,
    "expYield": 217
  },
  "REGICE": {
    "baseHP": 80,
    "baseAttack": 50,
    "baseDefense": 100,
    "baseSpeed": 50,
    "baseSpAttack": 100,
    "baseSpDefense": 200,
    "types": [
      "ICE",
      "ICE"
    ],
    "catchRate": 3,
    "expYield": 216
  },
  "REGISTEEL": {
    "baseHP": 80,
    "baseAttack": 75,
    "baseDefense": 150,
    "baseSpeed": 50,
    "baseSpAttack": 75,
    "baseSpDefense": 150,
    "types": [
      "STEEL",
      "STEEL"
    ],
    "catchRate": 3,
    "expYield": 215
  },
  "KYOGRE": {
    "baseHP": 100,
    "baseAttack": 100,
    "baseDefense": 90,
    "baseSpeed": 90,
    "baseSpAttack": 150,
    "baseSpDefense": 140,
    "types": [
      "WATER",
      "WATER"
    ],
    "catchRate": 5,
    "expYield": 218
  },
  "GROUDON": {
    "baseHP": 100,
    "baseAttack": 150,
    "baseDefense": 140,
    "baseSpeed": 90,
    "baseSpAttack": 100,
    "baseSpDefense": 90,
    "types": [
      "GROUND",
      "GROUND"
    ],
    "catchRate": 5,
    "expYield": 218
  },
  "RAYQUAZA": {
    "baseHP": 105,
    "baseAttack": 150,
    "baseDefense": 90,
    "baseSpeed": 95,
    "baseSpAttack": 150,
    "baseSpDefense": 90,
    "types": [
      "DRAGON",
      "FLYING"
    ],
    "catchRate": 3,
    "expYield": 220
  },
  "LATIAS": {
    "baseHP": 80,
    "baseAttack": 80,
    "baseDefense": 90,
    "baseSpeed": 110,
    "baseSpAttack": 110,
    "baseSpDefense": 130,
    "types": [
      "DRAGON",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 211
  },
  "LATIOS": {
    "baseHP": 80,
    "baseAttack": 90,
    "baseDefense": 80,
    "baseSpeed": 110,
    "baseSpAttack": 130,
    "baseSpDefense": 110,
    "types": [
      "DRAGON",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 211
  },
  "JIRACHI": {
    "baseHP": 100,
    "baseAttack": 100,
    "baseDefense": 100,
    "baseSpeed": 100,
    "baseSpAttack": 100,
    "baseSpDefense": 100,
    "types": [
      "STEEL",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 215
  },
  "DEOXYS": {
    "baseHP": 50,
    "baseAttack": 150,
    "baseDefense": 50,
    "baseSpeed": 150,
    "baseSpAttack": 150,
    "baseSpDefense": 50,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 3,
    "expYield": 215
  },
  "CHIMECHO": {
    "baseHP": 65,
    "baseAttack": 50,
    "baseDefense": 70,
    "baseSpeed": 65,
    "baseSpAttack": 95,
    "baseSpDefense": 80,
    "types": [
      "PSYCHIC",
      "PSYCHIC"
    ],
    "catchRate": 45,
    "expYield": 147
  }
};
