// AUTOGENERATED by scripts/generate-indoor-maps.mjs — do not edit.
// Maps every internal MapID to its canonical pokefirered layout.

import { bridgeFireredLayout, type FireredLayoutJson } from '../../lib/firered/bridge';
import type { MapData } from '../../types';

import firered_players_house_1f from '../../artifacts/firered/maps/LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_1F.json';
import firered_players_house_2f from '../../artifacts/firered/maps/LAYOUT_PALLET_TOWN_PLAYERS_HOUSE_2F.json';
import firered_rivals_house from '../../artifacts/firered/maps/LAYOUT_PALLET_TOWN_RIVALS_HOUSE.json';
import firered_oaks_lab from '../../artifacts/firered/maps/LAYOUT_PALLET_TOWN_PROFESSOR_OAKS_LAB.json';
import firered_pokecenter_viridian from '../../artifacts/firered/maps/MAPID_POKECENTER_VIRIDIAN.json';
import firered_pokecenter_pewter from '../../artifacts/firered/maps/MAPID_POKECENTER_PEWTER.json';
import firered_pokecenter_cerulean from '../../artifacts/firered/maps/MAPID_POKECENTER_CERULEAN.json';
import firered_pokecenter_lavender from '../../artifacts/firered/maps/MAPID_POKECENTER_LAVENDER.json';
import firered_pokecenter_vermilion from '../../artifacts/firered/maps/MAPID_POKECENTER_VERMILION.json';
import firered_pokecenter_celadon from '../../artifacts/firered/maps/MAPID_POKECENTER_CELADON.json';
import firered_pokecenter_fuchsia from '../../artifacts/firered/maps/MAPID_POKECENTER_FUCHSIA.json';
import firered_pokecenter_saffron from '../../artifacts/firered/maps/MAPID_POKECENTER_SAFFRON.json';
import firered_pokecenter_cinnabar from '../../artifacts/firered/maps/MAPID_POKECENTER_CINNABAR.json';
import firered_pokecenter_route4 from '../../artifacts/firered/maps/MAPID_POKECENTER_ROUTE4.json';
import firered_pokecenter_route10 from '../../artifacts/firered/maps/MAPID_POKECENTER_ROUTE10.json';
import firered_pokemart_viridian from '../../artifacts/firered/maps/MAPID_POKEMART_VIRIDIAN.json';
import firered_pokemart_pewter from '../../artifacts/firered/maps/MAPID_POKEMART_PEWTER.json';
import firered_pokemart_cerulean from '../../artifacts/firered/maps/MAPID_POKEMART_CERULEAN.json';
import firered_pokemart_lavender from '../../artifacts/firered/maps/MAPID_POKEMART_LAVENDER.json';
import firered_pokemart_vermilion from '../../artifacts/firered/maps/MAPID_POKEMART_VERMILION.json';
import firered_pokemart_fuchsia from '../../artifacts/firered/maps/MAPID_POKEMART_FUCHSIA.json';
import firered_pokemart_saffron from '../../artifacts/firered/maps/MAPID_POKEMART_SAFFRON.json';
import firered_pokemart_cinnabar from '../../artifacts/firered/maps/MAPID_POKEMART_CINNABAR.json';
import firered_mt_moon from '../../artifacts/firered/maps/LAYOUT_MT_MOON_1F.json';
import firered_mt_moon_b1f from '../../artifacts/firered/maps/LAYOUT_MT_MOON_B1F.json';
import firered_mt_moon_b2f from '../../artifacts/firered/maps/LAYOUT_MT_MOON_B2F.json';
import firered_pewter_gym from '../../artifacts/firered/maps/LAYOUT_PEWTER_CITY_GYM.json';
import firered_cerulean_gym from '../../artifacts/firered/maps/LAYOUT_CERULEAN_CITY_GYM.json';
import firered_vermilion_gym from '../../artifacts/firered/maps/LAYOUT_VERMILION_CITY_GYM.json';
import firered_celadon_gym from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_GYM.json';
import firered_fuchsia_gym from '../../artifacts/firered/maps/LAYOUT_FUCHSIA_CITY_GYM.json';
import firered_saffron_gym from '../../artifacts/firered/maps/LAYOUT_SAFFRON_CITY_GYM.json';
import firered_cinnabar_gym from '../../artifacts/firered/maps/LAYOUT_CINNABAR_ISLAND_GYM.json';
import firered_viridian_gym from '../../artifacts/firered/maps/LAYOUT_VIRIDIAN_CITY_GYM.json';
import firered_rock_tunnel_1f from '../../artifacts/firered/maps/LAYOUT_ROCK_TUNNEL_1F.json';
import firered_rock_tunnel_b1f from '../../artifacts/firered/maps/LAYOUT_ROCK_TUNNEL_B1F.json';
import firered_pokemon_tower_1f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_1F.json';
import firered_pokemon_tower_2f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_2F.json';
import firered_pokemon_tower_3f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_3F.json';
import firered_pokemon_tower_4f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_4F.json';
import firered_pokemon_tower_5f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_5F.json';
import firered_pokemon_tower_6f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_6F.json';
import firered_pokemon_tower_7f from '../../artifacts/firered/maps/LAYOUT_POKEMON_TOWER_7F.json';
import firered_bills_house from '../../artifacts/firered/maps/LAYOUT_ROUTE25_SEA_COTTAGE.json';
import firered_seafoam_islands_1f from '../../artifacts/firered/maps/LAYOUT_SEAFOAM_ISLANDS_1F.json';
import firered_seafoam_islands_b1f from '../../artifacts/firered/maps/LAYOUT_SEAFOAM_ISLANDS_B1F.json';
import firered_seafoam_islands_b2f from '../../artifacts/firered/maps/LAYOUT_SEAFOAM_ISLANDS_B2F.json';
import firered_seafoam_islands_b3f from '../../artifacts/firered/maps/LAYOUT_SEAFOAM_ISLANDS_B3F.json';
import firered_seafoam_islands_b4f from '../../artifacts/firered/maps/LAYOUT_SEAFOAM_ISLANDS_B4F.json';
import firered_victory_road_1f from '../../artifacts/firered/maps/LAYOUT_VICTORY_ROAD_1F.json';
import firered_victory_road_2f from '../../artifacts/firered/maps/LAYOUT_VICTORY_ROAD_2F.json';
import firered_victory_road_3f from '../../artifacts/firered/maps/LAYOUT_VICTORY_ROAD_3F.json';
import firered_cerulean_cave_1f from '../../artifacts/firered/maps/LAYOUT_CERULEAN_CAVE_1F.json';
import firered_cerulean_cave_2f from '../../artifacts/firered/maps/LAYOUT_CERULEAN_CAVE_2F.json';
import firered_cerulean_cave_b_1f from '../../artifacts/firered/maps/LAYOUT_CERULEAN_CAVE_B1F.json';
import firered_digletts_cave from '../../artifacts/firered/maps/LAYOUT_DIGLETTS_CAVE_B1F.json';
import firered_power_plant from '../../artifacts/firered/maps/LAYOUT_POWER_PLANT.json';
import firered_pokemon_mansion_1f from '../../artifacts/firered/maps/LAYOUT_POKEMON_MANSION_1F.json';
import firered_pokemon_mansion_2f from '../../artifacts/firered/maps/LAYOUT_POKEMON_MANSION_2F.json';
import firered_pokemon_mansion_3f from '../../artifacts/firered/maps/LAYOUT_POKEMON_MANSION_3F.json';
import firered_pokemon_mansion_b1f from '../../artifacts/firered/maps/LAYOUT_POKEMON_MANSION_B1F.json';
import firered_safari_zone_center from '../../artifacts/firered/maps/LAYOUT_SAFARI_ZONE_CENTER.json';
import firered_silph_co_1f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_1F.json';
import firered_silph_co_2f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_2F.json';
import firered_silph_co_3f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_3F.json';
import firered_silph_co_4f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_4F.json';
import firered_silph_co_5f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_5F.json';
import firered_silph_co_6f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_6F.json';
import firered_silph_co_7f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_7F.json';
import firered_silph_co_8f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_8F.json';
import firered_silph_co_9f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_9F.json';
import firered_silph_co_10f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_10F.json';
import firered_silph_co_11f from '../../artifacts/firered/maps/LAYOUT_SILPH_CO_11F.json';
import firered_rocket_hideout_b1f from '../../artifacts/firered/maps/LAYOUT_ROCKET_HIDEOUT_B1F.json';
import firered_rocket_hideout_b2f from '../../artifacts/firered/maps/LAYOUT_ROCKET_HIDEOUT_B2F.json';
import firered_rocket_hideout_b3f from '../../artifacts/firered/maps/LAYOUT_ROCKET_HIDEOUT_B3F.json';
import firered_rocket_hideout_b4f from '../../artifacts/firered/maps/LAYOUT_ROCKET_HIDEOUT_B4F.json';
import firered_ss_anne_1f from '../../artifacts/firered/maps/LAYOUT_SSANNE_1F_CORRIDOR.json';
import firered_ss_anne_2f from '../../artifacts/firered/maps/LAYOUT_SSANNE_2F_CORRIDOR.json';
import firered_ss_anne_3f from '../../artifacts/firered/maps/LAYOUT_SSANNE_3F_CORRIDOR.json';
import firered_indigo_plateau_lobby from '../../artifacts/firered/maps/MAPID_INDIGO_PLATEAU_LOBBY.json';
import firered_elite_four_lorelei from '../../artifacts/firered/maps/MAPID_ELITE_FOUR_LORELEI.json';
import firered_elite_four_bruno from '../../artifacts/firered/maps/MAPID_ELITE_FOUR_BRUNO.json';
import firered_elite_four_agatha from '../../artifacts/firered/maps/MAPID_ELITE_FOUR_AGATHA.json';
import firered_elite_four_lance from '../../artifacts/firered/maps/MAPID_ELITE_FOUR_LANCE.json';
import firered_elite_four_champion from '../../artifacts/firered/maps/MAPID_ELITE_FOUR_CHAMPION.json';
import firered_hall_of_fame from '../../artifacts/firered/maps/MAPID_HALL_OF_FAME.json';
import firered_celadon_mart_1f from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_1F.json';
import firered_celadon_mart_2f from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_2F.json';
import firered_celadon_mart_3f from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_3F.json';
import firered_celadon_mart_4f from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_4F.json';
import firered_celadon_mart_5f from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_5F.json';
import firered_celadon_mart_elevator from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_ELEVATOR.json';
import firered_celadon_mart_roof from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_DEPARTMENT_STORE_ROOF.json';
import firered_celadon_game_corner from '../../artifacts/firered/maps/LAYOUT_CELADON_CITY_GAME_CORNER.json';
import firered_viridian_forest from '../../artifacts/firered/maps/LAYOUT_VIRIDIAN_FOREST.json';

function fromFirered(json: unknown): MapData {
  const parsed = bridgeFireredLayout(json as FireredLayoutJson);
  return {
    tiles: parsed.tiles,
    warps: parsed.warps as MapData['warps'],
    firered: true,
    fireredLayout: parsed.layout,
    isUnderground: parsed.isUnderground,
  };
}

export const FIRERED_INDOOR_MAPS = {
  PLAYERS_HOUSE_1F: fromFirered(firered_players_house_1f),
  PLAYERS_HOUSE_2F: fromFirered(firered_players_house_2f),
  RIVALS_HOUSE: fromFirered(firered_rivals_house),
  OAKS_LAB: fromFirered(firered_oaks_lab),
  POKECENTER_VIRIDIAN: fromFirered(firered_pokecenter_viridian),
  POKECENTER_PEWTER: fromFirered(firered_pokecenter_pewter),
  POKECENTER_CERULEAN: fromFirered(firered_pokecenter_cerulean),
  POKECENTER_LAVENDER: fromFirered(firered_pokecenter_lavender),
  POKECENTER_VERMILION: fromFirered(firered_pokecenter_vermilion),
  POKECENTER_CELADON: fromFirered(firered_pokecenter_celadon),
  POKECENTER_FUCHSIA: fromFirered(firered_pokecenter_fuchsia),
  POKECENTER_SAFFRON: fromFirered(firered_pokecenter_saffron),
  POKECENTER_CINNABAR: fromFirered(firered_pokecenter_cinnabar),
  POKECENTER_ROUTE4: fromFirered(firered_pokecenter_route4),
  POKECENTER_ROUTE10: fromFirered(firered_pokecenter_route10),
  POKEMART_VIRIDIAN: fromFirered(firered_pokemart_viridian),
  POKEMART_PEWTER: fromFirered(firered_pokemart_pewter),
  POKEMART_CERULEAN: fromFirered(firered_pokemart_cerulean),
  POKEMART_LAVENDER: fromFirered(firered_pokemart_lavender),
  POKEMART_VERMILION: fromFirered(firered_pokemart_vermilion),
  POKEMART_FUCHSIA: fromFirered(firered_pokemart_fuchsia),
  POKEMART_SAFFRON: fromFirered(firered_pokemart_saffron),
  POKEMART_CINNABAR: fromFirered(firered_pokemart_cinnabar),
  MT_MOON: fromFirered(firered_mt_moon),
  MT_MOON_B1F: fromFirered(firered_mt_moon_b1f),
  MT_MOON_B2F: fromFirered(firered_mt_moon_b2f),
  PEWTER_GYM: fromFirered(firered_pewter_gym),
  CERULEAN_GYM: fromFirered(firered_cerulean_gym),
  VERMILION_GYM: fromFirered(firered_vermilion_gym),
  CELADON_GYM: fromFirered(firered_celadon_gym),
  FUCHSIA_GYM: fromFirered(firered_fuchsia_gym),
  SAFFRON_GYM: fromFirered(firered_saffron_gym),
  CINNABAR_GYM: fromFirered(firered_cinnabar_gym),
  VIRIDIAN_GYM: fromFirered(firered_viridian_gym),
  ROCK_TUNNEL_1F: fromFirered(firered_rock_tunnel_1f),
  ROCK_TUNNEL_B1F: fromFirered(firered_rock_tunnel_b1f),
  POKEMON_TOWER_1F: fromFirered(firered_pokemon_tower_1f),
  POKEMON_TOWER_2F: fromFirered(firered_pokemon_tower_2f),
  POKEMON_TOWER_3F: fromFirered(firered_pokemon_tower_3f),
  POKEMON_TOWER_4F: fromFirered(firered_pokemon_tower_4f),
  POKEMON_TOWER_5F: fromFirered(firered_pokemon_tower_5f),
  POKEMON_TOWER_6F: fromFirered(firered_pokemon_tower_6f),
  POKEMON_TOWER_7F: fromFirered(firered_pokemon_tower_7f),
  BILLS_HOUSE: fromFirered(firered_bills_house),
  SEAFOAM_ISLANDS_1F: fromFirered(firered_seafoam_islands_1f),
  SEAFOAM_ISLANDS_B1F: fromFirered(firered_seafoam_islands_b1f),
  SEAFOAM_ISLANDS_B2F: fromFirered(firered_seafoam_islands_b2f),
  SEAFOAM_ISLANDS_B3F: fromFirered(firered_seafoam_islands_b3f),
  SEAFOAM_ISLANDS_B4F: fromFirered(firered_seafoam_islands_b4f),
  VICTORY_ROAD_1F: fromFirered(firered_victory_road_1f),
  VICTORY_ROAD_2F: fromFirered(firered_victory_road_2f),
  VICTORY_ROAD_3F: fromFirered(firered_victory_road_3f),
  CERULEAN_CAVE_1F: fromFirered(firered_cerulean_cave_1f),
  CERULEAN_CAVE_2F: fromFirered(firered_cerulean_cave_2f),
  CERULEAN_CAVE_B_1F: fromFirered(firered_cerulean_cave_b_1f),
  DIGLETTS_CAVE: fromFirered(firered_digletts_cave),
  POWER_PLANT: fromFirered(firered_power_plant),
  POKEMON_MANSION_1F: fromFirered(firered_pokemon_mansion_1f),
  POKEMON_MANSION_2F: fromFirered(firered_pokemon_mansion_2f),
  POKEMON_MANSION_3F: fromFirered(firered_pokemon_mansion_3f),
  POKEMON_MANSION_B1F: fromFirered(firered_pokemon_mansion_b1f),
  SAFARI_ZONE_CENTER: fromFirered(firered_safari_zone_center),
  SILPH_CO_1F: fromFirered(firered_silph_co_1f),
  SILPH_CO_2F: fromFirered(firered_silph_co_2f),
  SILPH_CO_3F: fromFirered(firered_silph_co_3f),
  SILPH_CO_4F: fromFirered(firered_silph_co_4f),
  SILPH_CO_5F: fromFirered(firered_silph_co_5f),
  SILPH_CO_6F: fromFirered(firered_silph_co_6f),
  SILPH_CO_7F: fromFirered(firered_silph_co_7f),
  SILPH_CO_8F: fromFirered(firered_silph_co_8f),
  SILPH_CO_9F: fromFirered(firered_silph_co_9f),
  SILPH_CO_10F: fromFirered(firered_silph_co_10f),
  SILPH_CO_11F: fromFirered(firered_silph_co_11f),
  ROCKET_HIDEOUT_B1F: fromFirered(firered_rocket_hideout_b1f),
  ROCKET_HIDEOUT_B2F: fromFirered(firered_rocket_hideout_b2f),
  ROCKET_HIDEOUT_B3F: fromFirered(firered_rocket_hideout_b3f),
  ROCKET_HIDEOUT_B4F: fromFirered(firered_rocket_hideout_b4f),
  SS_ANNE_1F: fromFirered(firered_ss_anne_1f),
  SS_ANNE_2F: fromFirered(firered_ss_anne_2f),
  SS_ANNE_3F: fromFirered(firered_ss_anne_3f),
  INDIGO_PLATEAU_LOBBY: fromFirered(firered_indigo_plateau_lobby),
  ELITE_FOUR_LORELEI: fromFirered(firered_elite_four_lorelei),
  ELITE_FOUR_BRUNO: fromFirered(firered_elite_four_bruno),
  ELITE_FOUR_AGATHA: fromFirered(firered_elite_four_agatha),
  ELITE_FOUR_LANCE: fromFirered(firered_elite_four_lance),
  ELITE_FOUR_CHAMPION: fromFirered(firered_elite_four_champion),
  HALL_OF_FAME: fromFirered(firered_hall_of_fame),
  CELADON_MART_1F: fromFirered(firered_celadon_mart_1f),
  CELADON_MART_2F: fromFirered(firered_celadon_mart_2f),
  CELADON_MART_3F: fromFirered(firered_celadon_mart_3f),
  CELADON_MART_4F: fromFirered(firered_celadon_mart_4f),
  CELADON_MART_5F: fromFirered(firered_celadon_mart_5f),
  CELADON_MART_ELEVATOR: fromFirered(firered_celadon_mart_elevator),
  CELADON_MART_ROOF: fromFirered(firered_celadon_mart_roof),
  CELADON_GAME_CORNER: fromFirered(firered_celadon_game_corner),
  VIRIDIAN_FOREST: fromFirered(firered_viridian_forest),
} as const;
