import fs from 'fs';
import path from 'path';

// Generated by stitch-kanto.mjs
const KANTO_OFFSETS = {
  PALLET_TOWN       : { x:  11, y: 198 },
  ROUTE_1           : { x:  16, y: 163 },
  VIRIDIAN_CITY     : { x:   0, y: 128 },
  ROUTE_2           : { x:  16, y:  89 },
  VIRIDIAN_FOREST   : { x:   4, y:  42 },
  PEWTER_CITY       : { x:   0, y:   7 },
  ROUTE_3           : { x:  39, y:  18 },
  ROUTE_4           : { x:  69, y:  14 },
  CERULEAN_CITY     : { x: 108, y:   0 },
  ROUTE_5           : { x: 124, y:  35 },
  SAFFRON_CITY      : { x: 108, y:  51 },
  ROUTE_6           : { x: 124, y:  86 },
  VERMILION_CITY    : { x: 108, y: 102 },
  ROUTE_9           : { x: 147, y:   3 },
  ROUTE_10          : { x: 162, y:   7 },
  LAVENDER_TOWN     : { x: 156, y:  30 }
};

const mapDir = path.resolve('src/data/maps');
const files = fs.readdirSync(mapDir).filter(f => f.endsWith('.json'));

for (const file of files) {
  const filePath = path.join(mapDir, file);
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  let changed = false;

  if (data.warps) {
    for (const w of data.warps) {
      if (KANTO_OFFSETS[w.targetMap]) {
        const offset = KANTO_OFFSETS[w.targetMap];
        w.targetMap = 'KANTO_OVERWORLD';
        w.targetPos.x += offset.x;
        w.targetPos.y += offset.y;
        changed = true;
      }
    }
  }

  if (changed) {
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`Updated ${file}`);
  }
}
