import { Move, Pokemon, InventoryItem, PokemonSummary, BaseStats } from './types';
import { calcHp } from './lib/damage';

/** Gen I base stats for all 151 Pokemon */
export const BASE_STATS: Record<string, BaseStats> = {
  // #001–#009: Bulbasaur line, Charmander line, Squirtle line
  bulbasaur:   { hp: 45,  attack: 49,  defense: 49,  special: 65,  speed: 45 },
  ivysaur:     { hp: 60,  attack: 62,  defense: 63,  special: 80,  speed: 60 },
  venusaur:    { hp: 80,  attack: 82,  defense: 83,  special: 100, speed: 80 },
  charmander:  { hp: 39,  attack: 52,  defense: 43,  special: 50,  speed: 65 },
  charmeleon:  { hp: 58,  attack: 64,  defense: 58,  special: 65,  speed: 80 },
  charizard:   { hp: 78,  attack: 84,  defense: 78,  special: 85,  speed: 100 },
  squirtle:    { hp: 44,  attack: 48,  defense: 65,  special: 50,  speed: 43 },
  wartortle:   { hp: 59,  attack: 63,  defense: 80,  special: 65,  speed: 58 },
  blastoise:   { hp: 79,  attack: 83,  defense: 100, special: 85,  speed: 78 },
  // #010–#018: Caterpie line, Weedle line, Pidgey line
  caterpie:    { hp: 45,  attack: 30,  defense: 35,  special: 20,  speed: 45 },
  metapod:     { hp: 50,  attack: 20,  defense: 55,  special: 25,  speed: 30 },
  butterfree:  { hp: 60,  attack: 45,  defense: 50,  special: 80,  speed: 70 },
  weedle:      { hp: 40,  attack: 35,  defense: 30,  special: 20,  speed: 50 },
  kakuna:      { hp: 45,  attack: 25,  defense: 50,  special: 25,  speed: 35 },
  beedrill:    { hp: 65,  attack: 80,  defense: 40,  special: 45,  speed: 75 },
  pidgey:      { hp: 40,  attack: 45,  defense: 40,  special: 35,  speed: 56 },
  pidgeotto:   { hp: 63,  attack: 60,  defense: 55,  special: 50,  speed: 71 },
  pidgeot:     { hp: 83,  attack: 80,  defense: 75,  special: 70,  speed: 101 },
  // #019–#026: Rattata line, Spearow line, Ekans line, Pikachu line
  rattata:     { hp: 30,  attack: 56,  defense: 35,  special: 25,  speed: 72 },
  raticate:    { hp: 55,  attack: 81,  defense: 60,  special: 50,  speed: 97 },
  spearow:     { hp: 40,  attack: 60,  defense: 30,  special: 31,  speed: 70 },
  fearow:      { hp: 65,  attack: 90,  defense: 65,  special: 61,  speed: 100 },
  ekans:       { hp: 35,  attack: 60,  defense: 44,  special: 40,  speed: 55 },
  arbok:       { hp: 60,  attack: 85,  defense: 69,  special: 65,  speed: 80 },
  pikachu:     { hp: 35,  attack: 55,  defense: 30,  special: 50,  speed: 90 },
  raichu:      { hp: 60,  attack: 90,  defense: 55,  special: 90,  speed: 100 },
  // #027–#034: Sandshrew line, Nidoran lines
  sandshrew:   { hp: 50,  attack: 75,  defense: 85,  special: 30,  speed: 40 },
  sandslash:   { hp: 75,  attack: 100, defense: 110, special: 55,  speed: 65 },
  'nidoran-f': { hp: 55,  attack: 47,  defense: 52,  special: 40,  speed: 41 },
  nidorina:    { hp: 70,  attack: 62,  defense: 67,  special: 55,  speed: 56 },
  nidoqueen:   { hp: 90,  attack: 82,  defense: 87,  special: 75,  speed: 76 },
  'nidoran-m': { hp: 46,  attack: 57,  defense: 40,  special: 40,  speed: 50 },
  nidorino:    { hp: 61,  attack: 72,  defense: 57,  special: 55,  speed: 65 },
  nidoking:    { hp: 81,  attack: 102, defense: 77,  special: 85,  speed: 85 },
  // #035–#040: Clefairy line, Vulpix line, Jigglypuff line
  clefairy:    { hp: 70,  attack: 45,  defense: 48,  special: 60,  speed: 35 },
  clefable:    { hp: 95,  attack: 70,  defense: 73,  special: 85,  speed: 60 },
  vulpix:      { hp: 38,  attack: 41,  defense: 40,  special: 65,  speed: 65 },
  ninetales:   { hp: 73,  attack: 76,  defense: 75,  special: 100, speed: 100 },
  jigglypuff:  { hp: 115, attack: 45,  defense: 20,  special: 25,  speed: 20 },
  wigglytuff:  { hp: 140, attack: 70,  defense: 45,  special: 50,  speed: 45 },
  // #041–#045: Zubat line, Oddish line
  zubat:       { hp: 40,  attack: 45,  defense: 35,  special: 40,  speed: 55 },
  golbat:      { hp: 75,  attack: 80,  defense: 70,  special: 75,  speed: 90 },
  oddish:      { hp: 45,  attack: 50,  defense: 55,  special: 75,  speed: 30 },
  gloom:       { hp: 60,  attack: 65,  defense: 70,  special: 85,  speed: 40 },
  vileplume:   { hp: 75,  attack: 80,  defense: 85,  special: 100, speed: 50 },
  // #046–#051: Paras line, Venonat line, Diglett line
  paras:       { hp: 35,  attack: 70,  defense: 55,  special: 55,  speed: 25 },
  parasect:    { hp: 60,  attack: 95,  defense: 80,  special: 80,  speed: 30 },
  venonat:     { hp: 60,  attack: 55,  defense: 50,  special: 40,  speed: 45 },
  venomoth:    { hp: 70,  attack: 65,  defense: 60,  special: 90,  speed: 90 },
  diglett:     { hp: 10,  attack: 55,  defense: 25,  special: 45,  speed: 95 },
  dugtrio:     { hp: 35,  attack: 80,  defense: 50,  special: 50,  speed: 120 },
  // #052–#057: Meowth line, Psyduck line, Mankey line
  meowth:      { hp: 40,  attack: 45,  defense: 35,  special: 40,  speed: 90 },
  persian:     { hp: 65,  attack: 70,  defense: 60,  special: 65,  speed: 115 },
  psyduck:     { hp: 50,  attack: 52,  defense: 48,  special: 50,  speed: 55 },
  golduck:     { hp: 80,  attack: 82,  defense: 78,  special: 80,  speed: 85 },
  mankey:      { hp: 40,  attack: 80,  defense: 35,  special: 35,  speed: 70 },
  primeape:    { hp: 65,  attack: 105, defense: 60,  special: 60,  speed: 95 },
  // #058–#062: Growlithe line, Poliwag line
  growlithe:   { hp: 55,  attack: 70,  defense: 45,  special: 50,  speed: 60 },
  arcanine:    { hp: 90,  attack: 110, defense: 80,  special: 80,  speed: 95 },
  poliwag:     { hp: 40,  attack: 50,  defense: 40,  special: 40,  speed: 90 },
  poliwhirl:   { hp: 65,  attack: 65,  defense: 65,  special: 50,  speed: 90 },
  poliwrath:   { hp: 90,  attack: 85,  defense: 95,  special: 70,  speed: 70 },
  // #063–#068: Abra line, Machop line
  abra:        { hp: 25,  attack: 20,  defense: 15,  special: 105, speed: 90 },
  kadabra:     { hp: 40,  attack: 35,  defense: 30,  special: 120, speed: 105 },
  alakazam:    { hp: 55,  attack: 50,  defense: 45,  special: 135, speed: 120 },
  machop:      { hp: 70,  attack: 80,  defense: 50,  special: 35,  speed: 35 },
  machoke:     { hp: 80,  attack: 100, defense: 70,  special: 50,  speed: 45 },
  machamp:     { hp: 90,  attack: 130, defense: 80,  special: 65,  speed: 55 },
  // #069–#076: Bellsprout line, Tentacool line, Geodude line
  bellsprout:  { hp: 50,  attack: 75,  defense: 35,  special: 70,  speed: 40 },
  weepinbell:  { hp: 65,  attack: 90,  defense: 50,  special: 85,  speed: 55 },
  victreebel:  { hp: 80,  attack: 105, defense: 65,  special: 100, speed: 70 },
  tentacool:   { hp: 40,  attack: 40,  defense: 35,  special: 100, speed: 70 },
  tentacruel:  { hp: 80,  attack: 70,  defense: 65,  special: 120, speed: 100 },
  geodude:     { hp: 40,  attack: 80,  defense: 100, special: 30,  speed: 20 },
  graveler:    { hp: 55,  attack: 95,  defense: 115, special: 45,  speed: 35 },
  golem:       { hp: 80,  attack: 110, defense: 130, special: 55,  speed: 45 },
  // #077–#082: Ponyta line, Slowpoke line, Magnemite line
  ponyta:      { hp: 50,  attack: 85,  defense: 55,  special: 65,  speed: 90 },
  rapidash:    { hp: 65,  attack: 100, defense: 70,  special: 80,  speed: 105 },
  slowpoke:    { hp: 90,  attack: 65,  defense: 65,  special: 40,  speed: 15 },
  slowbro:     { hp: 95,  attack: 75,  defense: 110, special: 80,  speed: 30 },
  magnemite:   { hp: 25,  attack: 35,  defense: 70,  special: 95,  speed: 45 },
  magneton:    { hp: 50,  attack: 60,  defense: 95,  special: 120, speed: 70 },
  // #083–#089: Farfetch'd, Doduo line, Seel line, Grimer line
  farfetchd:   { hp: 52,  attack: 65,  defense: 55,  special: 58,  speed: 60 },
  doduo:       { hp: 35,  attack: 85,  defense: 45,  special: 35,  speed: 75 },
  dodrio:      { hp: 60,  attack: 110, defense: 70,  special: 60,  speed: 100 },
  seel:        { hp: 65,  attack: 45,  defense: 55,  special: 70,  speed: 45 },
  dewgong:     { hp: 90,  attack: 70,  defense: 80,  special: 95,  speed: 70 },
  grimer:      { hp: 80,  attack: 80,  defense: 50,  special: 40,  speed: 25 },
  muk:         { hp: 105, attack: 105, defense: 75,  special: 65,  speed: 50 },
  // #090–#095: Shellder line, Gastly line, Onix
  shellder:    { hp: 30,  attack: 65,  defense: 100, special: 45,  speed: 40 },
  cloyster:    { hp: 50,  attack: 95,  defense: 180, special: 85,  speed: 70 },
  gastly:      { hp: 30,  attack: 35,  defense: 30,  special: 100, speed: 80 },
  haunter:     { hp: 45,  attack: 50,  defense: 45,  special: 115, speed: 95 },
  gengar:      { hp: 60,  attack: 65,  defense: 60,  special: 130, speed: 110 },
  onix:        { hp: 35,  attack: 45,  defense: 160, special: 30,  speed: 70 },
  // #096–#101: Drowzee line, Krabby line, Voltorb line
  drowzee:     { hp: 60,  attack: 48,  defense: 45,  special: 90,  speed: 42 },
  hypno:       { hp: 85,  attack: 73,  defense: 70,  special: 115, speed: 67 },
  krabby:      { hp: 30,  attack: 105, defense: 90,  special: 25,  speed: 50 },
  kingler:     { hp: 55,  attack: 130, defense: 115, special: 50,  speed: 75 },
  voltorb:     { hp: 40,  attack: 30,  defense: 50,  special: 55,  speed: 100 },
  electrode:   { hp: 60,  attack: 50,  defense: 70,  special: 80,  speed: 140 },
  // #102–#106: Exeggcute line, Cubone line, Hitmonlee
  exeggcute:   { hp: 60,  attack: 40,  defense: 80,  special: 60,  speed: 40 },
  exeggutor:   { hp: 95,  attack: 95,  defense: 85,  special: 125, speed: 55 },
  cubone:      { hp: 50,  attack: 50,  defense: 95,  special: 40,  speed: 35 },
  marowak:     { hp: 60,  attack: 80,  defense: 110, special: 50,  speed: 45 },
  hitmonlee:   { hp: 50,  attack: 120, defense: 53,  special: 35,  speed: 87 },
  // #107–#114: Hitmonchan, Lickitung, Koffing line, Rhyhorn line, Chansey, Tangela
  hitmonchan:  { hp: 50,  attack: 105, defense: 79,  special: 35,  speed: 76 },
  lickitung:   { hp: 90,  attack: 55,  defense: 75,  special: 60,  speed: 30 },
  koffing:     { hp: 40,  attack: 65,  defense: 95,  special: 60,  speed: 35 },
  weezing:     { hp: 65,  attack: 90,  defense: 120, special: 85,  speed: 60 },
  rhyhorn:     { hp: 80,  attack: 85,  defense: 95,  special: 30,  speed: 25 },
  rhydon:      { hp: 105, attack: 130, defense: 120, special: 45,  speed: 40 },
  chansey:     { hp: 250, attack: 5,   defense: 5,   special: 105, speed: 50 },
  tangela:     { hp: 65,  attack: 55,  defense: 115, special: 100, speed: 60 },
  // #115–#122: Kangaskhan, Horsea line, Goldeen line, Staryu line, Mr. Mime
  kangaskhan:  { hp: 105, attack: 95,  defense: 80,  special: 40,  speed: 90 },
  horsea:      { hp: 30,  attack: 40,  defense: 70,  special: 70,  speed: 60 },
  seadra:      { hp: 55,  attack: 65,  defense: 95,  special: 95,  speed: 85 },
  goldeen:     { hp: 45,  attack: 67,  defense: 60,  special: 50,  speed: 63 },
  seaking:     { hp: 80,  attack: 92,  defense: 65,  special: 80,  speed: 68 },
  staryu:      { hp: 30,  attack: 45,  defense: 55,  special: 70,  speed: 85 },
  starmie:     { hp: 60,  attack: 75,  defense: 85,  special: 100, speed: 115 },
  'mr-mime':   { hp: 40,  attack: 45,  defense: 65,  special: 100, speed: 90 },
  // #123–#130: Scyther, Jynx, Electabuzz, Magmar, Pinsir, Tauros, Magikarp, Gyarados
  scyther:     { hp: 70,  attack: 110, defense: 80,  special: 55,  speed: 105 },
  jynx:        { hp: 65,  attack: 50,  defense: 35,  special: 95,  speed: 95 },
  electabuzz:  { hp: 65,  attack: 83,  defense: 57,  special: 85,  speed: 105 },
  magmar:      { hp: 65,  attack: 95,  defense: 57,  special: 85,  speed: 93 },
  pinsir:      { hp: 65,  attack: 125, defense: 100, special: 55,  speed: 85 },
  tauros:      { hp: 75,  attack: 100, defense: 95,  special: 70,  speed: 110 },
  magikarp:    { hp: 20,  attack: 10,  defense: 55,  special: 20,  speed: 80 },
  gyarados:    { hp: 95,  attack: 125, defense: 79,  special: 100, speed: 81 },
  // #131–#137: Lapras, Ditto, Eevee, Vaporeon, Jolteon, Flareon, Porygon
  lapras:      { hp: 130, attack: 85,  defense: 80,  special: 95,  speed: 60 },
  ditto:       { hp: 48,  attack: 48,  defense: 48,  special: 48,  speed: 48 },
  eevee:       { hp: 55,  attack: 55,  defense: 50,  special: 65,  speed: 55 },
  vaporeon:    { hp: 130, attack: 65,  defense: 60,  special: 110, speed: 65 },
  jolteon:     { hp: 65,  attack: 65,  defense: 60,  special: 110, speed: 130 },
  flareon:     { hp: 65,  attack: 130, defense: 60,  special: 110, speed: 65 },
  porygon:     { hp: 65,  attack: 60,  defense: 70,  special: 75,  speed: 40 },
  // #138–#145: Omanyte line, Kabuto line, Aerodactyl, Snorlax, Articuno, Zapdos
  omanyte:     { hp: 35,  attack: 40,  defense: 100, special: 90,  speed: 35 },
  omastar:     { hp: 70,  attack: 60,  defense: 125, special: 115, speed: 55 },
  kabuto:      { hp: 30,  attack: 80,  defense: 90,  special: 45,  speed: 55 },
  kabutops:    { hp: 60,  attack: 115, defense: 105, special: 70,  speed: 80 },
  aerodactyl:  { hp: 80,  attack: 105, defense: 65,  special: 60,  speed: 130 },
  snorlax:     { hp: 160, attack: 110, defense: 65,  special: 65,  speed: 30 },
  articuno:    { hp: 90,  attack: 85,  defense: 100, special: 125, speed: 85 },
  zapdos:      { hp: 90,  attack: 90,  defense: 85,  special: 125, speed: 100 },
  // #146–#151: Moltres, Dratini line, Mewtwo, Mew
  moltres:     { hp: 90,  attack: 100, defense: 90,  special: 125, speed: 90 },
  dratini:     { hp: 41,  attack: 64,  defense: 45,  special: 50,  speed: 50 },
  dragonair:   { hp: 61,  attack: 84,  defense: 65,  special: 70,  speed: 70 },
  dragonite:   { hp: 91,  attack: 134, defense: 95,  special: 100, speed: 80 },
  mewtwo:      { hp: 106, attack: 110, defense: 90,  special: 154, speed: 130 },
  mew:         { hp: 100, attack: 100, defense: 100, special: 100, speed: 100 },
};

/** Helper: create a Pokemon with HP computed from base stats */
export function makePokemon(
  id: string,
  name: string,
  level: number,
  type: string,
  moves: Move[],
  spriteId: number,
  extra?: Partial<Pokemon>,
): Pokemon {
  const baseStats = BASE_STATS[id];
  const maxHp = calcHp(baseStats.hp, level);
  return {
    id,
    name,
    level,
    hp: maxHp,
    maxHp,
    type,
    baseStats,
    moves,
    sprite: getSprite(spriteId),
    exp: 0,
    expToNextLevel: level * 100 || 100,
    ...extra,
  };
}

export const MOVES: Record<string, Move> = {
  TACKLE: { name: 'PLACAJE', type: 'normal', power: 40, accuracy: 100 },
  THUNDERSHOCK: { name: 'IMPACTRUENO', type: 'electric', power: 40, accuracy: 100, statusEffect: 'paralyzed', statusChance: 10 },
  SCRATCH: { name: 'ARAÑAZO', type: 'normal', power: 40, accuracy: 100 },
  GROWL: { name: 'GRUÑIDO', type: 'normal', power: 0, accuracy: 100 },
  GUST: { name: 'TORNADO', type: 'flying', power: 40, accuracy: 100 },
  STRING_SHOT: { name: 'DISP. SEDA', type: 'bug', power: 0, accuracy: 95, statusEffect: 'paralyzed', statusChance: 30 },
  PECK: { name: 'PICOTAZO', type: 'flying', power: 35, accuracy: 100 },
  EMBER: { name: 'ASCUAS', type: 'fire', power: 40, accuracy: 100, statusEffect: 'burn', statusChance: 10 },
  WATER_GUN: { name: 'PISTOLA AGUA', type: 'water', power: 40, accuracy: 100 },
  VINE_WHIP: { name: 'LATIGO CEPA', type: 'grass', power: 45, accuracy: 100 },
  POISON_POWDER: { name: 'POLVO VENENO', type: 'poison', power: 0, accuracy: 75, statusEffect: 'poison', statusChance: 100 },
  SLEEP_POWDER: { name: 'SOMNÍFERO', type: 'grass', power: 0, accuracy: 75, statusEffect: 'sleep', statusChance: 100 },
  ROCK_THROW: { name: 'LANZARROCAS', type: 'rock', power: 50, accuracy: 90 },
  HARDEN: { name: 'FORTALEZA', type: 'normal', power: 0, accuracy: 100 },
};

const getSprite = (id: number) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;

export const STARTERS: Pokemon[] = [
  makePokemon('bulbasaur', 'BULBASAUR', 5, 'grass', [MOVES.TACKLE, MOVES.GROWL], 1, {
    types: ['grass', 'poison'], evolutionLevel: 16, evolvesTo: 'ivysaur',
    movesToLearn: [{ level: 7, move: MOVES.VINE_WHIP }, { level: 13, move: MOVES.POISON_POWDER }],
  }),
  makePokemon('charmander', 'CHARMANDER', 5, 'fire', [MOVES.SCRATCH, MOVES.GROWL], 4, {
    evolutionLevel: 16, evolvesTo: 'charmeleon',
    movesToLearn: [{ level: 7, move: MOVES.EMBER }],
  }),
  makePokemon('squirtle', 'SQUIRTLE', 5, 'water', [MOVES.TACKLE, MOVES.GROWL], 7, {
    evolutionLevel: 16, evolvesTo: 'wartortle',
    movesToLearn: [{ level: 7, move: MOVES.WATER_GUN }],
  }),
];

export const ITEMS_DATABASE: Record<string, InventoryItem> = {
  OAK_PARCEL: { id: 'OAK_PARCEL', name: 'PAQUETE OAK', description: 'Un paquete para el Prof. Oak.', icon: '📦', type: 'key_item' },
  POTION: { id: 'POTION', name: 'POCIÓN', description: 'Restaura 20 PS de un Pokémon.', icon: '🧪', type: 'potion' },
  POKEBALL: { id: 'POKEBALL', name: 'POKÉ BALL', description: 'Sirve para atrapar Pokémon salvajes.', icon: '🔴', type: 'pokeball' },
};

export const POKEMON_LIST: PokemonSummary[] = [
  { id: 'bulbasaur', name: 'Bulbasaur', sprite: getSprite(1) },
  { id: 'ivysaur', name: 'Ivysaur', sprite: getSprite(2) },
  { id: 'venusaur', name: 'Venusaur', sprite: getSprite(3) },
  { id: 'charmander', name: 'Charmander', sprite: getSprite(4) },
  { id: 'charmeleon', name: 'Charmeleon', sprite: getSprite(5) },
  { id: 'charizard', name: 'Charizard', sprite: getSprite(6) },
  { id: 'squirtle', name: 'Squirtle', sprite: getSprite(7) },
  { id: 'wartortle', name: 'Wartortle', sprite: getSprite(8) },
  { id: 'blastoise', name: 'Blastoise', sprite: getSprite(9) },
  { id: 'caterpie', name: 'Caterpie', sprite: getSprite(10) },
  { id: 'metapod', name: 'Metapod', sprite: getSprite(11) },
  { id: 'butterfree', name: 'Butterfree', sprite: getSprite(12) },
  { id: 'weedle', name: 'Weedle', sprite: getSprite(13) },
  { id: 'kakuna', name: 'Kakuna', sprite: getSprite(14) },
  { id: 'beedrill', name: 'Beedrill', sprite: getSprite(15) },
  { id: 'pidgey', name: 'Pidgey', sprite: getSprite(16) },
  { id: 'pidgeotto', name: 'Pidgeotto', sprite: getSprite(17) },
  { id: 'pidgeot', name: 'Pidgeot', sprite: getSprite(18) },
  { id: 'rattata', name: 'Rattata', sprite: getSprite(19) },
  { id: 'raticate', name: 'Raticate', sprite: getSprite(20) },
  { id: 'spearow', name: 'Spearow', sprite: getSprite(21) },
  { id: 'fearow', name: 'Fearow', sprite: getSprite(22) },
  { id: 'ekans', name: 'Ekans', sprite: getSprite(23) },
  { id: 'arbok', name: 'Arbok', sprite: getSprite(24) },
  { id: 'pikachu', name: 'Pikachu', sprite: getSprite(25) },
  { id: 'raichu', name: 'Raichu', sprite: getSprite(26) },
  { id: 'sandshrew', name: 'Sandshrew', sprite: getSprite(27) },
  { id: 'sandslash', name: 'Sandslash', sprite: getSprite(28) },
  { id: 'nidoran-f', name: 'Nidoran♀', sprite: getSprite(29) },
  { id: 'nidorina', name: 'Nidorina', sprite: getSprite(30) },
  { id: 'nidoqueen', name: 'Nidoqueen', sprite: getSprite(31) },
  { id: 'nidoran-m', name: 'Nidoran♂', sprite: getSprite(32) },
  { id: 'nidorino', name: 'Nidorino', sprite: getSprite(33) },
  { id: 'nidoking', name: 'Nidoking', sprite: getSprite(34) },
  { id: 'clefairy', name: 'Clefairy', sprite: getSprite(35) },
  { id: 'clefable', name: 'Clefable', sprite: getSprite(36) },
  { id: 'vulpix', name: 'Vulpix', sprite: getSprite(37) },
  { id: 'ninetales', name: 'Ninetales', sprite: getSprite(38) },
  { id: 'jigglypuff', name: 'Jigglypuff', sprite: getSprite(39) },
  { id: 'wigglytuff', name: 'Wigglytuff', sprite: getSprite(40) },
  { id: 'zubat', name: 'Zubat', sprite: getSprite(41) },
  { id: 'golbat', name: 'Golbat', sprite: getSprite(42) },
  { id: 'oddish', name: 'Oddish', sprite: getSprite(43) },
  { id: 'gloom', name: 'Gloom', sprite: getSprite(44) },
  { id: 'vileplume', name: 'Vileplume', sprite: getSprite(45) },
  { id: 'paras', name: 'Paras', sprite: getSprite(46) },
  { id: 'parasect', name: 'Parasect', sprite: getSprite(47) },
  { id: 'venonat', name: 'Venonat', sprite: getSprite(48) },
  { id: 'venomoth', name: 'Venomoth', sprite: getSprite(49) },
  { id: 'diglett', name: 'Diglett', sprite: getSprite(50) },
  { id: 'dugtrio', name: 'Dugtrio', sprite: getSprite(51) },
  { id: 'meowth', name: 'Meowth', sprite: getSprite(52) },
  { id: 'persian', name: 'Persian', sprite: getSprite(53) },
  { id: 'psyduck', name: 'Psyduck', sprite: getSprite(54) },
  { id: 'golduck', name: 'Golduck', sprite: getSprite(55) },
  { id: 'mankey', name: 'Mankey', sprite: getSprite(56) },
  { id: 'primeape', name: 'Primeape', sprite: getSprite(57) },
  { id: 'growlithe', name: 'Growlithe', sprite: getSprite(58) },
  { id: 'arcanine', name: 'Arcanine', sprite: getSprite(59) },
  { id: 'poliwag', name: 'Poliwag', sprite: getSprite(60) },
  { id: 'poliwhirl', name: 'Poliwhirl', sprite: getSprite(61) },
  { id: 'poliwrath', name: 'Poliwrath', sprite: getSprite(62) },
  { id: 'abra', name: 'Abra', sprite: getSprite(63) },
  { id: 'kadabra', name: 'Kadabra', sprite: getSprite(64) },
  { id: 'alakazam', name: 'Alakazam', sprite: getSprite(65) },
  { id: 'machop', name: 'Machop', sprite: getSprite(66) },
  { id: 'machoke', name: 'Machoke', sprite: getSprite(67) },
  { id: 'machamp', name: 'Machamp', sprite: getSprite(68) },
  { id: 'bellsprout', name: 'Bellsprout', sprite: getSprite(69) },
  { id: 'weepinbell', name: 'Weepinbell', sprite: getSprite(70) },
  { id: 'victreebel', name: 'Victreebel', sprite: getSprite(71) },
  { id: 'tentacool', name: 'Tentacool', sprite: getSprite(72) },
  { id: 'tentacruel', name: 'Tentacruel', sprite: getSprite(73) },
  { id: 'geodude', name: 'Geodude', sprite: getSprite(74) },
  { id: 'graveler', name: 'Graveler', sprite: getSprite(75) },
  { id: 'golem', name: 'Golem', sprite: getSprite(76) },
  { id: 'ponyta', name: 'Ponyta', sprite: getSprite(77) },
  { id: 'rapidash', name: 'Rapidash', sprite: getSprite(78) },
  { id: 'slowpoke', name: 'Slowpoke', sprite: getSprite(79) },
  { id: 'slowbro', name: 'Slowbro', sprite: getSprite(80) },
  { id: 'magnemite', name: 'Magnemite', sprite: getSprite(81) },
  { id: 'magneton', name: 'Magneton', sprite: getSprite(82) },
  { id: 'farfetchd', name: "Farfetch'd", sprite: getSprite(83) },
  { id: 'doduo', name: 'Doduo', sprite: getSprite(84) },
  { id: 'dodrio', name: 'Dodrio', sprite: getSprite(85) },
  { id: 'seel', name: 'Seel', sprite: getSprite(86) },
  { id: 'dewgong', name: 'Dewgong', sprite: getSprite(87) },
  { id: 'grimer', name: 'Grimer', sprite: getSprite(88) },
  { id: 'muk', name: 'Muk', sprite: getSprite(89) },
  { id: 'shellder', name: 'Shellder', sprite: getSprite(90) },
  { id: 'cloyster', name: 'Cloyster', sprite: getSprite(91) },
  { id: 'gastly', name: 'Gastly', sprite: getSprite(92) },
  { id: 'haunter', name: 'Haunter', sprite: getSprite(93) },
  { id: 'gengar', name: 'Gengar', sprite: getSprite(94) },
  { id: 'onix', name: 'Onix', sprite: getSprite(95) },
  { id: 'drowzee', name: 'Drowzee', sprite: getSprite(96) },
  { id: 'hypno', name: 'Hypno', sprite: getSprite(97) },
  { id: 'krabby', name: 'Krabby', sprite: getSprite(98) },
  { id: 'kingler', name: 'Kingler', sprite: getSprite(99) },
  { id: 'voltorb', name: 'Voltorb', sprite: getSprite(100) },
  { id: 'electrode', name: 'Electrode', sprite: getSprite(101) },
  { id: 'exeggcute', name: 'Exeggcute', sprite: getSprite(102) },
  { id: 'exeggutor', name: 'Exeggutor', sprite: getSprite(103) },
  { id: 'cubone', name: 'Cubone', sprite: getSprite(104) },
  { id: 'marowak', name: 'Marowak', sprite: getSprite(105) },
  { id: 'hitmonlee', name: 'Hitmonlee', sprite: getSprite(106) },
  { id: 'hitmonchan', name: 'Hitmonchan', sprite: getSprite(107) },
  { id: 'lickitung', name: 'Lickitung', sprite: getSprite(108) },
  { id: 'koffing', name: 'Koffing', sprite: getSprite(109) },
  { id: 'weezing', name: 'Weezing', sprite: getSprite(110) },
  { id: 'rhyhorn', name: 'Rhyhorn', sprite: getSprite(111) },
  { id: 'rhydon', name: 'Rhydon', sprite: getSprite(112) },
  { id: 'chansey', name: 'Chansey', sprite: getSprite(113) },
  { id: 'tangela', name: 'Tangela', sprite: getSprite(114) },
  { id: 'kangaskhan', name: 'Kangaskhan', sprite: getSprite(115) },
  { id: 'horsea', name: 'Horsea', sprite: getSprite(116) },
  { id: 'seadra', name: 'Seadra', sprite: getSprite(117) },
  { id: 'goldeen', name: 'Goldeen', sprite: getSprite(118) },
  { id: 'seaking', name: 'Seaking', sprite: getSprite(119) },
  { id: 'staryu', name: 'Staryu', sprite: getSprite(120) },
  { id: 'starmie', name: 'Starmie', sprite: getSprite(121) },
  { id: 'mr-mime', name: 'Mr. Mime', sprite: getSprite(122) },
  { id: 'scyther', name: 'Scyther', sprite: getSprite(123) },
  { id: 'jynx', name: 'Jynx', sprite: getSprite(124) },
  { id: 'electabuzz', name: 'Electabuzz', sprite: getSprite(125) },
  { id: 'magmar', name: 'Magmar', sprite: getSprite(126) },
  { id: 'pinsir', name: 'Pinsir', sprite: getSprite(127) },
  { id: 'tauros', name: 'Tauros', sprite: getSprite(128) },
  { id: 'magikarp', name: 'Magikarp', sprite: getSprite(129) },
  { id: 'gyarados', name: 'Gyarados', sprite: getSprite(130) },
  { id: 'lapras', name: 'Lapras', sprite: getSprite(131) },
  { id: 'ditto', name: 'Ditto', sprite: getSprite(132) },
  { id: 'eevee', name: 'Eevee', sprite: getSprite(133) },
  { id: 'vaporeon', name: 'Vaporeon', sprite: getSprite(134) },
  { id: 'jolteon', name: 'Jolteon', sprite: getSprite(135) },
  { id: 'flareon', name: 'Flareon', sprite: getSprite(136) },
  { id: 'porygon', name: 'Porygon', sprite: getSprite(137) },
  { id: 'omanyte', name: 'Omanyte', sprite: getSprite(138) },
  { id: 'omastar', name: 'Omastar', sprite: getSprite(139) },
  { id: 'kabuto', name: 'Kabuto', sprite: getSprite(140) },
  { id: 'kabutops', name: 'Kabutops', sprite: getSprite(141) },
  { id: 'aerodactyl', name: 'Aerodactyl', sprite: getSprite(142) },
  { id: 'snorlax', name: 'Snorlax', sprite: getSprite(143) },
  { id: 'articuno', name: 'Articuno', sprite: getSprite(144) },
  { id: 'zapdos', name: 'Zapdos', sprite: getSprite(145) },
  { id: 'moltres', name: 'Moltres', sprite: getSprite(146) },
  { id: 'dratini', name: 'Dratini', sprite: getSprite(147) },
  { id: 'dragonair', name: 'Dragonair', sprite: getSprite(148) },
  { id: 'dragonite', name: 'Dragonite', sprite: getSprite(149) },
  { id: 'mewtwo', name: 'Mewtwo', sprite: getSprite(150) },
  { id: 'mew', name: 'Mew', sprite: getSprite(151) },
];

export const EVOLUTIONS: Record<string, Partial<Pokemon>> = {
  ivysaur: { name: 'IVYSAUR', sprite: getSprite(2), baseStats: BASE_STATS.ivysaur, types: ['grass', 'poison'], evolutionLevel: 32, evolvesTo: 'venusaur' },
  venusaur: { name: 'VENUSAUR', sprite: getSprite(3), baseStats: BASE_STATS.venusaur, types: ['grass', 'poison'] },
  charmeleon: { name: 'CHARMELEON', sprite: getSprite(5), baseStats: BASE_STATS.charmeleon, evolutionLevel: 36, evolvesTo: 'charizard' },
  charizard: { name: 'CHARIZARD', sprite: getSprite(6), baseStats: BASE_STATS.charizard, types: ['fire', 'flying'] },
  wartortle: { name: 'WARTORTLE', sprite: getSprite(8), baseStats: BASE_STATS.wartortle, evolutionLevel: 36, evolvesTo: 'blastoise' },
  blastoise: { name: 'BLASTOISE', sprite: getSprite(9), baseStats: BASE_STATS.blastoise },
};

export const WILD_POKEMON_DATABASE: Record<string, Pokemon[]> = {
  ROUTE_1: [
    makePokemon('pidgey', 'PIDGEY', 4, 'flying', [MOVES.TACKLE, MOVES.GUST], 16, { types: ['normal', 'flying'] }),
    makePokemon('rattata', 'RATTATA', 4, 'normal', [MOVES.TACKLE, MOVES.SCRATCH], 19),
    makePokemon('caterpie', 'CATERPIE', 3, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('weedle', 'WEEDLE', 3, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
    makePokemon('spearow', 'SPEAROW', 5, 'flying', [MOVES.PECK, MOVES.GROWL], 21, { types: ['normal', 'flying'] }),
    makePokemon('mankey', 'MANKEY', 5, 'fighting', [MOVES.SCRATCH, MOVES.TACKLE], 56),
    makePokemon('pikachu', 'PIKACHU', 6, 'electric', [MOVES.THUNDERSHOCK, MOVES.GROWL], 25),
  ],
  VIRIDIAN_FOREST: [
    makePokemon('caterpie', 'CATERPIE', 4, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 10),
    makePokemon('weedle', 'WEEDLE', 4, 'bug', [MOVES.TACKLE, MOVES.STRING_SHOT], 13, { types: ['bug', 'poison'] }),
    makePokemon('metapod', 'METAPOD', 6, 'bug', [MOVES.HARDEN], 11),
    makePokemon('pikachu', 'PIKACHU', 6, 'electric', [MOVES.THUNDERSHOCK, MOVES.GROWL], 25),
  ],
};
